import { randomUUID } from 'node:crypto';
import type { Transaction } from '@nursery/db';
import {
 receiptCorrectionInputSchema,expenseCorrectionInputSchema,transferCorrectionInputSchema,tuitionReductionInputSchema,refundInputSchema,financeQuerySchema,
 type CorrectionOptions,type CorrectionReceipt,type CorrectionExpense,type CorrectionTransfer,type CorrectionTuition,type RefundableCredit,type RefundRecord,type FinancialCorrectionRecord,type Receipt
} from '@nursery/contracts';
import { cairoIsoDate } from '@nursery/domain';
import { SafeError } from '../../errors.js';
import { denied,requireBranch,requireCapability,requireSensitiveCorrection,type Policy } from '../organization/policy.js';
import { FinancialCore,financeScope,invalid,type FinanceResource } from './core.js';
import { LedgerService,type DueItem } from './ledger.js';
import { PaymentService } from './payments.js';
import { SpendingService } from './spending.js';
import { TreasuryService,type LockedAccount } from './treasury.js';

type OriginalReceipt={id:string;branch_id:string;account_id:string;amount:string;collected_on:string;kind:'PAYMENT'|'CREDIT';payer_name:string;external_reference:string;lines:Receipt['lines']};
type OriginalExpense={settlement_id:string;branch_id:string;classroom_id:string|null;account_id:string;amount:string};
type OriginalTransfer={id:string;source_account_id:string;destination_account_id:string;amount:string};
const insufficient=()=>new SafeError('VALIDATION_ERROR','spending.insufficientFunds',false,409);

export class CorrectionService {
 constructor(readonly core:FinancialCore,readonly ledger:LedgerService,readonly treasury:TreasuryService,readonly payments:PaymentService,readonly spending:SpendingService) {}
 private current(date:string) {this.core.date(date);if(date!==cairoIsoDate()) throw invalid();}
 private sensitive(p:Policy,resource:FinanceResource) {requireSensitiveCorrection(p,resource);}
 private replay(p:Policy) {if(!p.sensitiveFinancialEdit) throw denied();}
 private async fundedNet(tx:Transaction,accounts:LockedAccount[],deltas:Map<string,bigint>) {
  const balances=(await tx.query<{id:string;balance:string}>('select id,balance::text from treasury_balances where id=any($1::uuid[])',[accounts.map(a=>a.id)])).rows;
  for(const a of accounts) if(BigInt(balances.find(b=>b.id===a.id)?.balance??'0')+(deltas.get(a.id)??0n)<0n) throw insufficient();
 }
 private add(delta:Map<string,bigint>,id:string,amount:bigint) {delta.set(id,(delta.get(id)??0n)+amount);}
 private async correction(tx:Transaction,p:Policy,input:{operationId:string;effectiveOn:string;reason:string},targetKind:string,targetId:string,action:string) {
  const id=randomUUID();await tx.query('insert into financial_corrections(id,target_kind,target_id,action,effective_on,reason,actor_id,operation_id) values($1,$2,$3,$4,$5,$6,$7,$8)',[id,targetKind,targetId,action,input.effectiveOn,input.reason,p.account.id,input.operationId]);return id;
 }
 private async postCorrection(tx:Transaction,p:Policy,correctionId:string,accountId:string,leg:string,amount:string,effectiveOn:string,reason:string,sourceReceiptId:string|null=null) {
  await tx.query("insert into treasury_movements(id,account_id,kind,correction_id,correction_leg,source_receipt_id,amount,effective_on,reason,actor_id) values($1,$2,'CORRECTION',$3,$4,$5,$6,$7,$8,$9)",[randomUUID(),accountId,correctionId,leg,sourceReceiptId,amount,effectiveOn,reason,p.account.id]);
 }
 async options(token:string):Promise<CorrectionOptions> {
  return this.core.children.withPolicy(token,async(tx,p)=>{
   requireCapability(p,'finance.read');const enabled=Boolean((await tx.query("select 1 from module_settings where module_key='FINANCE' and enabled")).rowCount);
   const system=p.account.kind==='SYSTEM',branchMode=system||p.scope.mode==='BRANCH',branches=p.scope.branchIds;
   const accounts=(await tx.query<CorrectionOptions['accounts'][number]>('select a.id,a.branch_id as "branchId",a.code,a.name,a.type,b.balance::text from treasury_accounts a join treasury_balances b on b.id=a.id where ($1::boolean or a.branch_id=any($2::uuid[])) order by a.code limit 100',[system,branches])).rows;
   const receipts=(await tx.query<CorrectionReceipt>(`select r.id,r.reference,r.branch_id as "branchId",r.account_id as "accountId",r.account_code as "accountCode",r.amount::text,r.collected_on::text as "collectedOn",r.payer_name as "payerName",
    coalesce((select json_agg(json_build_object('id',a.id,'installmentId',a.installment_id,'amount',a.amount::text,'activeAmount',(a.amount+coalesce((select sum(x.amount) from receipt_allocations x where x.reverses_id=a.id),0))::text,'childId',o.child_id,'childCode',o.child_code,'childName',o.child_name,'classroomId',o.classroom_id,'categoryName',o.category_name) order by a.id) from receipt_allocations a join installments i on i.id=a.installment_id join obligations o on o.id=i.obligation_id where a.receipt_id=r.id and a.reverses_id is null),'[]') as allocations
    from receipts r where r.kind='PAYMENT' and not exists(select 1 from receipt_corrections c where c.original_receipt_id=r.id)
    and not exists(select 1 from receipt_allocations x where x.receipt_id=r.id and x.reverses_id is not null)
    and ($1::boolean or r.branch_id=any($2::uuid[])) and ($3::boolean or not exists(select 1 from jsonb_array_elements(r.lines) l where l->>'classroomId' is null or not ((l->>'classroomId')::uuid=any($4::uuid[]))))
    order by r.collected_on desc,r.reference desc limit 100`,[system,branches,branchMode,p.scope.classroomIds])).rows;
   const s=financeScope(p,'finance.read','e');
   const expenses=(await tx.query<CorrectionExpense>(`select e.id,e.settlement_id as "settlementId",e.branch_id as "branchId",e.classroom_id as "classroomId",e.category_name as "categoryName",e.amount::text as "plannedAmount",e.paid_amount::text as "paidAmount",e.account_id as "accountId",a.code as "accountCode",e.paid_on::text as "paidOn" from expense_states e join treasury_accounts a on a.id=e.account_id where e.state='PAID' and ${s.sql} order by e.paid_on desc,e.id limit 100`,s.values)).rows;
   const transfers=branchMode?(await tx.query<CorrectionTransfer>(`select t.id,t.source_account_id as "sourceAccountId",t.destination_account_id as "destinationAccountId",s.code as "sourceCode",d.code as "destinationCode",t.amount::text,t.effective_on::text as "effectiveOn" from account_transfers t join treasury_accounts s on s.id=t.source_account_id join treasury_accounts d on d.id=t.destination_account_id where not exists(select 1 from transfer_corrections c where c.original_transfer_id=t.id) and ($1::boolean or (s.branch_id=any($2::uuid[]) and d.branch_id=any($2::uuid[]))) order by t.effective_on desc,t.id limit 100`,[system,branches])).rows:[];
   const tuition=(await tx.query<CorrectionTuition>(`select b.id as "installmentId",o.branch_id as "branchId",o.classroom_id as "classroomId",o.child_id as "childId",o.child_code as "childCode",o.child_name as "childName",o.category_name as "categoryName",b.due_on::text as "dueOn",(b.amount+b.adjustments)::text as "effectiveAmount",b.remaining::text,b.allocated::text as paid,b.credited::text from installment_balances b join obligations o on o.id=b.obligation_id where o.category_kind='TUITION' and b.amount+b.adjustments>0 and ${financeScope(p,'finance.read','o').sql} order by o.child_code,b.due_on,b.id limit 100`,financeScope(p,'finance.read','o').values)).rows;
   const credits=(await tx.query<RefundableCredit>(`select c.id,c.child_id as "childId",ch.code as "childCode",ch.full_name as "childName",c.branch_id as "branchId",c.amount::text,b.remaining::text,c.created_on::text as "createdOn",c.reason,
    coalesce((select json_agg(json_build_object('id',o.id,'receiptId',o.receipt_id,'receiptReference',r.reference,'accountId',o.account_id,'accountCode',r.account_code,'amount',o.amount::text,'remaining',ob.remaining::text) order by r.reference) from credit_origin_balances ob join credit_origins o on o.id=ob.id join receipts r on r.id=o.receipt_id where o.credit_id=c.id and ob.remaining>0),'[]') as origins
    from credits c join credit_balances b on b.id=c.id join children ch on ch.id=c.child_id where b.remaining>0 and ($1::boolean or c.branch_id=any($2::uuid[])) and ($3::boolean or ch.classroom_id=any($4::uuid[])) order by c.created_on,c.id limit 100`,[system,branches,branchMode,p.scope.classroomIds])).rows;
   return {canCorrect:enabled&&p.sensitiveFinancialEdit&&p.account.capabilities.includes('finance.correct'),accounts,receipts,expenses,transfers,tuition,credits};
  });
 }
 async correctReceipt(token:string,id:string,raw:unknown) {
  const input=receiptCorrectionInputSchema.parse(raw);let original:OriginalReceipt,dues:DueItem[],accounts:LockedAccount[];
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'RECEIPT_CORRECTION',{id,...input},'finance.correct',async()=>{
   original=(await tx.query<OriginalReceipt>('select id,branch_id,account_id,amount::text,collected_on::text,kind,payer_name,external_reference,lines from receipts where id=$1',[id])).rows[0];if(!original||original.kind!=='PAYMENT'||(await tx.query('select 1 from receipt_corrections where original_receipt_id=$1',[id])).rowCount||(await tx.query('select 1 from receipt_allocations where receipt_id=$1 and reverses_id is not null',[id])).rowCount) throw invalid();
   const originals=(await tx.query<{installment_id:string}>('select installment_id from receipt_allocations where receipt_id=$1 and reverses_id is null order by installment_id',[id])).rows.map(r=>r.installment_id);const ids=[...new Set([...originals,...(input.replacement?.allocations.map(a=>a.installmentId)??[])])];
   dues=await this.ledger.lockDue(tx,p,ids,'finance.correct');for(const d of dues) this.sensitive(p,{branchId:d.branch_id,classroomId:d.classroom_id??undefined,childId:d.child_id});
   accounts=await this.treasury.lockAccounts(tx,p,[original.account_id,...(input.replacement?[input.replacement.accountId]:[])]);return this.resources(dues,accounts);
  },async()=>{
   this.current(input.effectiveOn);const replacement=input.replacement,accountIds=accounts.map(a=>a.id);await this.core.cashDateOpen(tx,accountIds,input.effectiveOn);
   const delta=new Map<string,bigint>();this.add(delta,original.account_id,-BigInt(original.amount));if(replacement)this.add(delta,replacement.accountId,BigInt(replacement.amount));await this.fundedNet(tx,accounts,delta);
   if(replacement) {const a=accounts.find(x=>x.id===replacement.accountId)!;if(a.branch_id!==original.branch_id||a.type!==replacement.method||input.effectiveOn<a.opened_on||replacement.allocations.reduce((n,x)=>n+BigInt(x.amount),0n)!==BigInt(replacement.amount)) throw invalid();}
   const correctionId=await this.correction(tx,p,input,'RECEIPT',id,replacement?'REPLACEMENT':'REVERSAL');
   const allocations=(await tx.query<{id:string;receipt_id:string;installment_id:string;amount:string}>('select id,receipt_id,installment_id,amount::text from receipt_allocations where receipt_id=$1 and reverses_id is null order by id',[id])).rows;
   for(const a of allocations) await tx.query('insert into receipt_allocations(id,receipt_id,installment_id,amount,reverses_id,correction_id) values($1,$2,$3,$4,$5,$6)',[randomUUID(),a.receipt_id,a.installment_id,(-BigInt(a.amount)).toString(),a.id,correctionId]);
   let replacementReceiptId:null|string=null;
   if(replacement) {
    const fresh=(await tx.query<DueItem>(`select b.id,b.obligation_id,o.child_id,o.branch_id,o.classroom_id,o.child_code,o.child_name,o.category_name,o.category_kind,b.remaining::text,o.issued_on::text,b.due_on::text from installment_balances b join obligations o on o.id=b.obligation_id where b.id=any($1::uuid[]) order by b.id`,[replacement.allocations.map(a=>a.installmentId)])).rows;
    for(const a of replacement.allocations) {const d=fresh.find(x=>x.id===a.installmentId);if(!d||d.branch_id!==original.branch_id) throw invalid();this.ledger.validateAllocation(d,a.amount,input.effectiveOn);}
    const lines=replacement.allocations.map(a=>{const d=fresh.find(x=>x.id===a.installmentId)!;return {childId:d.child_id,childCode:d.child_code,childName:d.child_name,classroomId:d.classroom_id,installmentId:d.id,categoryName:d.category_name,amount:a.amount};});
    replacementReceiptId=await this.payments.receipt(tx,p,{operationId:input.operationId,collectedOn:input.effectiveOn,payerName:replacement.payerName,externalReference:replacement.externalReference},accounts.find(a=>a.id===replacement.accountId)!,replacement.amount,'PAYMENT',lines);
    for(const a of replacement.allocations) await tx.query('insert into receipt_allocations(id,receipt_id,installment_id,amount) values($1,$2,$3,$4)',[randomUUID(),replacementReceiptId,a.installmentId,a.amount]);
    await this.treasury.postReceiptInTransaction(tx,p,replacementReceiptId,'finance.correct');
   }
   await tx.query('insert into receipt_corrections(correction_id,original_receipt_id,replacement_receipt_id) values($1,$2,$3)',[correctionId,id,replacementReceiptId]);
   await this.postCorrection(tx,p,correctionId,original.account_id,'RECEIPT_REVERSAL',(-BigInt(original.amount)).toString(),input.effectiveOn,input.reason,id);return {correctionId,replacementReceiptId};
  },async()=>{this.replay(p);}));
 }
 private resources(dues:DueItem[],accounts:LockedAccount[]) {return [...dues.map(d=>({branchId:d.branch_id,classroomId:d.classroom_id??undefined,childId:d.child_id})),...accounts.map(a=>({branchId:a.branch_id}))];}
 async correctExpense(token:string,id:string,raw:unknown) {
  const input=expenseCorrectionInputSchema.parse(raw);let original:OriginalExpense,accounts:LockedAccount[];
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'EXPENSE_CORRECTION',{id,...input},'finance.correct',async()=>{
   await tx.query('select id from expenses where id=$1 for update',[id]);original=(await tx.query<OriginalExpense>(`select settlement_id,branch_id,classroom_id,account_id,paid_amount::text as amount from expense_states where id=$1 and state='PAID'`,[id])).rows[0];if(!original) throw invalid();this.sensitive(p,{branchId:original.branch_id,classroomId:original.classroom_id??undefined});
   accounts=await this.treasury.lockAccounts(tx,p,[original.account_id,...(input.replacement?[input.replacement.accountId]:[])]);for(const a of accounts)this.sensitive(p,{branchId:a.branch_id});return [{branchId:original.branch_id,classroomId:original.classroom_id??undefined},...accounts.map(a=>({branchId:a.branch_id}))];
  },async()=>{
   this.current(input.effectiveOn);const replacement=input.replacement;if(replacement){const a=accounts.find(x=>x.id===replacement.accountId)!;if(a.branch_id!==original.branch_id||a.type!==replacement.method||input.effectiveOn<a.opened_on)throw invalid();}
   await this.core.cashDateOpen(tx,accounts.map(a=>a.id),input.effectiveOn);const delta=new Map<string,bigint>();this.add(delta,original.account_id,BigInt(original.amount));if(replacement)this.add(delta,replacement.accountId,-BigInt(replacement.amount));await this.fundedNet(tx,accounts,delta);
   const correctionId=await this.correction(tx,p,input,'EXPENSE',original.settlement_id,replacement?'REPLACEMENT':'REVERSAL');await tx.query('insert into expense_corrections(correction_id,original_settlement_id,replacement_account_id,replacement_amount,replacement_method,external_reference) values($1,$2,$3,$4,$5,$6)',[correctionId,original.settlement_id,replacement?.accountId??null,replacement?.amount??null,replacement?.method??null,replacement?.externalReference??null]);
   await this.postCorrection(tx,p,correctionId,original.account_id,'EXPENSE_REVERSAL',original.amount,input.effectiveOn,input.reason);if(replacement)await this.postCorrection(tx,p,correctionId,replacement.accountId,'EXPENSE_REPLACEMENT',(-BigInt(replacement.amount)).toString(),input.effectiveOn,input.reason);return {correctionId};
  },async()=>{this.replay(p);}));
 }
 async correctTransfer(token:string,id:string,raw:unknown) {
  const input=transferCorrectionInputSchema.parse(raw);let original:OriginalTransfer,accounts:LockedAccount[];
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'TRANSFER_CORRECTION',{id,...input},'finance.correct',async()=>{
   original=(await tx.query<OriginalTransfer>('select id,source_account_id,destination_account_id,amount::text from account_transfers where id=$1',[id])).rows[0];if(!original||(await tx.query('select 1 from transfer_corrections where original_transfer_id=$1',[id])).rowCount)throw invalid();accounts=await this.treasury.lockAccounts(tx,p,[original.source_account_id,original.destination_account_id,...(input.replacement?[input.replacement.sourceAccountId,input.replacement.destinationAccountId]:[])]);for(const a of accounts)this.sensitive(p,{branchId:a.branch_id});return accounts.map(a=>({branchId:a.branch_id}));
  },async()=>{
   this.current(input.effectiveOn);if(accounts.some(a=>input.effectiveOn<a.opened_on))throw invalid();await this.core.cashDateOpen(tx,accounts.map(a=>a.id),input.effectiveOn);const delta=new Map<string,bigint>();this.add(delta,original.source_account_id,BigInt(original.amount));this.add(delta,original.destination_account_id,-BigInt(original.amount));if(input.replacement){this.add(delta,input.replacement.sourceAccountId,-BigInt(input.replacement.amount));this.add(delta,input.replacement.destinationAccountId,BigInt(input.replacement.amount));}await this.fundedNet(tx,accounts,delta);
   const correctionId=await this.correction(tx,p,input,'TRANSFER',id,input.replacement?'REPLACEMENT':'REVERSAL'),r=input.replacement;await tx.query('insert into transfer_corrections(correction_id,original_transfer_id,replacement_source_account_id,replacement_destination_account_id,replacement_amount,external_reference) values($1,$2,$3,$4,$5,$6)',[correctionId,id,r?.sourceAccountId??null,r?.destinationAccountId??null,r?.amount??null,r?.externalReference??null]);
   await this.postCorrection(tx,p,correctionId,original.source_account_id,'TRANSFER_REVERSAL_SOURCE',original.amount,input.effectiveOn,input.reason);await this.postCorrection(tx,p,correctionId,original.destination_account_id,'TRANSFER_REVERSAL_DESTINATION',(-BigInt(original.amount)).toString(),input.effectiveOn,input.reason);if(r){await this.postCorrection(tx,p,correctionId,r.sourceAccountId,'TRANSFER_REPLACEMENT_SOURCE',(-BigInt(r.amount)).toString(),input.effectiveOn,input.reason);await this.postCorrection(tx,p,correctionId,r.destinationAccountId,'TRANSFER_REPLACEMENT_DESTINATION',r.amount,input.effectiveOn,input.reason);}return {correctionId};
  },async()=>{this.replay(p);}));
 }
 async reduceTuition(token:string,id:string,raw:unknown) {
  const input=tuitionReductionInputSchema.parse(raw);let due:DueItem;
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'TUITION_REDUCTION',{id,...input},'finance.correct',async()=>{[due]=await this.ledger.lockDue(tx,p,[id],'finance.correct');this.sensitive(p,{branchId:due.branch_id,classroomId:due.classroom_id??undefined,childId:due.child_id});return [{branchId:due.branch_id,classroomId:due.classroom_id??undefined,childId:due.child_id}];},async()=>{
   this.current(input.effectiveOn);const state=(await tx.query<{effective:string;remaining:string;kind:string}>(`select (b.amount+b.adjustments)::text as effective,b.remaining::text,o.category_kind as kind from installment_balances b join obligations o on o.id=b.obligation_id where b.id=$1`,[id])).rows[0];if(!state||state.kind!=='TUITION'||BigInt(input.reductionAmount)>BigInt(state.effective))throw invalid();
   const excess=BigInt(input.reductionAmount)>BigInt(state.remaining)?BigInt(input.reductionAmount)-BigInt(state.remaining):0n;
   const creditSources=(await tx.query<{id:string;credit_id:string;amount:string}>(`select a.id,a.credit_id,(a.amount+coalesce((select sum(x.amount) from credit_allocations x where x.reverses_id=a.id),0))::text as amount from credit_allocations a where a.installment_id=$1 and a.reverses_id is null and a.amount+coalesce((select sum(x.amount) from credit_allocations x where x.reverses_id=a.id),0)>0 order by a.applied_on desc,a.id desc`,[id])).rows;
   await tx.query('select id from credits where id=any($1::uuid[]) order by id for update',[[...new Set(creditSources.map(x=>x.credit_id))].sort()]);
   const receiptSources=(await tx.query<{id:string;receipt_id:string;account_id:string;amount:string}>(`select a.id,a.receipt_id,r.account_id,(a.amount+coalesce((select sum(x.amount) from receipt_allocations x where x.reverses_id=a.id),0))::text as amount from receipt_allocations a join receipts r on r.id=a.receipt_id where a.installment_id=$1 and a.reverses_id is null and a.amount+coalesce((select sum(x.amount) from receipt_allocations x where x.reverses_id=a.id),0)>0 order by r.collected_on desc,r.reference desc,a.id desc`,[id])).rows;
   let remaining=excess,restored=0n,newCredit=0n;const creditReversals:{source:typeof creditSources[number];amount:bigint}[]=[],receiptReversals:{source:typeof receiptSources[number];amount:bigint}[]=[];
   for(const source of creditSources){if(!remaining)break;const amount=remaining<BigInt(source.amount)?remaining:BigInt(source.amount);creditReversals.push({source,amount});restored+=amount;remaining-=amount;}
   for(const source of receiptSources){if(!remaining)break;const amount=remaining<BigInt(source.amount)?remaining:BigInt(source.amount);receiptReversals.push({source,amount});newCredit+=amount;remaining-=amount;}
   if(remaining)throw invalid();const correctionId=await this.correction(tx,p,input,'TUITION',id,'REDUCTION'),adjustmentId=randomUUID();await tx.query('insert into obligation_adjustments(id,installment_id,amount,reason,actor_id,effective_on,correction_id) values($1,$2,$3,$4,$5,$6,$7)',[adjustmentId,id,(-BigInt(input.reductionAmount)).toString(),input.reason,p.account.id,input.effectiveOn,correctionId]);
   for(const x of creditReversals)await tx.query('insert into credit_allocations(id,credit_id,installment_id,amount,applied_on,reverses_id,correction_id) values($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),x.source.credit_id,id,(-x.amount).toString(),input.effectiveOn,x.source.id,correctionId]);
   for(const x of receiptReversals)await tx.query('insert into receipt_allocations(id,receipt_id,installment_id,amount,reverses_id,correction_id) values($1,$2,$3,$4,$5,$6)',[randomUUID(),x.source.receipt_id,id,(-x.amount).toString(),x.source.id,correctionId]);
   let creditId:null|string=null;if(newCredit){creditId=randomUUID();await tx.query('insert into credits(id,child_id,branch_id,receipt_id,amount,reason,created_on,correction_id) values($1,$2,$3,null,$4,$5,$6,$7)',[creditId,due.child_id,due.branch_id,newCredit.toString(),input.reason,input.effectiveOn,correctionId]);const grouped=new Map<string,{accountId:string;amount:bigint}>();for(const x of receiptReversals){const old=grouped.get(x.source.receipt_id);grouped.set(x.source.receipt_id,{accountId:x.source.account_id,amount:(old?.amount??0n)+x.amount});}for(const [receiptId,origin] of grouped)await tx.query('insert into credit_origins(id,credit_id,receipt_id,account_id,amount) values($1,$2,$3,$4,$5)',[randomUUID(),creditId,receiptId,origin.accountId,origin.amount.toString()]);}
   await tx.query('insert into tuition_corrections(correction_id,installment_id,adjustment_id,reduction_amount,remaining_before,restored_credit_amount,new_credit_id) values($1,$2,$3,$4,$5,$6,$7)',[correctionId,id,adjustmentId,input.reductionAmount,state.remaining,restored.toString(),creditId]);return {correctionId,creditId,creditAmount:newCredit.toString(),restoredCreditAmount:restored.toString()};
  },async()=>{this.replay(p);}));
 }
 async refund(token:string,raw:unknown) {
  const input=refundInputSchema.parse(raw);let credit:{id:string;child_id:string;branch_id:string;classroom_id:string|null;remaining:string},origin:{id:string;receipt_id:string;account_id:string;remaining:string},accounts:LockedAccount[];
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'CREDIT_REFUND',input,'finance.correct',async()=>{
   const witness=(await tx.query<{child_id:string}>('select child_id from credits where id=$1',[input.creditId])).rows[0];if(!witness)throw denied();await this.core.lockChildren(tx,[witness.child_id]);await tx.query('select id from credits where id=$1 for update',[input.creditId]);credit=(await tx.query<typeof credit>('select c.id,c.child_id,c.branch_id,ch.classroom_id,b.remaining::text from credits c join children ch on ch.id=c.child_id join credit_balances b on b.id=c.id where c.id=$1',[input.creditId])).rows[0];this.sensitive(p,{branchId:credit.branch_id,classroomId:credit.classroom_id??undefined,childId:credit.child_id});origin=(await tx.query<typeof origin>('select id,receipt_id,account_id,remaining::text from credit_origin_balances where id=$1 and credit_id=$2',[input.creditOriginId,input.creditId])).rows[0];if(!origin)throw invalid();accounts=await this.treasury.lockAccounts(tx,p,[origin.account_id,input.accountId]);for(const a of accounts)this.sensitive(p,{branchId:a.branch_id});return [{branchId:credit.branch_id,classroomId:credit.classroom_id??undefined,childId:credit.child_id},...accounts.map(a=>({branchId:a.branch_id}))];
  },async()=>{
   this.core.date(input.refundedOn);if(BigInt(input.amount)>BigInt(credit.remaining)||BigInt(input.amount)>BigInt(origin.remaining))throw invalid();const funding=accounts.find(a=>a.id===input.accountId)!;if(funding.type!==input.method||input.refundedOn<funding.opened_on||input.accountId!==origin.account_id&&!input.alternativeAccountConfirmed)throw invalid();await this.core.cashDateOpen(tx,[funding.id],input.refundedOn);await this.spending.funded(tx,funding.id,input.amount);
   const id=randomUUID();await tx.query('insert into refunds(id,credit_id,credit_origin_id,original_receipt_id,original_account_id,funding_account_id,funding_branch_id,amount,method,refunded_on,reason,external_reference,alternative_account_confirmed,actor_id,operation_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[id,input.creditId,input.creditOriginId,origin.receipt_id,origin.account_id,funding.id,funding.branch_id,input.amount,input.method,input.refundedOn,input.reason,input.externalReference,input.alternativeAccountConfirmed,p.account.id,input.operationId]);await tx.query("insert into treasury_movements(id,account_id,kind,refund_id,amount,effective_on,reason,actor_id) values($1,$2,'REFUND',$3,$4,$5,$6,$7)",[randomUUID(),funding.id,id,(-BigInt(input.amount)).toString(),input.refundedOn,input.reason,p.account.id]);return {id};
  },async()=>{this.replay(p);}));
 }
 async corrections(token:string,raw:unknown):Promise<FinancialCorrectionRecord[]> {
  const q=financeQuerySchema.parse(raw);return this.core.children.withPolicy(token,async(tx,p)=>{requireCapability(p,'finance.read');if(q.branchId)requireBranch(p,q.branchId);const system=p.account.kind==='SYSTEM',branchMode=system||p.scope.mode==='BRANCH';return (await tx.query<FinancialCorrectionRecord>(`with visible as (
   select c.id,c.target_kind,c.target_id,c.action,c.effective_on,c.reason,c.actor_id from financial_corrections c join receipt_corrections d on d.correction_id=c.id join receipts r on r.id=d.original_receipt_id where c.target_kind='RECEIPT' and ($1::boolean or r.branch_id=any($2::uuid[])) and ($3::boolean or not exists(select 1 from jsonb_array_elements(r.lines) l where l->>'classroomId' is null or not ((l->>'classroomId')::uuid=any($4::uuid[]))))
   union all select c.id,c.target_kind,c.target_id,c.action,c.effective_on,c.reason,c.actor_id from financial_corrections c join expense_corrections d on d.correction_id=c.id join expense_settlements s on s.id=d.original_settlement_id join expenses e on e.id=s.expense_id where c.target_kind='EXPENSE' and ($1::boolean or e.branch_id=any($2::uuid[])) and ($3::boolean or e.classroom_id=any($4::uuid[]))
   union all select c.id,c.target_kind,c.target_id,c.action,c.effective_on,c.reason,c.actor_id from financial_corrections c join transfer_corrections d on d.correction_id=c.id join account_transfers t on t.id=d.original_transfer_id join treasury_accounts a on a.id=t.source_account_id join treasury_accounts b on b.id=t.destination_account_id where c.target_kind='TRANSFER' and $3 and ($1::boolean or (a.branch_id=any($2::uuid[]) and b.branch_id=any($2::uuid[])))
   union all select c.id,c.target_kind,c.target_id,c.action,c.effective_on,c.reason,c.actor_id from financial_corrections c join tuition_corrections d on d.correction_id=c.id join installments i on i.id=d.installment_id join obligations o on o.id=i.obligation_id where c.target_kind='TUITION' and ($1::boolean or o.branch_id=any($2::uuid[])) and ($3::boolean or o.classroom_id=any($4::uuid[]))
  ) select v.id,v.target_kind as "targetKind",v.target_id as "targetId",v.action,v.effective_on::text as "effectiveOn",v.reason,a.username_normalized as actor from visible v join accounts a on a.id=v.actor_id where ($5::uuid is null or exists(select 1 from financial_operations f,jsonb_array_elements(f.resources) r where f.actor_id=v.actor_id and f.operation_id=(select operation_id from financial_corrections where id=v.id) and (r->>'branchId')::uuid=$5)) order by v.effective_on desc,v.id limit $6 offset $7`,[system,p.scope.branchIds,branchMode,p.scope.classroomIds,q.branchId??null,q.limit,q.offset])).rows;});
 }
 async refunds(token:string,raw:unknown):Promise<RefundRecord[]> {
  const q=financeQuerySchema.parse(raw);return this.core.children.withPolicy(token,async(tx,p)=>{const s=financeScope(p,'finance.read','ch');if(q.branchId)requireBranch(p,q.branchId);return (await tx.query<RefundRecord>(`select r.id,r.credit_id as "creditId",ch.code as "childCode",ch.full_name as "childName",r.amount::text,r.refunded_on::text as "refundedOn",original.reference as "originalReceiptReference",oa.code as "originalAccountCode",fa.code as "fundingAccountCode",r.reason from refunds r join credits c on c.id=r.credit_id join children ch on ch.id=c.child_id join receipts original on original.id=r.original_receipt_id join treasury_accounts oa on oa.id=r.original_account_id join treasury_accounts fa on fa.id=r.funding_account_id where ${s.sql} and ($5::uuid is null or c.branch_id=$5) order by r.refunded_on desc,r.id limit $6 offset $7`,[...s.values,q.branchId??null,q.limit,q.offset])).rows;});
 }
}
