import { BillingService } from './billing.js';
import { ReceiptService } from './receipts.js';
import { ReminderService } from './reminders.js';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { FinancialCore } from './core.js';
import { LedgerService } from './ledger.js';
import { TreasuryService } from './treasury.js';
import { PaymentService } from './payments.js';
import { SpendingService } from './spending.js';
import { ExpenseDocumentService } from './expense-documents.js';
import { ClosingService } from './closing.js';
import { CorrectionService } from './corrections.js';
declare module 'fastify' { interface FastifyInstance { corrections:CorrectionService;closing:ClosingService;expenseDocuments:ExpenseDocumentService;spending:SpendingService;billing:BillingService;financialCore:FinancialCore;ledger:LedgerService;treasury:TreasuryService;payments:PaymentService } }
export function installFinance(app:FastifyInstance) {
  const core=new FinancialCore(app.children),ledger=new LedgerService(core),treasury=new TreasuryService(core),payments=new PaymentService(core,ledger,treasury);
  const billing=new BillingService(core);app.decorate('billing',billing);
  app.decorate('financialCore',core);app.decorate('ledger',ledger);app.decorate('treasury',treasury);app.decorate('payments',payments);
  const id=(raw:unknown)=>z.object({id:z.uuid()}).strict().parse(raw).id;
  const spending=new SpendingService(core,treasury);app.decorate('spending',spending);
  const corrections=new CorrectionService(core,ledger,treasury,payments,spending);app.decorate('corrections',corrections);
  const closing=new ClosingService(core,treasury);app.decorate('closing',closing);
  app.get('/api/v1/finance/correction-options',async r=>({data:await corrections.options(r.sessionToken)}));
  app.get('/api/v1/finance/corrections',async r=>({data:await corrections.corrections(r.sessionToken,r.query)}));
  app.get('/api/v1/finance/refunds',async r=>({data:await corrections.refunds(r.sessionToken,r.query)}));
  app.post('/api/v1/finance/receipts/:id/correct',async r=>({data:await corrections.correctReceipt(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/expenses/:id/correct',async r=>({data:await corrections.correctExpense(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/finance/transfers/:id/correct',async r=>({data:await corrections.correctTransfer(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/finance/installments/:id/reduce',async r=>({data:await corrections.reduceTuition(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/finance/refunds',async r=>({data:await corrections.refund(r.sessionToken,r.body)}));
  app.get('/api/v1/finance/closing-options',async r=>({data:await closing.options(r.sessionToken)}));
  app.get('/api/v1/finance/closing-current',async r=>({data:await closing.current(r.sessionToken,r.query)}));
  app.get('/api/v1/finance/closings',async r=>({data:await closing.list(r.sessionToken,r.query)}));
  app.post('/api/v1/finance/closings',async r=>({data:await closing.count(r.sessionToken,r.body)}));
  app.post('/api/v1/finance/closings/:id/reopen',async r=>({data:await closing.reopen(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/finance/closings/:id/adjust',async r=>({data:await closing.adjust(r.sessionToken,id(r.params),r.body)}));
  const expenseDocuments=new ExpenseDocumentService(spending,app.childDocuments.store.configuredRoot);app.decorate('expenseDocuments',expenseDocuments);
  app.get('/api/v1/expenses/:id/documents',async r=>({data:await expenseDocuments.list(r.sessionToken,id(r.params))}));
  app.post('/api/v1/expenses/:id/documents',{bodyLimit:7*1024*1024+4096},async r=>({data:await expenseDocuments.upload(r.sessionToken,id(r.params),r.body)}));
  app.get('/api/v1/expense-documents/:id/download',async(r,reply)=>{const file=await expenseDocuments.download(r.sessionToken,id(r.params));return reply.type(file.mimeType).header('Cache-Control','private, no-store').header('Content-Disposition',`attachment; filename="${file.filename}"`).send(file.bytes);});
  app.post('/api/v1/expense-documents/:id/retire',async r=>({data:await expenseDocuments.retire(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/expense-documents/cleanup',async r=>{z.object({}).strict().parse(r.body);return {data:await expenseDocuments.cleanup(r.sessionToken)};});
  app.get('/api/v1/expenses/options',async r=>({data:await spending.options(r.sessionToken)}));
  app.get('/api/v1/expenses',async r=>({data:await spending.list(r.sessionToken,r.query)}));
  app.post('/api/v1/expenses',async r=>({data:await spending.create(r.sessionToken,r.body)}));
  app.post('/api/v1/expenses/categories',async r=>({data:await spending.category(r.sessionToken,r.body)}));
  app.post('/api/v1/expenses/settings',async r=>({data:await spending.configure(r.sessionToken,r.body)}));
  app.get('/api/v1/expenses/:id/history',async r=>({data:await spending.history(r.sessionToken,id(r.params))}));
  app.post('/api/v1/expenses/:id/approve',async r=>({data:await spending.act(r.sessionToken,id(r.params),'APPROVED',r.body)}));
  app.post('/api/v1/expenses/:id/cancel',async r=>({data:await spending.act(r.sessionToken,id(r.params),'CANCELLED',r.body)}));
  app.post('/api/v1/expenses/:id/pay',async r=>({data:await spending.pay(r.sessionToken,id(r.params),r.body)}));
  app.post('/api/v1/finance/transfers',async r=>({data:await spending.transfer(r.sessionToken,r.body)}));
  app.get('/api/v1/finance/transfers',async r=>({data:await spending.transfers(r.sessionToken,r.query)}));
  app.get('/api/v1/billing/agreements',async r=>({data:await billing.list(r.sessionToken,r.query)}));
  app.get('/api/v1/billing/options',async r=>({data:await billing.options(r.sessionToken,r.query)}));
  app.post('/api/v1/billing/agreements',{bodyLimit:65536},async r=>({data:await billing.draft(r.sessionToken,r.body)}));
  app.get('/api/v1/billing/agreements/:id/catchup',async r=>({data:await billing.preview(r.sessionToken,id(r.params))}));
  for(const action of ['approve','price','pause','end','catchup'] as const) app.post(`/api/v1/billing/agreements/:id/${action}`,{bodyLimit:65536},async r=>({data:await billing[action](r.sessionToken,id(r.params),r.body)}));
  app.get('/api/v1/finance/options',async r=>({data:await treasury.options(r.sessionToken)}));
  app.get('/api/v1/finance/accounts',async r=>({data:await treasury.accounts(r.sessionToken,r.query)}));
  app.post('/api/v1/finance/accounts',async r=>({data:await treasury.createAccount(r.sessionToken,r.body)}));
  app.post('/api/v1/finance/branches/:id/default-account',async r=>({data:await treasury.setDefault(r.sessionToken,id(r.params),r.body)}));
  app.get('/api/v1/finance/accounts/:id/movements',async r=>({data:await treasury.movements(r.sessionToken,id(r.params),r.query)}));
  app.get('/api/v1/finance/categories',async r=>({data:await ledger.categories(r.sessionToken)}));
  app.get('/api/v1/finance/collection-options',async r=>({data:await ledger.collectionOptions(r.sessionToken)}));
  app.get('/api/v1/finance/outstanding',async r=>({data:await ledger.outstanding(r.sessionToken,r.query)}));
  const reminders=new ReminderService(ledger);
  app.post('/api/v1/finance/installments/:id/reminders',async r=>({data:await reminders.resend(r.sessionToken,id(r.params),r.body)}));
  app.get('/api/v1/finance/reminders',async r=>({data:await reminders.inbox(r.sessionToken,r.query)}));
  app.post('/api/v1/finance/categories',async r=>({data:await ledger.category(r.sessionToken,r.body)}));
  app.get('/api/v1/finance/balances',async r=>({data:await ledger.balances(r.sessionToken,r.query)}));
  app.get('/api/v1/finance/children/:id/balances',async r=>({data:await ledger.balances(r.sessionToken,r.query,id(r.params))}));
  app.get('/api/v1/parent/payment-options',async r=>({data:await ledger.parentOptions(r.sessionToken)}));
  app.get('/api/v1/parent/children/:id/receipts',async r=>({data:await payments.receipts(r.sessionToken,r.query,id(r.params))}));
  app.post('/api/v1/finance/obligations',{bodyLimit:65536},async r=>({data:await ledger.createObligation(r.sessionToken,r.body)}));
  app.post('/api/v1/payments',{bodyLimit:262144},async r=>({data:await payments.collect(r.sessionToken,r.body)}));
  app.post('/api/v1/finance/credit-receipts',async r=>({data:await payments.receiveCredit(r.sessionToken,r.body)}));
  app.post('/api/v1/finance/credit-applications',{bodyLimit:65536},async r=>({data:await payments.applyCredit(r.sessionToken,r.body)}));
  app.get('/api/v1/finance/receipts',async r=>({data:await payments.receipts(r.sessionToken,r.query)}));
  app.get('/api/v1/finance/receipts/:id',async r=>({data:await payments.getReceipt(r.sessionToken,id(r.params))}));
  const receiptFiles=new ReceiptService(payments);
  app.get('/api/v1/finance/receipts/:id/download',async(r,reply)=>{const file=await receiptFiles.download(r.sessionToken,id(r.params));return reply.type('application/pdf').header('Cache-Control','private, no-store').header('Content-Disposition',`attachment; filename="${file.filename}"`).send(file.bytes);});
  app.get('/api/v1/finance/operations/:id',async r=>({data:await core.operationStatus(r.sessionToken,id(r.params))}));
}
