import { randomUUID } from 'node:crypto';
import { postObligation,type Transaction } from '@nursery/db';
import { activityCancelInputSchema,activityConsentInputSchema,activityCreateInputSchema,busPermissionInputSchema,busSubscriptionInputSchema,transportQuerySchema,type Activity,type BusSubscription,type TransportOptions } from '@nursery/contracts';
import { cairoIsoDate } from '@nursery/domain';
import { denied,requireCapability,requireRecord,requireSensitiveCorrection,type Policy } from '../organization/policy.js';
import { requireChild,resolveChild,staffChildScope } from '../children/policy.js';
import { FinancialCore,invalid } from './core.js';
import type { CorrectionService } from './corrections.js';

type SubscriptionRow={id:string;child_id:string;branch_id:string;classroom_id:string|null;child_code:string;child_name:string;period_start:string;period_end:string;amount:string;administrative_permission:boolean;version:number;obligation_id:string|null;installment_id:string|null;remaining:string|null;child_status?:string};
const transportModule=async(tx:Transaction,key:'TRANSPORT'|'ACTIVITIES')=>{if(!(await tx.query('select 1 from module_settings where module_key=$1 and enabled',[key])).rowCount) throw new (await import('../../errors.js')).SafeError('MODULE_DISABLED',`${key.toLowerCase()}.disabled`,false,403);};
export class TransportService {
 constructor(readonly core:FinancialCore,readonly corrections:CorrectionService) {}
 private async category(tx:Transaction,id:string,kind:'BUS'|'TRIP') {if(!(await tx.query('select 1 from fee_categories where id=$1 and kind=$2',[id,kind])).rowCount) throw invalid();}
 private dto(r:SubscriptionRow):BusSubscription {const paid=r.amount==='0'||r.remaining==='0',today=cairoIsoDate(),current=r.period_start<=today&&today<=r.period_end;return {id:r.id,childId:r.child_id,childCode:r.child_code,childName:r.child_name,branchId:r.branch_id,periodStart:r.period_start,periodEnd:r.period_end,amount:r.amount,administrativePermission:r.administrative_permission,paid,noFee:r.amount==='0',eligible:current&&paid&&r.administrative_permission&&r.child_status==='ACTIVE',version:r.version,obligationId:r.obligation_id,installmentId:r.installment_id};}
 async options(token:string):Promise<TransportOptions> {return this.core.children.withPolicy(token,async(tx,p)=>{
  const capability=p.account.capabilities.includes('activities.manage')?'activities.manage':p.account.capabilities.includes('transport.manage')?'transport.manage':null;if(!capability)throw denied();const scope=staffChildScope(p,capability);
  const modules=Object.fromEntries((await tx.query<{module_key:string;enabled:boolean}>("select module_key,enabled from module_settings where module_key in ('TRANSPORT','ACTIVITIES','FINANCE')")).rows.map(r=>[r.module_key,r.enabled]));
  return {modules:{transport:Boolean(modules.TRANSPORT),activities:Boolean(modules.ACTIVITIES),finance:Boolean(modules.FINANCE)},branches:(await tx.query<{id:string;code:string;name:string}>('select id,code,name from branches where ($1::boolean or id=any($2::uuid[])) order by code',scope.values.slice(0,2))).rows,children:(await tx.query<TransportOptions['children'][number]>(`select c.id,c.code,c.full_name as "fullName",c.branch_id as "branchId",c.classroom_id as "classroomId" from children c where c.status='ACTIVE' and ${scope.sql} order by c.code,c.id`,scope.values)).rows,categories:(await tx.query<TransportOptions['categories'][number]>("select id,code,name,kind from fee_categories where kind in ('BUS','TRIP') order by code")).rows};
 });}
 async subscribe(token:string,raw:unknown) {
  const input=busSubscriptionInputSchema.parse(raw);let child:Awaited<ReturnType<typeof resolveChild>>;
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'BUS_SUBSCRIBE',input,'transport.manage',async()=>{await transportModule(tx,'TRANSPORT');child=await resolveChild(tx,input.childId,true);if(child.status!=='ACTIVE')throw invalid();requireChild(p,'transport.manage',child);await this.category(tx,input.categoryId,'BUS');return [{branchId:child.branchId,classroomId:child.classroomId??undefined,childId:child.id}];},async()=>{
   const posted=await postObligation(tx,p.account.id,child,{operationId:randomUUID(),childId:child.id,categoryId:input.categoryId,amount:input.amount,description:`Bus ${input.periodStart} to ${input.periodEnd}`,sourceReference:`bus/${child.id}/${input.periodStart}/${input.periodEnd}`,issuedOn:cairoIsoDate(),serviceFrom:input.periodStart,serviceUntil:input.periodEnd,installments:[{dueOn:input.dueOn,amount:input.amount}]});const id=randomUUID();await tx.query('insert into bus_subscriptions(id,child_id,branch_id,classroom_id,child_code,child_name,period_start,period_end,amount,administrative_permission,category_id,obligation_id,installment_id,actor_id,operation_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[id,child.id,child.branchId,child.classroomId,child.code,child.fullName,input.periodStart,input.periodEnd,input.amount,input.administrativePermission,input.categoryId,posted.id,posted.installmentIds[0],p.account.id,input.operationId]);return {id,obligationId:posted.id,installmentId:posted.installmentIds[0]};},undefined,input.amount!=='0'));
 }
 async permission(token:string,id:string,raw:unknown) {const input=busPermissionInputSchema.parse(raw);return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'BUS_PERMISSION',{id,...input},'transport.manage',async()=>{await transportModule(tx,'TRANSPORT');const r=(await tx.query<SubscriptionRow>('select s.*,null::text as remaining from bus_subscriptions s where id=$1 for update',[id])).rows[0];if(!r)throw denied();requireRecord(p,'transport.manage',{branchId:r.branch_id,classroomId:r.classroom_id??undefined,childId:r.child_id});if(r.version!==input.expectedVersion)throw invalid();return [{branchId:r.branch_id,classroomId:r.classroom_id??undefined,childId:r.child_id}];},async()=>{await tx.query('insert into bus_permission_events(id,subscription_id,actor_id,operation_id,enabled,reason) values($1,$2,$3,$4,$5,$6)',[randomUUID(),id,p.account.id,input.operationId,input.enabled,input.reason]);await tx.query('update bus_subscriptions set administrative_permission=$2,version=version+1 where id=$1',[id,input.enabled]);return {id,enabled:input.enabled};},undefined,false));}
 async subscriptions(token:string,raw:unknown) {const q=transportQuerySchema.parse(raw);return this.core.children.withPolicy(token,async(tx,p)=>{requireCapability(p,'transport.read');const scope=staffChildScope(p,'transport.read');if(q.branchId)requireRecord(p,'transport.read',{branchId:q.branchId});const rows=(await tx.query<SubscriptionRow>(`select s.*,s.period_start::text as period_start,s.period_end::text as period_end,s.amount::text as amount,c.branch_id,c.classroom_id,c.status as child_status,coalesce(b.remaining,0)::text as remaining from bus_subscriptions s left join installment_balances b on b.id=s.installment_id join children c on c.id=s.child_id where ${scope.sql} and ($5::uuid is null or c.branch_id=$5) order by s.period_start desc,s.id limit $6 offset $7`,[...scope.values,q.branchId??null,q.limit,q.offset])).rows;return rows.map(r=>this.dto(r));});}
 async createActivity(token:string,raw:unknown) {const input=activityCreateInputSchema.parse(raw);let children:Awaited<ReturnType<typeof resolveChild>>[]=[];return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'ACTIVITY_CREATE',input,'activities.manage',async()=>{await transportModule(tx,'ACTIVITIES');requireRecord(p,'activities.manage',{branchId:input.branchId});await this.category(tx,input.categoryId,'TRIP');children=[];for(const id of [...input.childIds].sort()){const c=await resolveChild(tx,id,true);if(c.status!=='ACTIVE'||c.branchId!==input.branchId)throw invalid();requireChild(p,'activities.manage',c);children.push(c);}return children.map(c=>({branchId:c.branchId,classroomId:c.classroomId??undefined,childId:c.id}));},async()=>{const id=randomUUID();await tx.query("insert into activities(id,branch_id,category_id,title,details,event_date,fee,actor_id,operation_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,input.branchId,input.categoryId,input.title,input.details,input.eventDate,input.fee,p.account.id,input.operationId]);for(const c of children){const posted=await postObligation(tx,p.account.id,c,{operationId:randomUUID(),childId:c.id,categoryId:input.categoryId,amount:input.fee,description:input.title,sourceReference:`activity/${id}/${c.id}`,issuedOn:cairoIsoDate(),serviceFrom:input.eventDate,serviceUntil:input.eventDate,installments:[{dueOn:input.dueOn,amount:input.fee}]});await tx.query('insert into activity_children(id,activity_id,child_id,child_code,child_name,classroom_id,obligation_id,installment_id) values($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),id,c.id,c.code,c.fullName,c.classroomId,posted.id,posted.installmentIds[0]]);}return {id};},undefined,input.fee!=='0'));}
 async consent(token:string,id:string,childId:string,raw:unknown) {const input=activityConsentInputSchema.parse(raw);return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'ACTIVITY_CONSENT',{id,childId,...input},'activities.manage',async()=>{await transportModule(tx,'ACTIVITIES');const r=(await tx.query<{branch_id:string;classroom_id:string|null}>('select a.branch_id,ac.classroom_id from activities a join activity_children ac on ac.activity_id=a.id where a.id=$1 and ac.child_id=$2 and a.status=\'ACTIVE\' for update of a,ac',[id,childId])).rows[0];if(!r)throw denied();requireRecord(p,'activities.manage',{branchId:r.branch_id,classroomId:r.classroom_id??undefined,childId});return [{branchId:r.branch_id,classroomId:r.classroom_id??undefined,childId}];},async()=>{const row=(await tx.query<{id:string}>('select id from activity_children where activity_id=$1 and child_id=$2',[id,childId])).rows[0];await tx.query('insert into activity_consents(id,activity_child_id,actor_id,operation_id,consented,reason) values($1,$2,$3,$4,$5,$6)',[randomUUID(),row.id,p.account.id,input.operationId,input.consented,input.reason]);return {id,childId,consented:input.consented};},undefined,false));}
 async activities(token:string,raw:unknown):Promise<Activity[]> {const q=transportQuerySchema.parse(raw);return this.core.children.withPolicy(token,async(tx,p)=>{requireCapability(p,'activities.read');const scope=staffChildScope(p,'activities.read');if(q.branchId)requireRecord(p,'activities.read',{branchId:q.branchId});return (await tx.query<Activity>(`select a.id,a.branch_id as "branchId",a.title,a.details,a.event_date::text as "eventDate",a.fee::text,a.status,coalesce(json_agg(json_build_object('childId',ac.child_id,'childCode',ac.child_code,'childName',ac.child_name,'classroomId',ac.classroom_id,'paid',a.fee=0 or b.remaining=0,'noFee',a.fee=0,'consented',coalesce((select c.consented from activity_consents c where c.activity_child_id=ac.id order by c.created_at desc,c.id desc limit 1),false),'participating',a.status='ACTIVE' and (a.fee=0 or b.remaining=0) and coalesce((select c.consented from activity_consents c where c.activity_child_id=ac.id order by c.created_at desc,c.id desc limit 1),false),'obligationId',ac.obligation_id,'installmentId',ac.installment_id) order by ac.child_code) filter(where ac.id is not null),'[]') as items from activities a left join activity_children ac on ac.activity_id=a.id left join installment_balances b on b.id=ac.installment_id join children c on c.id=ac.child_id where ${scope.sql.replaceAll('c.branch_id','a.branch_id').replaceAll('c.classroom_id','ac.classroom_id')} and ($5::uuid is null or a.branch_id=$5) group by a.id order by a.event_date desc,a.id limit $6 offset $7`,[...scope.values,q.branchId??null,q.limit,q.offset])).rows;});}
 async cancel(token:string,id:string,raw:unknown) {
  const input=activityCancelInputSchema.parse(raw);let dues:import('./ledger.js').DueItem[]=[];let reductions:{due:import('./ledger.js').DueItem;amount:string}[]=[];const resources:{branchId:string;classroomId?:string;childId?:string}[]=[];
  const authorize=async(tx:Transaction,p:Policy,allowCancelled=false)=>{
   await transportModule(tx,'ACTIVITIES');const a=(await tx.query<{branch_id:string;status:string;fee:string}>('select branch_id,status,fee::text from activities where id=$1 for update',[id])).rows[0];if(!a||(!allowCancelled&&a.status!=='ACTIVE'))throw invalid();requireRecord(p,'activities.manage',{branchId:a.branch_id});
   const participants=(await tx.query<{child_id:string;classroom_id:string|null;installment_id:string}>(`select child_id,classroom_id,installment_id from activity_children where activity_id=$1 order by child_id for update`,[id])).rows;if(!participants.length)throw invalid();
   if(a.fee==='0'){dues=[];reductions=[];resources.splice(0);for(const row of participants){requireRecord(p,'activities.manage',{branchId:a.branch_id,classroomId:row.classroom_id??undefined,childId:row.child_id});resources.push({branchId:a.branch_id,classroomId:row.classroom_id??undefined,childId:row.child_id});}return resources;}
   await this.core.enabled(tx);
   dues=await this.corrections.ledger.lockDue(tx,p,participants.map(x=>x.installment_id),'finance.correct');reductions=[];resources.splice(0);
   for(const due of dues){requireRecord(p,'activities.manage',{branchId:due.branch_id,classroomId:due.classroom_id??undefined,childId:due.child_id});requireSensitiveCorrection(p,{branchId:due.branch_id,classroomId:due.classroom_id??undefined});const state=(await tx.query<{effective:string}>('select (amount+adjustments)::text as effective from installment_balances where id=$1',[due.id])).rows[0];if(BigInt(state.effective)>0n)reductions.push({due,amount:state.effective});resources.push({branchId:due.branch_id,classroomId:due.classroom_id??undefined,childId:due.child_id});}
   return resources;
  };
  return this.core.children.withPolicy(token,(tx,p)=>this.core.operation(tx,p,input.operationId,'ACTIVITY_CANCEL',{id,...input},'activities.manage',()=>authorize(tx,p),async()=>{
   await tx.query("update activities set status='CANCELLED' where id=$1",[id]);await tx.query('insert into activity_cancellations(id,activity_id,actor_id,operation_id,reason) values($1,$2,$3,$4,$5)',[randomUUID(),id,p.account.id,input.operationId,input.reason]);
   const corrections=[];for(const {due,amount} of reductions)corrections.push(await this.corrections.reductionInTransaction(tx,p,due.id,{...input,effectiveOn:cairoIsoDate(),reductionAmount:amount},due,resources));return {id,status:'CANCELLED' as const,corrections};
  },async()=>{await authorize(tx,p,true);},false));
 }
}
