insert into capabilities(key,reserved) values ('transport.manage',false),('transport.read',false),('activities.manage',false),('activities.read',false);
alter table module_settings drop constraint module_settings_module_key_check;
alter table module_settings add constraint module_settings_module_key_check check(module_key in ('FINANCE','ATTENDANCE','EXAMS','HOMEWORK','HEALTH','PICKUP','INCIDENTS','CUSTOM_CHECKPOINTS','TRANSPORT','ACTIVITIES'));
insert into module_settings(module_key) values ('TRANSPORT'),('ACTIVITIES');

create table bus_subscriptions (
 id uuid primary key, child_id uuid not null references children(id), branch_id uuid not null references branches(id), classroom_id uuid references classrooms(id),
 child_code text not null, child_name text not null, period_start date not null, period_end date not null, amount bigint not null check(amount>=0),
 administrative_permission boolean not null, version integer not null default 1 check(version>0), category_id uuid not null references fee_categories(id), obligation_id uuid unique references obligations(id), installment_id uuid unique references installments(id),
 actor_id uuid not null references accounts(id), operation_id uuid not null, created_at timestamptz not null default now(), unique(actor_id,operation_id), unique(child_id,period_start,period_end), check(period_end>=period_start),
 foreign key(actor_id,operation_id) references financial_operations(actor_id,operation_id) deferrable initially deferred
);
create table bus_permission_events (id uuid primary key,subscription_id uuid not null references bus_subscriptions(id),actor_id uuid not null references accounts(id),operation_id uuid not null,enabled boolean not null,reason text not null,created_at timestamptz not null default now(),unique(actor_id,operation_id));
create table activities (id uuid primary key,branch_id uuid not null references branches(id),category_id uuid not null references fee_categories(id),title text not null check(length(title) between 1 and 160),details text not null check(length(details) between 1 and 500),event_date date not null,fee bigint not null check(fee>=0),status text not null default 'ACTIVE' check(status in ('ACTIVE','CANCELLED')),actor_id uuid not null references accounts(id),operation_id uuid not null,created_at timestamptz not null default now(),unique(actor_id,operation_id),foreign key(actor_id,operation_id) references financial_operations(actor_id,operation_id) deferrable initially deferred);
create table activity_children (id uuid primary key,activity_id uuid not null references activities(id),child_id uuid not null references children(id),child_code text not null,child_name text not null,classroom_id uuid references classrooms(id),obligation_id uuid unique references obligations(id),installment_id uuid unique references installments(id),unique(activity_id,child_id));
create table activity_consents (id uuid primary key,activity_child_id uuid not null references activity_children(id),actor_id uuid not null references accounts(id),operation_id uuid not null,consented boolean not null,reason text not null,created_at timestamptz not null default now(),unique(actor_id,operation_id));
create table activity_cancellations (id uuid primary key,activity_id uuid not null unique references activities(id),actor_id uuid not null references accounts(id),operation_id uuid not null,reason text not null,created_at timestamptz not null default now(),unique(actor_id,operation_id));
create view transport_notification_sources as select 'activity:'||a.id::text||':'||ac.child_id::text as event_key,ac.child_id,'TRIP'::text as kind,'ACTIVITIES'::text as module_key,a.event_date as business_date,array(select l.guardian_id from guardian_child_links l where l.child_id=ac.child_id and l.active and l.can_read and l.can_notify) as recipient_ids,null::uuid as announcement_id from activities a join activity_children ac on ac.activity_id=a.id where a.status='ACTIVE';
alter view parent_notification_sources rename to parent_notification_sources_before_transport;
create view parent_notification_sources as select * from parent_notification_sources_before_transport union all select * from transport_notification_sources;
create function preserve_activity() returns trigger language plpgsql as $$ begin
 if tg_op='DELETE' or new.id<>old.id or new.branch_id<>old.branch_id or new.category_id<>old.category_id or new.title<>old.title or new.details<>old.details or new.event_date<>old.event_date or new.fee<>old.fee or new.actor_id<>old.actor_id or new.operation_id<>old.operation_id or (new.status<>old.status and not(old.status='ACTIVE' and new.status='CANCELLED')) then raise exception 'Activity history is immutable'; end if; return new;
end $$;
create trigger activities_immutable before update or delete on activities for each row execute function preserve_activity();
do $$ declare t text; begin foreach t in array array['bus_permission_events','activity_children','activity_consents','activity_cancellations'] loop execute format('create trigger %I before update or delete on %I for each row execute function preserve_learning_history()',t||'_immutable',t); end loop; end $$;
