export const safetyEnglish = {
 'safety.title': 'Safety and health', 'safety.emergency': 'Emergency information', 'safety.emergencyHelp': 'Guardian contacts, critical alerts and emergency contacts for authorized staff. Retained even when the health module is disabled.',
 'safety.healthDisabled': 'The health module is disabled. Existing emergency information stays visible here; no new entries or changes can be recorded.',
 'safety.pickupDisabled': 'The authorized pickup module is disabled. History remains visible; no new people, restrictions or releases can be recorded.',
 'safety.incidentsDisabled': 'The incidents module is disabled. Existing reports remain visible; no new reports or follow-ups can be recorded.',
 'safety.guardians': 'Linked guardians', 'safety.whatsapp': 'Open WhatsApp chat', 'safety.whatsappHelp': 'Opens a chat in WhatsApp on your device when you choose it. The nursery app never sends messages automatically.', 'safety.noWhatsapp': 'Number cannot be used for WhatsApp',
 'safety.health': 'Health notes and alerts', 'safety.healthHelp': 'Notes, allergies/alerts and emergency contacts only. No medication schedules, doses or medical decisions are recorded.',
 'safety.kind': 'Type', 'safety.NOTE': 'Note', 'safety.ALLERGY': 'Allergy', 'safety.ALERT': 'Alert', 'safety.EMERGENCY_CONTACT': 'Emergency contact', 'safety.severity': 'Severity', 'safety.INFO': 'Information', 'safety.CRITICAL': 'Critical',
 'safety.entryTitle': 'Title or contact name', 'safety.entryBody': 'Details', 'safety.addEntry': 'Add health entry', 'safety.retireEntry': 'Remove entry', 'safety.retired': 'Removed',
 'safety.pickup': 'Authorized pickup', 'safety.authorized': 'Authorized people', 'safety.addPerson': 'Add authorized person', 'safety.validFrom': 'Valid from', 'safety.validUntil': 'Valid until', 'safety.oneDay': 'One day only', 'safety.openEnded': 'No end date',
 'safety.deactivate': 'Remove authorization', 'safety.pending': 'Awaiting nursery confirmation', 'safety.permitted': 'Permitted today',
 'safety.pickupGuardianHelp': 'People you add may collect your child only after staff confirm a call with a guardian who has pickup permission. Use one day only for a single collection.',
 'safety.blocker.INACTIVE': 'Removed', 'safety.blocker.REJECTED': 'Rejected by management', 'safety.blocker.NOT_YET_VALID': 'Not yet valid', 'safety.blocker.EXPIRED': 'Expired', 'safety.blocker.PROHIBITED_COLLECTOR': 'Matches a prohibited collector', 'safety.blocker.REVIEW_REQUIRED': 'Management review required',
 'safety.review': 'Management review', 'safety.approve': 'Approve', 'safety.reject': 'Reject', 'safety.reviewNote': 'Review note (optional)', 'safety.APPROVED': 'Approved', 'safety.REJECTED': 'Rejected',
 'safety.restrictions': 'Restrictions and prohibited collectors', 'safety.addRestriction': 'Add restriction', 'safety.PROHIBITED_COLLECTOR': 'Prohibited collector', 'safety.REVIEW_REQUIRED': 'Review required for every authorized person',
 'safety.summary': 'Summary shown to pickup staff', 'safety.privateNote': 'Private management note (optional)', 'safety.privateNoteHelp': 'Visible only to staff who manage pickup restrictions. Never shown to guardians or release-recording staff.', 'safety.endRestriction': 'End restriction', 'safety.ended': 'Ended',
 'safety.record': 'Record a release', 'safety.collector': 'Collector', 'safety.chooseCollector': 'Choose the collector', 'safety.calledGuardian': 'Guardian called', 'safety.chooseGuardian': 'Choose the guardian you called',
 'safety.callConfirmed': 'I called this guardian and they confirmed the release', 'safety.recordHelp': 'Only the business date and the procedure are recorded. The app cannot verify the caller physically and stores no arrival or departure times.',
 'safety.note': 'Note (optional)', 'safety.records': 'Release history', 'safety.recorded': 'Release recorded.', 'safety.collectedBy': 'Collected by {name} ({relationship}); confirmed with {guardian}',
 'safety.incidents': 'Incidents', 'safety.report': 'Report an incident', 'safety.occurredOn': 'Date', 'safety.occurredTime': 'Time', 'safety.description': 'What happened', 'safety.actionTaken': 'Action taken',
 'safety.guardianInformed': 'A guardian was informed', 'safety.contactMethod': 'Contact method', 'safety.CALL': 'Phone call', 'safety.WHATSAPP': 'WhatsApp', 'safety.IN_PERSON': 'In person', 'safety.IN_APP': 'In-app notification',
 'safety.followUp': 'Follow-up (optional)', 'safety.status': 'Status', 'safety.OPEN': 'Open', 'safety.CLOSED': 'Closed', 'safety.updateIncident': 'Save follow-up', 'safety.notInformed': 'Guardian not yet informed',
 'safety.incidentHelp': 'Parents see committed reports in the app. Calls or WhatsApp handle real-world follow-up; no injury photos are stored.',
 'safety.saved': 'Saved.', 'safety.none': 'None recorded.', 'safety.invalid': 'Check the required fields and values.', 'safety.moduleDisabled': 'This module is disabled by the nursery.',
 'safety.childNotActive': 'Releases can be recorded only for active children.', 'safety.collectorNotPermitted': 'This collector is not permitted today. Check validity, removal, or review status.',
 'safety.prohibitedCollector': 'This person matches a prohibited collector. Do not release the child; contact management.', 'safety.unresolvedRestriction': 'A management restriction is unresolved for this person. Ask management to review it before any release.',
 'safety.callNotConfirmed': 'Confirm the call to a guardian before recording the release.', 'safety.calledGuardianNotPermitted': 'The guardian called must have pickup permission for this child.',
 'organization.cap.health.read': 'View health and emergency information', 'organization.cap.health.manage': 'Manage health notes, alerts and emergency contacts', 'organization.cap.pickup.record': 'Record child releases', 'organization.cap.pickup.manage': 'Manage pickup restrictions and reviews',
 'organization.cap.incidents.read': 'View incident reports', 'organization.cap.incidents.manage': 'Report and follow up incidents'
} as const;
export const safetyArabic: Record<keyof typeof safetyEnglish,string> = {
 'safety.title': 'السلامة والصحة', 'safety.emergency': 'معلومات الطوارئ', 'safety.emergencyHelp': 'أرقام أولياء الأمور والتنبيهات الحرجة وجهات اتصال الطوارئ للموظفين المصرّح لهم. بتفضل موجودة حتى لو وحدة الصحة معطّلة.',
 'safety.healthDisabled': 'وحدة الصحة معطّلة. معلومات الطوارئ الموجودة بتفضل ظاهرة هنا، ومش ممكن إضافة أو تعديل بيانات جديدة.',
 'safety.pickupDisabled': 'وحدة الاستلام المصرّح به معطّلة. السجل بيفضل ظاهر، ومش ممكن تسجيل أشخاص أو قيود أو استلامات جديدة.',
 'safety.incidentsDisabled': 'وحدة الحوادث معطّلة. البلاغات الموجودة بتفضل ظاهرة، ومش ممكن تسجيل بلاغات أو متابعات جديدة.',
 'safety.guardians': 'أولياء الأمور المرتبطين', 'safety.whatsapp': 'فتح محادثة واتساب', 'safety.whatsappHelp': 'بيفتح محادثة في واتساب على جهازك لما تختار ده. التطبيق مش بيبعت أي رسائل لوحده.', 'safety.noWhatsapp': 'الرقم مش صالح لواتساب',
 'safety.health': 'الملاحظات الصحية والتنبيهات', 'safety.healthHelp': 'ملاحظات وحساسية/تنبيهات وجهات اتصال طوارئ فقط. مفيش تسجيل لجداول أدوية أو جرعات أو قرارات طبية.',
 'safety.kind': 'النوع', 'safety.NOTE': 'ملاحظة', 'safety.ALLERGY': 'حساسية', 'safety.ALERT': 'تنبيه', 'safety.EMERGENCY_CONTACT': 'جهة اتصال طوارئ', 'safety.severity': 'درجة الأهمية', 'safety.INFO': 'للعلم', 'safety.CRITICAL': 'حرج',
 'safety.entryTitle': 'العنوان أو اسم جهة الاتصال', 'safety.entryBody': 'التفاصيل', 'safety.addEntry': 'إضافة بيان صحي', 'safety.retireEntry': 'إزالة البيان', 'safety.retired': 'تمت إزالته',
 'safety.pickup': 'الاستلام المصرّح به', 'safety.authorized': 'الأشخاص المصرّح لهم', 'safety.addPerson': 'إضافة شخص مصرّح له', 'safety.validFrom': 'ساري من', 'safety.validUntil': 'ساري حتى', 'safety.oneDay': 'يوم واحد فقط', 'safety.openEnded': 'بدون تاريخ انتهاء',
 'safety.deactivate': 'إلغاء التصريح', 'safety.pending': 'في انتظار تأكيد الحضانة', 'safety.permitted': 'مسموح له النهارده',
 'safety.pickupGuardianHelp': 'الأشخاص اللي تضيفهم يقدروا يستلموا طفلك بعد ما الموظفين يأكدوا بمكالمة مع ولي أمر عنده صلاحية الاستلام. استخدم "يوم واحد فقط" لاستلام مرة واحدة.',
 'safety.blocker.INACTIVE': 'تم إلغاؤه', 'safety.blocker.REJECTED': 'مرفوض من الإدارة', 'safety.blocker.NOT_YET_VALID': 'لسه مش ساري', 'safety.blocker.EXPIRED': 'منتهي', 'safety.blocker.PROHIBITED_COLLECTOR': 'مطابق لشخص ممنوع من الاستلام', 'safety.blocker.REVIEW_REQUIRED': 'محتاج مراجعة الإدارة',
 'safety.review': 'مراجعة الإدارة', 'safety.approve': 'اعتماد', 'safety.reject': 'رفض', 'safety.reviewNote': 'ملاحظة المراجعة (اختياري)', 'safety.APPROVED': 'معتمد', 'safety.REJECTED': 'مرفوض',
 'safety.restrictions': 'القيود والأشخاص الممنوعين من الاستلام', 'safety.addRestriction': 'إضافة قيد', 'safety.PROHIBITED_COLLECTOR': 'شخص ممنوع من الاستلام', 'safety.REVIEW_REQUIRED': 'مراجعة مطلوبة لكل شخص مصرّح له',
 'safety.summary': 'ملخص يظهر لموظفي الاستلام', 'safety.privateNote': 'ملاحظة إدارية خاصة (اختياري)', 'safety.privateNoteHelp': 'بتظهر فقط للموظفين اللي بيديروا قيود الاستلام. مش بتظهر أبدًا لأولياء الأمور أو لموظفي تسجيل الاستلام.', 'safety.endRestriction': 'إنهاء القيد', 'safety.ended': 'انتهى',
 'safety.record': 'تسجيل استلام', 'safety.collector': 'المستلم', 'safety.chooseCollector': 'اختار المستلم', 'safety.calledGuardian': 'ولي الأمر اللي اتصلت به', 'safety.chooseGuardian': 'اختار ولي الأمر اللي اتصلت به',
 'safety.callConfirmed': 'اتصلت بولي الأمر ده وأكد الاستلام', 'safety.recordHelp': 'بيتم تسجيل تاريخ اليوم والإجراء فقط. التطبيق مش بيقدر يتحقق من هوية المتصل فعليًا ومش بيسجل أوقات وصول أو مغادرة.',
 'safety.note': 'ملاحظة (اختياري)', 'safety.records': 'سجل الاستلام', 'safety.recorded': 'تم تسجيل الاستلام.', 'safety.collectedBy': 'استلمه {name} ({relationship})؛ تم التأكيد مع {guardian}',
 'safety.incidents': 'الحوادث', 'safety.report': 'الإبلاغ عن حادث', 'safety.occurredOn': 'التاريخ', 'safety.occurredTime': 'الوقت', 'safety.description': 'اللي حصل', 'safety.actionTaken': 'الإجراء المتخذ',
 'safety.guardianInformed': 'تم إبلاغ ولي الأمر', 'safety.contactMethod': 'طريقة التواصل', 'safety.CALL': 'مكالمة هاتفية', 'safety.WHATSAPP': 'واتساب', 'safety.IN_PERSON': 'شخصيًا', 'safety.IN_APP': 'إشعار داخل التطبيق',
 'safety.followUp': 'المتابعة (اختياري)', 'safety.status': 'الحالة', 'safety.OPEN': 'مفتوح', 'safety.CLOSED': 'مغلق', 'safety.updateIncident': 'حفظ المتابعة', 'safety.notInformed': 'ولي الأمر لم يُبلَّغ بعد',
 'safety.incidentHelp': 'أولياء الأمور بيشوفوا البلاغات المحفوظة في التطبيق. المكالمات أو واتساب بتتولى المتابعة الفعلية؛ مفيش تخزين لصور الإصابات.',
 'safety.saved': 'تم الحفظ.', 'safety.none': 'مفيش بيانات مسجلة.', 'safety.invalid': 'راجع البيانات المطلوبة والقيم.', 'safety.moduleDisabled': 'الوحدة دي معطّلة من الحضانة.',
 'safety.childNotActive': 'تسجيل الاستلام متاح للأطفال النشطين فقط.', 'safety.collectorNotPermitted': 'المستلم ده مش مسموح له النهارده. راجع الصلاحية أو الإلغاء أو حالة المراجعة.',
 'safety.prohibitedCollector': 'الشخص ده مطابق لشخص ممنوع من الاستلام. متسلّمش الطفل وتواصل مع الإدارة.', 'safety.unresolvedRestriction': 'فيه قيد إداري لسه مش محلول للشخص ده. اطلب من الإدارة تراجعه قبل أي استلام.',
 'safety.callNotConfirmed': 'أكد المكالمة مع ولي الأمر قبل تسجيل الاستلام.', 'safety.calledGuardianNotPermitted': 'ولي الأمر اللي اتصلت به لازم يكون عنده صلاحية الاستلام للطفل ده.',
 'organization.cap.health.read': 'عرض المعلومات الصحية ومعلومات الطوارئ', 'organization.cap.health.manage': 'إدارة الملاحظات الصحية والتنبيهات وجهات اتصال الطوارئ', 'organization.cap.pickup.record': 'تسجيل استلام الأطفال', 'organization.cap.pickup.manage': 'إدارة قيود الاستلام والمراجعات',
 'organization.cap.incidents.read': 'عرض بلاغات الحوادث', 'organization.cap.incidents.manage': 'الإبلاغ عن الحوادث ومتابعتها'
};
