import 'dotenv/config';
import pino from 'pino';
import { createDatabase } from '@nursery/db';
import { startBillingWorker } from './billing.js';
import { installReportWorker } from './reports.js';
const logger=pino({redact:['databaseUrl','token']});
const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl) throw new Error('DATABASE_URL is required');
const privateFilesDir=process.env.PRIVATE_FILES_DIR;
if(!privateFilesDir) throw new Error('PRIVATE_FILES_DIR is required for private report exports');
const database=createDatabase(databaseUrl);
const boss=await startBillingWorker(databaseUrl,database,()=>logger.error('Billing job failed; inspect queue status'));
await installReportWorker(boss,database,privateFilesDir);
logger.info('Billing and report worker started');
let stopping=false;
const stop=async()=>{if(stopping) return;stopping=true;await boss.stop({graceful:true});await database.close();logger.info('Background worker stopped');};
process.once('SIGINT',()=>{void stop();});process.once('SIGTERM',()=>{void stop();});
