import 'dotenv/config';
import pino from 'pino';
import { createDatabase } from '@nursery/db';
import { startBillingWorker } from './billing.js';
const logger=pino({redact:['databaseUrl','token']});
const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl) throw new Error('DATABASE_URL is required');
const database=createDatabase(databaseUrl);
const boss=await startBillingWorker(databaseUrl,database,()=>logger.error('Billing job failed; inspect queue status'));
logger.info('Billing worker started');
let stopping=false;
const stop=async()=>{if(stopping) return;stopping=true;await boss.stop({graceful:true});await database.close();logger.info('Billing worker stopped');};
process.once('SIGINT',()=>{void stop();});process.once('SIGTERM',()=>{void stop();});
