export const learningEnglish = {
  "organization.cap.learning.configure": "Configure daily checkpoints",
  "organization.cap.learning.read": "View daily learning",
  "organization.cap.learning.publish": "Publish and correct daily learning",
  "learning.title": "Daily learning",
  "learning.configuration": "Checkpoint configuration",
  "learning.nextDay": "Changes start on the next Cairo date. Existing reports keep their definitions and labels.",
  "learning.effective": "Effective from",
  "learning.add": "Add custom checkpoint",
  "learning.addStatus": "Add status",
  "learning.save": "Save configuration",
  "learning.saved": "Saved successfully",
  "learning.nameEn": "English label",
  "learning.nameAr": "Arabic label",
  "learning.order": "Display order",
  "learning.enabled": "Enabled",
  "learning.from": "Enabled from",
  "learning.until": "Enabled until",
  "learning.statuses": "Statuses",
  "learning.status": "Status",
  "learning.meaning": "Reporting meaning",
  "learning.theme": "Status color",
  "learning.icon": "Icon",
  "learning.PENDING": "Pending",
  "learning.RESOLVED": "Recorded",
  "learning.NOT_APPLICABLE": "Not applicable",
  "learning.neutral": "Neutral",
  "learning.success": "Success",
  "learning.warning": "Warning",
  "learning.error": "Error",
  "learning.calendar": "Calendar",
  "learning.learning": "Learning",
  "learning.check": "Check",
  "learning.star": "Star",
  "learning.child": "Child",
  "learning.date": "Report date",
  "learning.note": "Optional note",
  "learning.reason": "Correction reason",
  "learning.publish": "Publish",
  "learning.correct": "Publish correction",
  "learning.transition": "Record status change",
  "learning.action": "Action",
  "learning.pending": "Not published",
  "learning.progress": "{completed} of {total} updates complete",
  "learning.off": "Daily updates are off or unavailable for this date.",
  "learning.disabled": "This learning module is disabled.",
  "learning.invalid": "Check dates, statuses and required mappings. Retire existing statuses instead of deleting or changing their meaning.",
  "learning.operationConflict": "This operation ID was already used for a different change. Refresh before trying again.",
  "learning.empty": "No assigned children are available.",
  "learning.history": "Publication history",
  "learning.retireHelp": "Turn off a definition or status to retire it. Existing identities and reporting meanings are preserved.",
  "learning.more": "Next children",
  "learning.previous": "Previous children",
  "learning.batch": "Publish classroom updates",
  "learning.classroom": "Classroom",
  "learning.prepare": "Review children",
  "learning.exceptionHelp": "Review every child. Change individual statuses or notes before publishing. Already published updates are excluded.",
  "learning.include": "Include",
  "learning.uncertain": "If the response was lost, retry the unchanged form to retrieve the original publication."
} as const;
export const learningArabic: Record<keyof typeof learningEnglish,string> = {
  "organization.cap.learning.configure": "إعداد المتابعات اليومية",
  "organization.cap.learning.read": "عرض المتابعة اليومية",
  "organization.cap.learning.publish": "نشر وتصحيح المتابعة اليومية",
  "learning.title": "المتابعة اليومية",
  "learning.configuration": "إعداد المتابعات",
  "learning.nextDay": "التغييرات بتبدأ من بكرة بتوقيت القاهرة. التقارير الموجودة بتحتفظ بالإعدادات والمسميات القديمة.",
  "learning.effective": "ساري من",
  "learning.add": "إضافة متابعة جديدة",
  "learning.addStatus": "إضافة حالة",
  "learning.save": "حفظ الإعدادات",
  "learning.saved": "اتحفظ بنجاح",
  "learning.nameEn": "الاسم بالإنجليزي",
  "learning.nameAr": "الاسم بالعربي",
  "learning.order": "ترتيب العرض",
  "learning.enabled": "مفعّل",
  "learning.from": "مفعّل من",
  "learning.until": "مفعّل لحد",
  "learning.statuses": "الحالات",
  "learning.status": "الحالة",
  "learning.meaning": "معنى الحالة في التقرير",
  "learning.theme": "لون الحالة",
  "learning.icon": "الأيقونة",
  "learning.PENDING": "لسه مستني",
  "learning.RESOLVED": "اتسجل",
  "learning.NOT_APPLICABLE": "مش مطلوب",
  "learning.neutral": "محايد",
  "learning.success": "نجاح",
  "learning.warning": "تنبيه",
  "learning.error": "خطأ",
  "learning.calendar": "تقويم",
  "learning.learning": "تعليم",
  "learning.check": "علامة صح",
  "learning.star": "نجمة",
  "learning.child": "الطفل",
  "learning.date": "تاريخ التقرير",
  "learning.note": "ملاحظة اختيارية",
  "learning.reason": "سبب التصحيح",
  "learning.publish": "نشر",
  "learning.correct": "نشر التصحيح",
  "learning.transition": "تسجيل تغيير الحالة",
  "learning.action": "الإجراء",
  "learning.pending": "لسه متنشرش",
  "learning.progress": "اكتمل {completed} من {total} تحديثات",
  "learning.off": "المتابعة اليومية مقفولة أو مش متاحة للتاريخ ده.",
  "learning.disabled": "قسم المتابعة ده مقفول.",
  "learning.invalid": "راجع التواريخ والحالات والربط المطلوب. اقفل الحالة القديمة بدل ما تمسحها أو تغيّر معناها.",
  "learning.operationConflict": "رقم العملية ده اتستخدم لتغيير مختلف. حدّث الصفحة قبل المحاولة تاني.",
  "learning.empty": "مفيش أطفال متاحين في الفصول المسندة ليك.",
  "learning.history": "سجل النشر",
  "learning.retireHelp": "اقفل المتابعة أو الحالة لإيقاف استخدامها. هوية الحالة ومعناها في التقارير بيفضلوا محفوظين.",
  "learning.more": "الأطفال التاليين",
  "learning.previous": "الأطفال السابقين",
  "learning.batch": "نشر تحديثات الفصل",
  "learning.classroom": "الفصل",
  "learning.prepare": "مراجعة الأطفال",
  "learning.exceptionHelp": "راجع كل طفل وغيّر حالته أو ملاحظته قبل النشر. التحديثات المنشورة بالفعل مش مشمولة.",
  "learning.include": "يشمل",
  "learning.uncertain": "لو الرد موصلش، جرّب نفس النموذج من غير تغيير لاسترجاع النشر الأصلي."
};
