// @vitest-environment jsdom
import React from 'react';
import { afterEach,describe,it,expect } from 'vitest';
import { render,screen,within,cleanup,fireEvent,waitFor } from '@testing-library/react';
import { userEvent } from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { cairoIsoDate } from '@nursery/domain';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';
import { httpClient } from '../helpers/http-client.js';
import { App } from '../../apps/web/src/App.js';
import { LocaleProvider } from '../../apps/web/src/i18n/LocaleProvider.js';
import { translate } from '../../apps/web/src/i18n/catalogs.js';
import axe from 'axe-core';

describe('Phase 19 scripted bilingual payroll over real HTTP/PostgreSQL',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;
 afterEach(async()=>{cleanup();await f?.close();});
 it.each(['en','ar-EG'] as const)('A26/A28: profile, advance, deduction and lost-response final payout recover once in %s',async locale=>{
  window.localStorage.clear();f=await financeFixture(false);const account=await f.treasuryAccount('PAYROLL-CASH',f.a.id,'CASH','2000000');await f.app.auth.setLocale(f.root.token,locale);
  let drop=true;f.app.addHook('onSend',async(request,reply,payload)=>{if(drop&&request.method==='POST'&&request.url.endsWith('/settlements')){drop=false;reply.raw.destroy();}return payload;});
  const origin=await f.app.listen({host:'127.0.0.1',port:0}),client=httpClient(origin,f.config.appOrigin);await client.login(f.root.account.username,f.password);const t=(key:Parameters<typeof translate>[1])=>translate(locale,key),user=userEvent.setup();
  const view=render(<MemoryRouter initialEntries={['/administration/payroll']}><LocaleProvider userLocale={locale}><App authClient={client}/></LocaleProvider></MemoryRouter>);
  const create=await screen.findByRole('group',{name:t('payroll.create')},{timeout:15000});
  const input=(group:HTMLElement,key:Parameters<typeof translate>[1],value:string)=>fireEvent.change(within(group).getByLabelText(t(key),{exact:false}),{target:{value}});
  input(create,'payroll.code','UIPAY');input(create,'payroll.name','Synthetic payroll employee');input(create,'payroll.salary','5000.00');await user.selectOptions(within(create).getByLabelText(t('payroll.branch'),{exact:false}),f.a.id);await user.selectOptions(within(create).getByLabelText(t('payroll.account'),{exact:false}),account.id);await user.dblClick(within(create).getByRole('button',{name:t('payroll.create')}));
  await screen.findByRole('heading',{name:'UIPAY — Synthetic payroll employee'},{timeout:15000});expect((await f.database.pool.query("select count(*)::int n from seat_reservations where kind='EMPLOYEE'")).rows[0].n).toBe(0);
  await user.click(screen.getByRole('button',{name:t('payroll.prepare')}));await screen.findByRole('button',{name:t('payroll.openMonth')},{timeout:15000});await user.click(screen.getByRole('button',{name:t('payroll.openMonth')}));
  const advance=await screen.findByRole('group',{name:t('payroll.advance')},{timeout:15000});input(advance,'spending.amount','1000.00');input(advance,'spending.reason','Paid salary advance');await user.click(within(advance).getByRole('checkbox',{name:t('payroll.confirmAdvance')}));await user.dblClick(within(advance).getByRole('button',{name:t('payroll.advance')}));await screen.findByText(/Paid salary advance/,{},{timeout:15000});
  const adjust=await screen.findByRole('group',{name:t('payroll.adjust')},{timeout:15000});await user.selectOptions(within(adjust).getByRole('combobox'),'DEDUCTION');input(adjust,'spending.amount','300.00');input(adjust,'spending.reason','Reasoned salary deduction');await user.click(within(adjust).getByRole('button',{name:t('payroll.adjust')}));await screen.findByText(/Reasoned salary deduction/,{},{timeout:15000});
  const settle=await screen.findByRole('group',{name:t('payroll.settle')},{timeout:15000});input(settle,'spending.reason','Full 3700 salary remainder');await user.click(within(settle).getByRole('checkbox',{name:t('payroll.confirm')}));await user.dblClick(within(settle).getByRole('button',{name:t('payroll.settle')}));await screen.findByText(t('finance.uncertain'),{},{timeout:15000});expect((settle as HTMLFieldSetElement).disabled).toBe(true);await user.click(screen.getByRole('button',{name:t('finance.check')}));await screen.findByText(t('spending.saved'),{},{timeout:15000});
  await waitFor(()=>expect(screen.queryByRole('group',{name:t('payroll.settle')})).toBeNull());await user.click(await screen.findByRole('button',{name:t('payroll.receipt')},{timeout:15000}));const receipt=await screen.findByRole('heading',{name:t('payroll.receipt')},{timeout:15000});await waitFor(()=>expect(within(receipt.closest('section')!).getByText(new RegExp(t('payroll.cashTotal')))).toBeTruthy());
  const period=(await f.app.payroll.roster(f.root.token,{month:cairoIsoDate().slice(0,7)})).items[0];expect(await f.app.payroll.receiptData(f.root.token,period.periodId!)).toMatchObject({finalPaid:'370000',totalCashOutflow:'470000'});expect((await f.database.pool.query("select count(*)::int n,(-sum(amount))::text outflow from treasury_movements where kind in ('PAYROLL_ADVANCE','PAYROLL_SETTLEMENT')")).rows[0]).toEqual({n:2,outflow:'470000'});expect(await reconcileFinance(f.database)).toEqual([]);expect(document.documentElement.dir).toBe(locale==='en'?'ltr':'rtl');expect((await axe.run(view.container,{rules:{'color-contrast':{enabled:false}}})).violations).toEqual([]);
 },60000);
 it('A05: later login provisioning displays only a one-time credential and financial deactivation keeps the slot',async()=>{
  window.localStorage.clear();f=await financeFixture(false);await f.app.auth.setLocale(f.root.token,'en');const employee=await f.app.payroll.createProfile(f.root.token,{operationId:crypto.randomUUID(),employeeCode:'OPTIONAL',fullName:'Optional login employee',basicSalary:'500000',effectiveMonth:cairoIsoDate().slice(0,7),payingBranchId:f.a.id,payingAccountId:f.cashA.id,loginUsername:null});const origin=await f.app.listen({host:'127.0.0.1',port:0}),client=httpClient(origin,f.config.appOrigin);await client.login(f.root.account.username,f.password);const user=userEvent.setup(),t=(key:Parameters<typeof translate>[1])=>translate('en',key);
  const view=render(<MemoryRouter initialEntries={['/administration/payroll']}><LocaleProvider userLocale="en"><App authClient={client}/></LocaleProvider></MemoryRouter>);await user.click(await screen.findByRole('button',{name:t('payroll.details')},{timeout:15000}));const login=await screen.findByRole('group',{name:t('payroll.provisionLogin')},{timeout:15000});fireEvent.change(within(login).getByLabelText(t('payroll.username'),{exact:false}),{target:{value:'optional-login-employee'}});fireEvent.change(within(login).getByLabelText(t('spending.reason'),{exact:false}),{target:{value:'Create optional app access'}});await user.dblClick(within(login).getByRole('button',{name:t('payroll.provisionLogin')}));await screen.findByText(t('payroll.secretHelp'),{},{timeout:15000});const credential=view.container.querySelector('code.auth-temporary')!.textContent!;expect(credential.length).toBeGreaterThan(20);expect(JSON.stringify(window.localStorage)).not.toContain(credential);await user.click(screen.getByRole('button',{name:t('auth.dismissSecret')}));expect(view.container.querySelector('code.auth-temporary')).toBeNull();
  const deactivate=await screen.findByRole('group',{name:t('payroll.deactivate')},{timeout:15000});fireEvent.change(within(deactivate).getByLabelText(t('spending.reason'),{exact:false}),{target:{value:'Financial-only deactivation'}});await user.click(within(deactivate).getByRole('button',{name:t('payroll.deactivate')}));await screen.findByRole('group',{name:t('payroll.reactivate')},{timeout:15000});const history=await f.app.payroll.employee(f.root.token,employee.id);expect(history.employee.active).toBe(false);expect((await f.database.pool.query('select status from accounts where id=$1',[history.employee.accountId])).rows[0].status).toBe('ACTIVE');expect((await f.licensing.context(f.root.token)).employeeReserved).toBe(1);expect(await reconcileFinance(f.database)).toEqual([]);
 },60000);
 it('A01: read-only payroll retains old months, shows no mutation controls and drops revoked details',async()=>{
  window.localStorage.clear();f=await financeFixture(false);const account=await f.treasuryAccount('HISTORY-CASH',f.a.id,'CASH','1000000'),month=cairoIsoDate().slice(0,7),[year,m]=month.split('-').map(Number),old=new Date(Date.UTC(year,m-2,1)).toISOString().slice(0,7);
  const employee=await f.app.payroll.createProfile(f.root.token,{operationId:crypto.randomUUID(),employeeCode:'OLD',fullName:'Retained unpaid employee',basicSalary:'500000',effectiveMonth:old,payingBranchId:f.a.id,payingAccountId:account.id,loginUsername:null});const period=await f.app.payroll.prepare(f.root.token,{operationId:crypto.randomUUID(),employeeId:employee.id,month:old}),staff=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read']);await f.app.auth.setLocale(staff.token,'en');const origin=await f.app.listen({host:'127.0.0.1',port:0}),client=httpClient(origin,f.config.appOrigin);await client.login(staff.username,staff.password);
  render(<MemoryRouter initialEntries={['/administration/payroll']}><LocaleProvider userLocale="en"><App authClient={client}/></LocaleProvider></MemoryRouter>);const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:translate('en','payroll.details')},{timeout:15000}));await screen.findByRole('heading',{name:translate('en','payroll.periodHistory')},{timeout:15000});await user.click(screen.getByRole('button',{name:`${translate('en','payroll.openMonth')} — ${old}`}));await screen.findByRole('heading',{name:translate('en','payroll.openMonth')},{timeout:15000});expect(screen.queryByRole('group',{name:translate('en','payroll.create')})).toBeNull();expect(screen.queryByRole('group',{name:translate('en','payroll.settle')})).toBeNull();
  const role=await f.app.organization.save(f.root.token,'roles',{name:'Payroll moved away',capabilities:['finance.read']});await f.app.organization.assign(f.root.token,staff.id,{expectedVersion:2,roleIds:[role.id],branchIds:[f.b.id],classroomIds:[],scopeMode:'BRANCH'});fireEvent(window,new Event('nursery:scope-refresh'));await waitFor(()=>expect(screen.queryByText('Retained unpaid employee',{exact:false})).toBeNull(),{timeout:15000});await expect(client.business(`payroll/periods/${period.id}/receipt-data`)).rejects.toMatchObject({detail:{code:'FORBIDDEN'}});
 },60000);
});
