export const importsEn={
 'imports.title':'Excel imports','imports.help':'Download the current template, fill it with plain values, upload it for a validation preview, then commit the reviewed batch. Every row is checked again at commit; a batch either commits completely or not at all.','imports.kind':'Import type','imports.template':'Download template','imports.templateVersion':'Template version','imports.file':'Completed template (.xlsx)','imports.upload':'Upload and preview','imports.uploading':'Checking the file…','imports.invalidFile':'Choose a .xlsx file up to the size limit.','imports.limits':'Up to {rows} data rows per sheet and {kb} KB per file. Larger data must be split into separate reviewed batches. Formulas and passwords are never accepted.',
 'imports.preview':'Validation preview','imports.rowCounts':'Rows per sheet','imports.creates':'Will create','imports.guardians':'Parent accounts','imports.children':'Children','imports.links':'Guardian links','imports.obligations':'Opening debts','imports.obligationsTotal':'Total opening debt (EGP)','imports.employees':'Employee profiles','imports.logins':'New logins (reserved slots)','imports.assignments':'Role assignments','imports.seats':'Account slots','imports.seatParent':'Parent slots','imports.seatEmployee':'Employee slots','imports.seatDetail':'{required} needed, {reserved} reserved of {capacity}','imports.unlimited':'not configured','imports.warnings':'Warnings','imports.CAPACITY_EXCEEDED':'Classroom capacity will be exceeded (advisory): {code}',
 'imports.errors':'Row errors','imports.noErrors':'No errors. The batch can be committed.','imports.sheet':'Sheet','imports.row':'Row','imports.column':'Column','imports.problem':'Problem','imports.rows':'Reviewed rows','imports.key':'Key','imports.label':'Value','imports.detail':'Details','imports.errorCount':'{count} error(s) — fix the file and upload it again.',
 'imports.commit':'Commit batch','imports.committing':'Committing…','imports.committed':'Batch committed.','imports.stale':'Data, scope, quotas or the template changed since the preview. The preview was refreshed — review it again before committing.','imports.expired':'This preview expired. Upload the file again.','imports.alreadyCommitted':'This batch was already committed.','imports.revalidationFailed':'The batch no longer passes validation. Review the refreshed errors.','imports.previewStale':'The preview is out of date; it was refreshed.','imports.tooLarge':'The file is too large or contains too much data. Split it into smaller batches.','imports.unsupportedFile':'Unsupported file. Use the downloaded .xlsx template without macros or external links.','imports.conflict':'A conflicting record already exists. Refresh the preview.','imports.invalid':'Invalid import request.',
 'imports.result':'Commit result','imports.credentials':'One-time temporary passwords','imports.credentialsHelp':'Deliver each password to its person outside the app. They are shown once only and expire after 24 hours; a lost password needs a Superadmin reset.','imports.username':'Username','imports.temporaryPassword':'Temporary password','imports.dismissCredentials':'I have delivered these passwords','imports.uncertain':'The commit result is unknown. Check the batch status before retrying.','imports.checkStatus':'Check batch status','imports.retry':'Retry the same commit','imports.notFound':'The commit was not recorded. You may retry it.',
 'imports.recent':'Recent batches','imports.open':'Open','imports.status':'Status','imports.PREVIEWED':'Previewed','imports.COMMITTED':'Committed','imports.EXPIRED':'Expired','imports.created':'Uploaded','imports.expires':'Preview valid until','imports.disabledKind':'Not available with your current permissions or module settings.','imports.new':'Start another batch','organization.cap.imports.commit':'Upload, preview and commit Excel import batches'
} as const;
export const importsAr:Record<keyof typeof importsEn,string>={
 'imports.title':'استيراد من إكسل','imports.help':'نزّل القالب الحالي، املاه بقيم عادية، ارفعه عشان تشوف معاينة التحقق، وبعدين نفّذ الدفعة بعد المراجعة. كل صف بيتراجع تاني وقت التنفيذ؛ الدفعة يا تتنفذ كلها يا متتنفذش خالص.','imports.kind':'نوع الاستيراد','imports.template':'تنزيل القالب','imports.templateVersion':'إصدار القالب','imports.file':'القالب بعد التعبئة (.xlsx)','imports.upload':'رفع ومعاينة','imports.uploading':'بنراجع الملف…','imports.invalidFile':'اختار ملف .xlsx في حدود الحجم المسموح.','imports.limits':'لحد {rows} صف بيانات في كل ورقة و{kb} كيلوبايت للملف. البيانات الأكبر لازم تتقسم لدفعات منفصلة تتراجع. المعادلات وكلمات السر مرفوضة دايمًا.',
 'imports.preview':'معاينة التحقق','imports.rowCounts':'عدد الصفوف في كل ورقة','imports.creates':'هيتم إنشاء','imports.guardians':'حسابات أولياء الأمور','imports.children':'الأطفال','imports.links':'روابط أولياء الأمور','imports.obligations':'مديونيات افتتاحية','imports.obligationsTotal':'إجمالي المديونية الافتتاحية (جنيه)','imports.employees':'ملفات الموظفين','imports.logins':'حسابات دخول جديدة (أماكن محجوزة)','imports.assignments':'تعيينات الأدوار','imports.seats':'أماكن الحسابات','imports.seatParent':'أماكن أولياء الأمور','imports.seatEmployee':'أماكن الموظفين','imports.seatDetail':'محتاج {required}، محجوز {reserved} من {capacity}','imports.unlimited':'غير مضبوط','imports.warnings':'تنبيهات','imports.CAPACITY_EXCEEDED':'سعة الفصل هتتعدى (تنبيه استرشادي): {code}',
 'imports.errors':'أخطاء الصفوف','imports.noErrors':'مفيش أخطاء. الدفعة جاهزة للتنفيذ.','imports.sheet':'الورقة','imports.row':'الصف','imports.column':'العمود','imports.problem':'المشكلة','imports.rows':'الصفوف اللي اتراجعت','imports.key':'المفتاح','imports.label':'القيمة','imports.detail':'التفاصيل','imports.errorCount':'{count} خطأ — صلّح الملف وارفعه تاني.',
 'imports.commit':'تنفيذ الدفعة','imports.committing':'جاري التنفيذ…','imports.committed':'تم تنفيذ الدفعة.','imports.stale':'البيانات أو الصلاحيات أو الأماكن أو القالب اتغيرت من وقت المعاينة. المعاينة اتحدثت — راجعها تاني قبل التنفيذ.','imports.expired':'المعاينة دي انتهت. ارفع الملف تاني.','imports.alreadyCommitted':'الدفعة دي اتنفذت قبل كده.','imports.revalidationFailed':'الدفعة مبقتش تعدي التحقق. راجع الأخطاء المحدثة.','imports.previewStale':'المعاينة قديمة؛ اتحدثت.','imports.tooLarge':'الملف كبير أوي أو فيه بيانات كتير. قسّمه لدفعات أصغر.','imports.unsupportedFile':'ملف غير مدعوم. استخدم قالب .xlsx اللي نزّلته من غير ماكرو أو روابط خارجية.','imports.conflict':'في سجل متعارض موجود بالفعل. حدّث المعاينة.','imports.invalid':'طلب استيراد غير صالح.',
 'imports.result':'نتيجة التنفيذ','imports.credentials':'كلمات سر مؤقتة لمرة واحدة','imports.credentialsHelp':'سلّم كل كلمة سر لصاحبها خارج التطبيق. بتظهر مرة واحدة بس وبتنتهي بعد 24 ساعة؛ لو ضاعت محتاجة إعادة تعيين من مسؤول النظام.','imports.username':'اسم المستخدم','imports.temporaryPassword':'كلمة السر المؤقتة','imports.dismissCredentials':'سلّمت كلمات السر دي','imports.uncertain':'نتيجة التنفيذ مش معروفة. اتأكد من حالة الدفعة قبل ما تعيد المحاولة.','imports.checkStatus':'اتأكد من حالة الدفعة','imports.retry':'أعد نفس التنفيذ','imports.notFound':'التنفيذ ماتسجلش. تقدر تعيد المحاولة.',
 'imports.recent':'الدفعات الأخيرة','imports.open':'فتح','imports.status':'الحالة','imports.PREVIEWED':'تمت المعاينة','imports.COMMITTED':'تم التنفيذ','imports.EXPIRED':'منتهية','imports.created':'تاريخ الرفع','imports.expires':'المعاينة صالحة لحد','imports.disabledKind':'مش متاح بصلاحياتك أو إعدادات الوحدات الحالية.','imports.new':'ابدأ دفعة تانية','organization.cap.imports.commit':'رفع ومعاينة وتنفيذ دفعات الاستيراد من إكسل'
};
