export const supportEn = {
  'support.title': 'Installation support',
  'support.help': 'Fixed, audited support actions for this installation. There is no shell, SQL or file browser here.',
  'support.installation': 'Installation',
  'support.release': 'Release',
  'support.schema': 'Schema version',
  'support.pendingMigrations': 'Pending migrations',
  'support.license': 'Subscription',
  'support.worker': 'Background worker',
  'support.workerHealthy': 'Healthy (last seen {seconds}s ago)',
  'support.workerStale': 'No heartbeat for {seconds}s',
  'support.workerNever': 'Never seen',
  'support.queues': 'Job queues',
  'support.queueName': 'Queue',
  'support.queueState': 'State',
  'support.queueCount': 'Jobs',
  'support.queueOldest': 'Oldest',
  'support.failedJobs': 'Failed jobs (24h): {count}',
  'support.overdueJobs': 'Overdue jobs: {count}',
  'support.billingLast': 'Last recurring charge period: {value}',
  'support.remindersLast': 'Last reminder: {value}',
  'support.storage': 'Storage',
  'support.privateFilesFree': 'Private files: {free} free of {total}',
  'support.backupsFree': 'Backups: {free} free of {total}',
  'support.storageUnknown': 'Not available',
  'support.backups': 'Backups',
  'support.backupsHelp': 'Encrypted recovery sets (database + private files) are written by the worker. Seven daily and four weekly scheduled sets are retained; copies leave the server only when an off-host destination is configured.',
  'support.backupsNotConfigured': 'Backups are not configured on this installation (BACKUP_DIR / BACKUP_ENCRYPTION_KEY).',
  'support.offsiteMissing': 'No off-host destination is configured: archives stay on this server only.',
  'support.lastSuccessful': 'Last successful backup: {value}',
  'support.backupAge': '{hours} hours ago',
  'support.never': 'never',
  'support.failedRecently': 'Failed or skipped runs in the last 7 days: {count}',
  'support.requestBackup': 'Create backup now',
  'support.backupRequested': 'Backup requested. The worker starts it within a minute; refresh to follow its status.',
  'support.reason': 'Reason (audited)',
  'support.kind': 'Kind',
  'support.status': 'Status',
  'support.requestedAt': 'Requested',
  'support.finishedAt': 'Finished',
  'support.archive': 'Archive',
  'support.size': 'Size',
  'support.files': 'Files',
  'support.offsite': 'Off-host copy',
  'support.error': 'Problem',
  'support.deleted': 'Deleted by retention',
  'support.yes': 'Yes',
  'support.no': 'No',
  'support.refresh': 'Refresh',
  'support.restoreValidation': 'Restore validation (isolated target)',
  'support.restoreHelp': 'Restores a recovery set into the isolated validation database and directory, then checks schema, files, login state, debt and treasury. Nothing touches the live installation; a live restore is an operator command.',
  'support.restoreNotConfigured': 'The isolated validation target is not configured (RESTORE_VALIDATION_DATABASE_URL / RESTORE_VALIDATION_FILES_DIR). Requests will fail visibly.',
  'support.selectBackup': 'Recovery set',
  'support.confirmArchive': 'Type the archive name to confirm',
  'support.operatorPassword': 'Your password (re-entered)',
  'support.startValidation': 'Start restore validation',
  'support.validationRequested': 'Restore validation requested. The worker runs it within a minute.',
  'support.target': 'Target database',
  'support.report': 'Report',
  'support.reportSummary': 'Files {files} (missing {missing}), accounts {accounts}, children {children}, debt {debt}, treasury {treasury}, sessions revoked {sessions}',
  'support.audit': 'Audit search',
  'support.auditHelp': 'Authentication, licensing, support, financial-operation and child audit events. Passwords, tokens and file contents are never stored.',
  'support.auditQuery': 'Event, username or ID',
  'support.from': 'From',
  'support.to': 'To',
  'support.search': 'Search',
  'support.source': 'Source',
  'support.event': 'Event',
  'support.actor': 'Actor',
  'support.targetId': 'Target',
  'support.when': 'When',
  'support.noResults': 'No matching events.',
  'support.accounts': 'Account lookup',
  'support.accountsHelp': 'Find an account by username or ID, then use the audited reset, block/unblock, deactivate/reactivate or release/restore actions. Releasing a seat is the only action that frees a reservation.',
  'support.accountQuery': 'Username or account ID',
  'support.username': 'Username',
  'support.accountKind': 'Kind',
  'support.accountStatus': 'Status',
  'support.reservation': 'Seat reserved',
  'support.lastLogin': 'Last sign-in',
  'support.mustChange': 'Temporary password pending',
  'support.copyId': 'Use this ID',
  'support.action': 'Action',
  'support.selectedAccount': 'Selected account ID: {id}',
  'support.resetPassword': 'Reset password',
  'support.resetDone': 'Temporary password (shown once):',
  'support.blockParent': 'Block parent',
  'support.unblockParent': 'Unblock parent',
  'support.deactivateStaff': 'Deactivate staff',
  'support.reactivateStaff': 'Reactivate staff',
  'support.releaseSeat': 'Release seat (Superadmin)',
  'support.restoreAccount': 'Restore released account',
  'support.publicMessage': 'Message shown to the parent',
  'support.untilDate': 'Blocked until (optional)',
  'support.actionDone': 'Action recorded.',
  'support.archival': 'Child archival preview',
  'support.archivalHelp': 'Shows the records that stay attached to a child before archiving it. Archiving ends future monthly generation and keeps every obligation, receipt, document and history record; nothing is deleted.',
  'support.childId': 'Child ID',
  'support.preview': 'Preview dependents',
  'support.dependents': '{code} — {name} ({status}): {links} guardian links, {obligations} obligations with {outstanding} outstanding, {receipts} receipts, {documents} documents, {attendance} attendance records, {learning} learning records.',
  'support.archiveChild': 'Archive child',
  'support.archived': 'Child archived; history retained.',
  'support.backupNotConfigured': 'Backups are not configured on this installation.',
  'support.backupPending': 'A manual backup is already requested or running.',
  'support.backupNotFound': 'Recovery set not found.',
  'support.backupNotRestorable': 'Only a successful, retained recovery set can be validated.',
  'support.confirmationMismatch': 'The typed archive name does not match the selected recovery set.',
  'support.restorePending': 'A restore validation is already requested or running.',
  'organization.cap.support.restore': 'Start restore validations of recovery sets (Superadmin only)'
} as const;

export const supportAr: Record<keyof typeof supportEn, string> = {
  'support.title': 'دعم التركيب',
  'support.help': 'إجراءات دعم ثابتة ومسجَّلة لهذا التركيب. لا يوجد هنا سطر أوامر ولا SQL ولا متصفح ملفات.',
  'support.installation': 'التركيب',
  'support.release': 'الإصدار',
  'support.schema': 'إصدار قاعدة البيانات',
  'support.pendingMigrations': 'ترحيلات معلّقة',
  'support.license': 'الاشتراك',
  'support.worker': 'عامل الخلفية',
  'support.workerHealthy': 'يعمل (آخر نبضة منذ {seconds} ثانية)',
  'support.workerStale': 'لا نبضة منذ {seconds} ثانية',
  'support.workerNever': 'لم يُرصد بعد',
  'support.queues': 'طوابير المهام',
  'support.queueName': 'الطابور',
  'support.queueState': 'الحالة',
  'support.queueCount': 'المهام',
  'support.queueOldest': 'الأقدم',
  'support.failedJobs': 'مهام فشلت (24 ساعة): {count}',
  'support.overdueJobs': 'مهام متأخرة: {count}',
  'support.billingLast': 'آخر فترة رسوم دورية: {value}',
  'support.remindersLast': 'آخر تذكير: {value}',
  'support.storage': 'التخزين',
  'support.privateFilesFree': 'الملفات الخاصة: {free} متاح من {total}',
  'support.backupsFree': 'النسخ الاحتياطية: {free} متاح من {total}',
  'support.storageUnknown': 'غير متاح',
  'support.backups': 'النسخ الاحتياطية',
  'support.backupsHelp': 'يكتب عامل الخلفية مجموعات استرجاع مشفّرة (قاعدة البيانات + الملفات الخاصة). يُحتفظ بسبع نسخ يومية وأربع أسبوعية؛ ولا تغادر النسخ الخادم إلا عند ضبط وجهة خارجية.',
  'support.backupsNotConfigured': 'النسخ الاحتياطي غير مضبوط في هذا التركيب (BACKUP_DIR / BACKUP_ENCRYPTION_KEY).',
  'support.offsiteMissing': 'لا توجد وجهة خارجية مضبوطة: النسخ تبقى على هذا الخادم فقط.',
  'support.lastSuccessful': 'آخر نسخة ناجحة: {value}',
  'support.backupAge': 'منذ {hours} ساعة',
  'support.never': 'لا يوجد',
  'support.failedRecently': 'تشغيلات فشلت أو تخطّت خلال 7 أيام: {count}',
  'support.requestBackup': 'إنشاء نسخة الآن',
  'support.backupRequested': 'تم طلب النسخة. يبدأها العامل خلال دقيقة؛ حدّث الصفحة لمتابعة الحالة.',
  'support.reason': 'السبب (يُسجَّل)',
  'support.kind': 'النوع',
  'support.status': 'الحالة',
  'support.requestedAt': 'طُلبت',
  'support.finishedAt': 'انتهت',
  'support.archive': 'الأرشيف',
  'support.size': 'الحجم',
  'support.files': 'الملفات',
  'support.offsite': 'نسخة خارجية',
  'support.error': 'المشكلة',
  'support.deleted': 'حُذفت بسياسة الاحتفاظ',
  'support.yes': 'نعم',
  'support.no': 'لا',
  'support.refresh': 'تحديث',
  'support.restoreValidation': 'التحقق من الاسترجاع (هدف معزول)',
  'support.restoreHelp': 'يسترجع مجموعة استرجاع في قاعدة بيانات ومجلد التحقق المعزولين ثم يفحص الهيكل والملفات وحالة الدخول والمديونية والخزينة. لا يمس التركيب الحي؛ الاسترجاع الحي أمر تشغيلي منفصل.',
  'support.restoreNotConfigured': 'هدف التحقق المعزول غير مضبوط (RESTORE_VALIDATION_DATABASE_URL / RESTORE_VALIDATION_FILES_DIR). ستفشل الطلبات بشكل ظاهر.',
  'support.selectBackup': 'مجموعة الاسترجاع',
  'support.confirmArchive': 'اكتب اسم الأرشيف للتأكيد',
  'support.operatorPassword': 'كلمة مرورك (إعادة إدخال)',
  'support.startValidation': 'بدء التحقق من الاسترجاع',
  'support.validationRequested': 'تم طلب التحقق من الاسترجاع. يشغّله العامل خلال دقيقة.',
  'support.target': 'قاعدة البيانات الهدف',
  'support.report': 'التقرير',
  'support.reportSummary': 'الملفات {files} (مفقودة {missing})، الحسابات {accounts}، الأطفال {children}، المديونية {debt}، الخزينة {treasury}، جلسات أُلغيت {sessions}',
  'support.audit': 'بحث السجل',
  'support.auditHelp': 'أحداث الدخول والترخيص والدعم والعمليات المالية وسجل الأطفال. لا تُخزَّن كلمات المرور أو الرموز أو محتوى الملفات أبدًا.',
  'support.auditQuery': 'الحدث أو اسم المستخدم أو المعرّف',
  'support.from': 'من',
  'support.to': 'إلى',
  'support.search': 'بحث',
  'support.source': 'المصدر',
  'support.event': 'الحدث',
  'support.actor': 'المنفّذ',
  'support.targetId': 'الهدف',
  'support.when': 'التوقيت',
  'support.noResults': 'لا توجد أحداث مطابقة.',
  'support.accounts': 'البحث عن حساب',
  'support.accountsHelp': 'ابحث عن حساب بالاسم أو المعرّف ثم استخدم إجراءات إعادة التعيين أو الحظر/إلغائه أو التعطيل/إعادة التفعيل أو تحرير/استعادة المقعد المسجَّلة. تحرير المقعد هو الإجراء الوحيد الذي يفرّغ حجزًا.',
  'support.accountQuery': 'اسم المستخدم أو معرّف الحساب',
  'support.username': 'اسم المستخدم',
  'support.accountKind': 'النوع',
  'support.accountStatus': 'الحالة',
  'support.reservation': 'مقعد محجوز',
  'support.lastLogin': 'آخر دخول',
  'support.mustChange': 'كلمة مرور مؤقتة معلّقة',
  'support.copyId': 'استخدام هذا المعرّف',
  'support.action': 'الإجراء',
  'support.selectedAccount': 'معرّف الحساب المحدد: {id}',
  'support.resetPassword': 'إعادة تعيين كلمة المرور',
  'support.resetDone': 'كلمة المرور المؤقتة (تظهر مرة واحدة):',
  'support.blockParent': 'حظر ولي الأمر',
  'support.unblockParent': 'إلغاء حظر ولي الأمر',
  'support.deactivateStaff': 'تعطيل الموظف',
  'support.reactivateStaff': 'إعادة تفعيل الموظف',
  'support.releaseSeat': 'تحرير المقعد (المشرف الأعلى)',
  'support.restoreAccount': 'استعادة حساب محرَّر',
  'support.publicMessage': 'رسالة تظهر لولي الأمر',
  'support.untilDate': 'محظور حتى (اختياري)',
  'support.actionDone': 'تم تسجيل الإجراء.',
  'support.archival': 'معاينة أرشفة طفل',
  'support.archivalHelp': 'يعرض السجلات التي تبقى مرتبطة بالطفل قبل أرشفته. تُنهي الأرشفة توليد الرسوم الشهرية المستقبلية وتحتفظ بكل التزام وإيصال ومستند وسجل؛ لا يُحذف شيء.',
  'support.childId': 'معرّف الطفل',
  'support.preview': 'معاينة السجلات المرتبطة',
  'support.dependents': '{code} — {name} ({status}): {links} روابط أولياء أمور، {obligations} التزامات بمتبقٍّ {outstanding}، {receipts} إيصالات، {documents} مستندات، {attendance} سجلات حضور، {learning} سجلات تعلّم.',
  'support.archiveChild': 'أرشفة الطفل',
  'support.archived': 'تمت أرشفة الطفل مع الاحتفاظ بالسجل.',
  'support.backupNotConfigured': 'النسخ الاحتياطي غير مضبوط في هذا التركيب.',
  'support.backupPending': 'هناك نسخة يدوية مطلوبة أو قيد التشغيل بالفعل.',
  'support.backupNotFound': 'مجموعة الاسترجاع غير موجودة.',
  'support.backupNotRestorable': 'يمكن التحقق فقط من مجموعة استرجاع ناجحة ومحتفظ بها.',
  'support.confirmationMismatch': 'اسم الأرشيف المكتوب لا يطابق مجموعة الاسترجاع المختارة.',
  'support.restorePending': 'هناك تحقق من الاسترجاع مطلوب أو قيد التشغيل بالفعل.',
  'organization.cap.support.restore': 'بدء التحقق من استرجاع مجموعات الاسترجاع (للمشرف الأعلى فقط)'
};
