import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { cairoIsoDate, formatDateOnly } from '@nursery/domain';
import type { AttendanceClassroomDraft, AttendanceDailyReport, AttendancePresence, AttendanceRecord } from '@nursery/contracts';
import { Button, SelectField, TextField } from '../../components/controls.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import type { MessageKey } from '../../i18n/catalogs.js';
import { useAuth } from '../auth/AuthProvider.js';
import { errorKey, useScoped } from '../children/scoped.js';

function Frame({ children }: { children: ReactNode }) { return <main className="organization-page">{children}</main>; }
type Choice={ include: boolean; statusId: string; absenceReason: string };
const labelFor=(presence: AttendancePresence) => presence==='PRESENT' ? 'attendance.present' : presence==='ABSENT' ? 'attendance.absent' : 'attendance.noClass';

function History({ childId,date }: { childId: string; date: string }) {
  const { t }=useLocale(); const state=useScoped<AttendanceRecord[]>(`attendance/children/${childId}/history?date=${date}`);
  return <details><summary>{t('attendance.history')}</summary>{state.error && <p role="alert">{t(state.error)}</p>}<ol>{state.data?.map((record) => <li key={record.event.id}>{t(labelFor(record.presence))}{record.absenceReason && ` — ${record.absenceReason}`}{record.event.reason && ` — ${t('attendance.correctionReason')}: ${record.event.reason}`}</li>)}</ol></details>;
}

function Correction({ childId,date,record,draft,reload }: { childId: string; date: string; record: AttendanceRecord; draft: AttendanceClassroomDraft; reload: () => void }) {
  const { t,locale }=useLocale(); const auth=useAuth(); const definition=draft.entries.find((entry) => entry.childId===childId)!.definition;
  const outcomes=definition.statuses.filter((status) => status.enabled && ['PRESENT','ABSENT'].includes(status.outcome ?? ''));
  const [statusId,setStatus]=useState(record.event.statusId); const [absenceReason,setAbsenceReason]=useState(record.absenceReason ?? ''); const [reason,setReason]=useState('');
  const [operationId,setOperation]=useState(crypto.randomUUID()); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null); const selected=outcomes.find((status) => status.id===statusId);
  const edit=(work: () => void) => { work(); setOperation(crypto.randomUUID()); };
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(null); try { await auth.client.business('attendance/corrections','POST',{ childId,date,statusId,absenceReason: selected?.outcome==='ABSENT' ? absenceReason || null : null,expectedVersion: record.event.revision,operationId,reason }); reload(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
  return <details><summary>{t('attendance.correct')}</summary><form onSubmit={(e) => { void submit(e); }}><fieldset disabled={busy} className="organization-fields"><legend>{t('attendance.correct')}</legend>{error && <p role="alert">{t(error)}</p>}<SelectField label={t('learning.status')} value={statusId} onChange={(e) => edit(() => setStatus(e.target.value))}>{outcomes.map((status) => <option key={status.id} value={status.id}>{status.label[locale]}</option>)}</SelectField>{selected?.outcome==='ABSENT' && <TextField label={t('attendance.absenceReason')} maxLength={500} value={absenceReason} onChange={(e) => edit(() => setAbsenceReason(e.target.value))} />}<TextField label={t('attendance.correctionReason')} required maxLength={500} value={reason} onChange={(e) => edit(() => setReason(e.target.value))} /><Button type="submit">{t('attendance.correct')}</Button></fieldset></form></details>;
}

function ClassroomAttendance({ classroomId,date }: { classroomId: string; date: string }) {
  const { t,locale }=useLocale(); const auth=useAuth(); const state=useScoped<AttendanceClassroomDraft>(`attendance/classrooms/${classroomId}/draft?date=${date}`); const draft=state.data;
  const [choices,setChoices]=useState<Record<string,Choice>>({}); const [operationId,setOperation]=useState(crypto.randomUUID()); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null); const [saved,setSaved]=useState(false);
  const effective=useMemo(() => draft ? Object.fromEntries(draft.entries.map((entry) => { const present=entry.definition.statuses.find((status) => status.outcome==='PRESENT')?.id ?? ''; return [entry.childId,choices[entry.childId] ?? { include: false,statusId: present,absenceReason: '' }]; })) : {},[draft,choices]);
  const edit=(next: Record<string,Choice>) => { setChoices(next); setOperation(crypto.randomUUID()); setSaved(false); };
  async function publish() { if (!draft) return; setBusy(true); setError(null); try { await auth.client.business('attendance/classroom-publications','POST',{ classroomId,date,operationId,entries: draft.entries.filter((entry) => !entry.record && effective[entry.childId]?.include).map((entry) => { const choice=effective[entry.childId]; const status=entry.definition.statuses.find((value) => value.id===choice.statusId); return { childId: entry.childId,statusId: choice.statusId,absenceReason: status?.outcome==='ABSENT' ? choice.absenceReason || null : null,expectedVersion: 0 }; }) }); setSaved(true); setChoices({}); state.reload(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
  async function noClass() { setBusy(true); setError(null); try { await auth.client.business('attendance/no-class','POST',{ classroomId,date,operationId }); setSaved(true); state.reload(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
  if (state.error) return <p role="alert">{t(state.error)}</p>; if (!draft) return <p role="status">{t('state.loading')}</p>;
  return <section><h2>{draft.classroomName}</h2><p>{t('attendance.progress',{ complete: draft.complete,total: draft.total })}</p><progress aria-label={t('attendance.progress',{ complete: draft.complete,total: draft.total })} max={draft.total || 1} value={draft.complete} />{error && <p role="alert">{t(error)}</p>}{saved && <p role="status">{t('attendance.saved')}</p>}{!draft.entries.length ? <p>{t('attendance.empty')}</p> : <><p>{t('attendance.reviewHelp')}</p><fieldset disabled={busy || draft.noClass} className="organization-fields"><legend>{t('attendance.classroom')}</legend><Button variant="secondary" onClick={() => edit(Object.fromEntries(draft.entries.map((entry) => { const present=entry.definition.statuses.find((status) => status.outcome==='PRESENT')?.id ?? ''; return [entry.childId,{ include: !entry.record,statusId: present,absenceReason: '' }]; })))}>{t('attendance.bulkPresent')}</Button>{draft.entries.map((entry) => { const choice=effective[entry.childId]; const statuses=entry.definition.statuses.filter((status) => status.enabled && ['PRESENT','ABSENT'].includes(status.outcome ?? '')); const selected=statuses.find((status) => status.id===choice.statusId); return <fieldset key={entry.childId} className="organization-fields"><legend>{entry.fullName}</legend>{entry.notices.map((notice,index) => <p key={index}>{t(notice.reason ? 'attendance.notice' : 'attendance.noticeNoReason',{ reason: notice.reason ?? '' })}</p>)}{entry.record ? <><strong>{t(labelFor(entry.record.presence))}</strong>{entry.record.absenceReason && <p>{entry.record.absenceReason}</p>}<Correction childId={entry.childId} date={date} record={entry.record} draft={draft} reload={state.reload} /><History childId={entry.childId} date={date} /></> : <><p>{t('attendance.missing')}</p><label><input type="checkbox" checked={choice.include} onChange={(e) => edit({ ...effective,[entry.childId]: { ...choice,include: e.target.checked } })} />{t('attendance.include')}</label><SelectField label={t('learning.status')} value={choice.statusId} onChange={(e) => edit({ ...effective,[entry.childId]: { ...choice,statusId: e.target.value } })}>{statuses.map((status) => <option key={status.id} value={status.id}>{status.label[locale]}</option>)}</SelectField>{selected?.outcome==='ABSENT' && <TextField label={t('attendance.absenceReason')} maxLength={500} value={choice.absenceReason} onChange={(e) => edit({ ...effective,[entry.childId]: { ...choice,absenceReason: e.target.value } })} />}</>}</fieldset>; })}<Button disabled={!draft.entries.some((entry) => !entry.record && effective[entry.childId]?.include)} onClick={() => { void publish(); }}>{t('attendance.publish')}</Button></fieldset>{draft.complete===0 && <section><p>{t('attendance.noClassHelp')}</p><Button variant="secondary" disabled={busy} onClick={() => { void noClass(); }}>{t('attendance.noClass')}</Button></section>}</>}</section>;
}

type RosterChild={ id: string; classroomId: string; classroomName: string };
export function TeacherAttendanceScreen() {
  const { t }=useLocale(); const [date,setDate]=useState(cairoIsoDate()); const roster=useScoped<RosterChild[]>('learning/roster?offset=0'); const classrooms=roster.data?.filter((child,index,all) => all.findIndex((value) => value.classroomId===child.classroomId)===index) ?? []; const [selected,setSelected]=useState(''); const classroomId=classrooms.some((value) => value.classroomId===selected) ? selected : classrooms[0]?.classroomId;
  return <Frame><h1>{t('attendance.title')}</h1><TextField label={t('attendance.date')} type="date" max={cairoIsoDate()} value={date} onChange={(e) => setDate(e.target.value)} />{roster.error && <p role="alert">{t(roster.error)}</p>}{classrooms.length ? <><SelectField label={t('learning.classroom')} value={classroomId} onChange={(e) => setSelected(e.target.value)}>{classrooms.map((value) => <option key={value.classroomId} value={value.classroomId}>{value.classroomName}</option>)}</SelectField>{classroomId && date && <ClassroomAttendance key={`${classroomId}/${date}`} classroomId={classroomId} date={date} />}</> : <p>{t('attendance.empty')}</p>}</Frame>;
}

export function GuardianAttendancePanel({ childId }: { childId: string }) {
  const { t }=useLocale(); const auth=useAuth(); const today=cairoIsoDate(); const report=useScoped<AttendanceDailyReport>(`attendance/children/${childId}/daily?date=${today}`); const [from,setFrom]=useState(today); const [until,setUntil]=useState(today); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null); const [saved,setSaved]=useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(null); try { await auth.client.business('attendance/planned-absence','PUT',{ childId,from,until,reason: reason || null }); setSaved(true); report.reload(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
  if (report.error==='learning.disabled') return null;
  if (!report.data) return <p role={report.error ? 'alert' : 'status'}>{t(report.error || 'state.loading')}</p>;
  return <section><h2>{t('attendance.title')} — {formatDateOnly(today)}</h2>{report.error && <p role="alert">{t(report.error)}</p>}{report.data && <>{!report.data.progress.hidden && <><p>{t('learning.progress',{ completed: report.data.progress.completed,total: report.data.progress.total })}</p><progress aria-label={t('learning.title')} max={report.data.progress.total} value={report.data.progress.completed} /></>}<p>{t('attendance.current')}: {report.data.attendance ? t(labelFor(report.data.attendance.presence)) : t('attendance.missing')}</p></>}<form onSubmit={(e) => { void submit(e); }}><fieldset disabled={busy} className="organization-fields"><legend>{t('attendance.planned')}</legend><p>{t('attendance.plannedHelp')}</p>{error && <p role="alert">{t(error)}</p>}{saved && <p role="status">{t('attendance.noticeSaved')}</p>}<TextField label={t('attendance.from')} type="date" min={today} value={from} onChange={(e) => setFrom(e.target.value)} /><TextField label={t('attendance.until')} type="date" min={from} value={until} onChange={(e) => setUntil(e.target.value)} /><TextField label={t('attendance.reason')} maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} /><Button type="submit">{t('attendance.planned')}</Button></fieldset></form></section>;
}
