import { beforeAll,afterAll,afterEach,describe,it,expect } from 'vitest';
import { runBillingBatch } from '@nursery/db';
import { cairoIsoDate,monthStart,nextMonth } from '@nursery/domain';
import type { ChildTransferInput,AgreementTerms } from '@nursery/contracts';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';

describe('Phase 17 child transfer PostgreSQL',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;
 beforeAll(async()=>{f=await financeFixture();});afterAll(async()=>{await f?.close();});
 afterEach(async()=>{expect(await reconcileFinance(f.database)).toEqual([]);});
 const op=()=>crypto.randomUUID();
 const input=(childId:string,extra:Partial<ChildTransferInput>={}):ChildTransferInput=>({operationId:op(),childId,sourceBranchId:f.a.id,destinationBranchId:f.b.id,destinationClassroomId:f.classes[2].id,effectiveOn:cairoIsoDate(),expectedVersion:1,reason:'Family requested branch move',...extra});
 const previewInput=({operationId:_op,reason:_reason,...rest}:ChildTransferInput)=>rest;
 const cash=async()=>(await f.database.pool.query('select id,balance::text from treasury_balances order by id')).rows;
 it('A21: 4000 charge, 1500 collected in A, only 2500 moves; original debt/dates/receipts and treasury are retained',async()=>{
  const c=await f.child('TRANSFER-A21'),charge=await f.charge(c.childId,'400000');
  const payment=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0],'150000'));
  const original=(await f.database.pool.query('select * from obligations where id=$1',[charge.id])).rows;
  const receipt=await f.payments.getReceipt(f.root.token,payment.receiptIds[0]),before=await cash(),move=input(c.childId);
  const preview=await f.app.childTransfers.preview(f.root.token,previewInput(move));expect(preview.amount).toBe('250000');expect(preview.items[0]).toMatchObject({obligationId:charge.id,installmentId:charge.installmentIds[0],dueOn:cairoIsoDate()});
  const result=await f.app.childTransfers.transfer(f.root.token,move);expect(result.amount).toBe('250000');expect(await cash()).toEqual(before);
  expect(await f.app.childTransfers.transfer(f.root.token,move)).toEqual(result);
  expect((await f.database.pool.query('select * from obligations where id=$1',[charge.id])).rows).toEqual(original);
  expect(await f.payments.getReceipt(f.root.token,payment.receiptIds[0])).toEqual(receipt);
  expect((await f.ledger.outstanding(f.root.token,{childId:c.childId,branchId:f.a.id})).totalRemaining).toBe('0');
  expect((await f.ledger.outstanding(f.root.token,{childId:c.childId,branchId:f.b.id})).totalRemaining).toBe('250000');
  const later=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0],'250000',f.b.id,f.cashB.id));
  expect((await f.payments.getReceipt(f.root.token,later.receiptIds[0])).branchId).toBe(f.b.id);
  expect((await f.ledger.balances(f.root.token,{},c.childId)).totalRemaining).toBe('0');
  expect((await cash()).find(r=>r.id===f.cashA.id).balance).toBe('150000');expect((await cash()).find(r=>r.id===f.cashB.id).balance).toBe('250000');
  const out=await f.app.childTransfers.history(f.root.token,{branchId:f.a.id});expect(out.totalOut).toBe('250000');
  expect((await f.app.childTransfers.history(f.root.token,{branchId:f.b.id})).totalIn).toBe('250000');
  expect((await f.database.pool.query("select payload from child_integration_events where child_id=$1 and kind='child.branch_transferred'",[c.childId])).rows[0].payload).toMatchObject({automaticEnrollment:false,transportAction:'REVIEW_REQUIRED',eventAction:'REVIEW_REQUIRED'});
 });
 it('A01/A02: both branch capabilities required; current teacher/manager scope changes, source receipts remain private, parent history continues',async()=>{
  const c=await f.child('TRANSFER-SCOPE'),d=await f.charge(c.childId,'40000');const receipt=await f.payments.collect(f.root.token,f.collect(d.installmentIds[0],'10000'));
  const capabilities=['finance.read','billing.manage','payments.record','children.manage','children.read'] as const;
  const a=await f.financeStaff([f.a.id],[],'BRANCH',[...capabilities]),b=await f.financeStaff([f.b.id],[],'BRANCH',[...capabilities]);
  const oldTeacher=await f.financeStaff([f.a.id],[f.classes[0].id],'CLASSROOM',[...capabilities]),newTeacher=await f.financeStaff([f.b.id],[f.classes[2].id],'CLASSROOM',[...capabilities]);
  const move=input(c.childId);await expect(f.app.childTransfers.transfer(a.token,move)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.app.childTransfers.preview(b.token,previewInput(move))).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.app.childTransfers.transfer(f.root.token,move);
  await expect(f.children.detail(oldTeacher.token,c.childId)).rejects.toMatchObject({code:'FORBIDDEN'});expect((await f.children.detail(newTeacher.token,c.childId)).child.branchId).toBe(f.b.id);
  expect((await f.ledger.outstanding(a.token,{childId:c.childId})).totalRemaining).toBe('0');expect((await f.ledger.outstanding(newTeacher.token,{childId:c.childId})).totalRemaining).toBe('30000');
  expect((await f.payments.getReceipt(a.token,receipt.receiptIds[0])).branchId).toBe(f.a.id);await expect(f.payments.getReceipt(b.token,receipt.receiptIds[0])).rejects.toMatchObject({code:'FORBIDDEN'});
  expect((await f.app.childTransfers.history(a.token,{})).items.some(t=>t.childId===c.childId)).toBe(true);expect((await f.app.childTransfers.history(b.token,{})).items.some(t=>t.childId===c.childId)).toBe(true);
  const credential=c.credentials[0];let parent=await f.app.auth.login(credential.username,credential.temporaryPassword);await f.app.auth.changePassword(parent.token,credential.temporaryPassword,'New transfer parent password 2026');parent=await f.app.auth.login(credential.username,'New transfer parent password 2026');
  expect((await f.ledger.balances(parent.token,{},c.childId)).totalRemaining).toBe('30000');expect((await f.payments.receipts(parent.token,{},c.childId)).map(r=>r.id)).toContain(receipt.receiptIds[0]);expect((await f.app.childTransfers.history(parent.token,{},c.childId)).items).toHaveLength(1);
  const outsider=await f.child('TRANSFER-OTHER',f.b.id);await expect(f.app.childTransfers.history(parent.token,{},outsider.childId)).rejects.toMatchObject({code:'FORBIDDEN'});
 });
 it('commit recalculates stale preview; repeated chain, fully paid anchors, invalid date/classroom/status/version and operation conflict',async()=>{
  const c=await f.child('TRANSFER-CHAIN'),d=await f.charge(c.childId,'10000',''+f.tuition.id,['4000','6000']);const move=input(c.childId);
  expect((await f.app.childTransfers.preview(f.root.token,previewInput(move))).amount).toBe('10000');await f.payments.collect(f.root.token,f.collect(d.installmentIds[0],'4000'));
  for(const extra of [{effectiveOn:'2026-01-01'},{effectiveOn:'2099-01-01'},{destinationClassroomId:f.classes[0].id},{expectedVersion:2},{destinationBranchId:f.a.id}]) await expect(f.app.childTransfers.transfer(f.root.token,input(c.childId,extra))).rejects.toThrow();
  const first=await f.app.childTransfers.transfer(f.root.token,move);expect(first.amount).toBe('6000');expect(first.items).toHaveLength(1);
  const second=await f.app.childTransfers.transfer(f.root.token,input(c.childId,{sourceBranchId:f.b.id,destinationBranchId:f.a.id,destinationClassroomId:f.classes[1].id,expectedVersion:2}));expect(second.amount).toBe('6000');expect(second.items[0].installmentId).toBe(d.installmentIds[1]);
  expect(await f.app.childTransfers.transfer(f.root.token,move)).toEqual(first);await expect(f.app.childTransfers.transfer(f.root.token,{...move,reason:'Changed request'})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
  await expect(f.database.pool.query('update child_branch_transfers set amount=0 where id=$1',[first.id])).rejects.toThrow();await expect(f.database.pool.query('delete from transferred_due_items where transfer_id=$1',[first.id])).rejects.toThrow();
  await f.children.lifecycle(f.root.token,c.childId,{status:'ARCHIVED',expectedVersion:3,reason:'Archive child',publicMessage:'Archived'});await expect(f.app.childTransfers.transfer(f.root.token,input(c.childId,{expectedVersion:4}))).rejects.toMatchObject({code:'VALIDATION_ERROR'});
 });
 it('A22: payment/transfer contend on child row; one ordering, no lost debt, no stale source collection',async()=>{
  const c=await f.child('TRANSFER-RACE'),d=await f.charge(c.childId,'400000');const collector=await f.financeStaff([f.a.id]);
  const blocker=await f.database.pool.connect();await blocker.query('begin');await blocker.query('select id from children where id=$1 for update',[c.childId]);
  const competing=Promise.allSettled([f.payments.collect(collector.token,f.collect(d.installmentIds[0],'150000')),f.app.childTransfers.transfer(f.root.token,input(c.childId))]);
  try {await expect.poll(async()=>Number((await f.database.pool.query("select count(*) n from pg_stat_activity where wait_event_type='Lock' and pid<>pg_backend_pid()")).rows[0].n)).toBeGreaterThanOrEqual(2);}finally{await blocker.query('rollback');blocker.release();}
  const [payment,transfer]=await competing;expect(transfer.status).toBe('fulfilled');
  const due=(await f.ledger.outstanding(f.root.token,{childId:c.childId})).totalRemaining;
  expect(due).toBe(payment.status==='fulfilled'?'250000':'400000');
  if(transfer.status==='fulfilled')expect(transfer.value.amount).toBe(due);
  await expect(f.payments.collect(collector.token,f.collect(d.installmentIds[0],'1'))).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.payments.collect(f.root.token,f.collect(d.installmentIds[0],due,f.b.id,f.cashB.id));expect((await f.ledger.outstanding(f.root.token,{childId:c.childId})).totalRemaining).toBe('0');
 });
 it('paid source reversals restore current debt ownership; source-funded refunds retain receipts/accounts and historical scope',async()=>{
  await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true)',[f.root.account.id]);
  const c=await f.child('TRANSFER-PAID'),d=await f.charge(c.childId,'10000'),payment=await f.payments.collect(f.root.token,f.collect(d.installmentIds[0]));
  const moved=await f.app.childTransfers.transfer(f.root.token,input(c.childId));expect(moved.amount).toBe('0');expect(moved.items).toEqual([]);
  const manager=await f.financeStaff([f.b.id],[],'BRANCH',['finance.read','finance.correct','payments.record']);await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true)',[manager.id]);
  const reduction={operationId:op(),effectiveOn:cairoIsoDate(),reductionAmount:'1000',reason:'Reviewed paid reduction'};
  await expect(f.app.corrections.reduceTuition(manager.token,d.installmentIds[0],reduction)).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.app.corrections.correctReceipt(f.root.token,payment.receiptIds[0],{operationId:op(),effectiveOn:cairoIsoDate(),reason:'Reverse paid receipt after move',replacement:null});
  expect((await f.ledger.outstanding(manager.token,{childId:c.childId})).totalRemaining).toBe('10000');
  await expect(f.payments.collect(manager.token,{...f.collect(d.installmentIds[0],'10000',f.b.id,f.cashB.id),collectedOn:'2026-01-01'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
  await f.payments.collect(manager.token,f.collect(d.installmentIds[0],'10000',f.b.id,f.cashB.id));
  const child=await f.child('TRANSFER-REFUND'),debt=await f.charge(child.childId,'10000'),source=await f.payments.collect(f.root.token,f.collect(debt.installmentIds[0]));
  await f.app.childTransfers.transfer(f.root.token,input(child.childId));const credit=await f.app.corrections.reduceTuition(f.root.token,debt.installmentIds[0],{...reduction,operationId:op()});
  const sourceManager=await f.financeStaff([f.a.id]);
  expect((await f.app.corrections.corrections(manager.token,{})).some(r=>r.id===credit.correctionId)).toBe(true);
  expect((await f.app.corrections.corrections(sourceManager.token,{})).some(r=>r.id===credit.correctionId)).toBe(false);
  const origin=(await f.database.pool.query('select id,receipt_id,account_id from credit_origins where credit_id=$1',[credit.creditId])).rows[0];expect(origin).toMatchObject({receipt_id:source.receiptIds[0],account_id:f.cashA.id});
  const refund={operationId:op(),creditId:credit.creditId,creditOriginId:origin.id,accountId:f.cashA.id,amount:'1000',method:'CASH',refundedOn:cairoIsoDate(),reason:'Actual original-source refund after child move',externalReference:'',alternativeAccountConfirmed:false};
  await expect(f.app.corrections.refund(manager.token,refund)).rejects.toMatchObject({code:'FORBIDDEN'});const cashBefore=await cash();await f.app.corrections.refund(f.root.token,refund);const cashAfter=await cash();
  expect((await f.app.corrections.refunds(manager.token,{})).some(r=>r.creditId===credit.creditId)).toBe(false);
  expect((await f.app.corrections.refunds(sourceManager.token,{})).some(r=>r.creditId===credit.creditId)).toBe(true);
  expect(BigInt(cashAfter.find(r=>r.id===f.cashA.id).balance)).toBe(BigInt(cashBefore.find(r=>r.id===f.cashA.id).balance)-1000n);expect(cashAfter.find(r=>r.id===f.cashB.id)).toEqual(cashBefore.find(r=>r.id===f.cashB.id));
  await f.app.childTransfers.transfer(f.root.token,input(child.childId,{sourceBranchId:f.b.id,destinationBranchId:f.a.id,destinationClassroomId:f.classes[0].id,expectedVersion:2}));
  expect((await f.app.corrections.corrections(manager.token,{})).some(r=>r.id===credit.correctionId)).toBe(true);
  expect((await f.app.corrections.corrections(sourceManager.token,{})).some(r=>r.id===credit.correctionId)).toBe(false);
 });
 it('A22: family recurrence/transfer serialized; current occurrence identity/price retained; next period uses destination with unchanged sibling shares',async()=>{
  const c=await f.child('TRANSFER-MONTH'),s=await f.child('TRANSFER-SIBLING');const current=monthStart(cairoIsoDate()),future=nextMonth(current);
  const terms:AgreementTerms={mode:'MONTHLY',childIds:[c.childId,s.childId],categoryId:f.tuition.id,description:'Stable family shares',normalAmount:'1000000',agreedAmount:'800001',startsOn:current,endsOn:null,firstPeriod:current,dueDay:15,serviceFrom:null,serviceUntil:null,installments:[]};
  const a=await f.app.billing.draft(f.root.token,{operationId:op(),terms});await f.app.billing.approve(f.root.token,a.id,{operationId:op(),expectedVersion:1});
  const snapshot=(await f.database.pool.query('select * from recurrence_occurrences where agreement_id=$1 order by child_id',[a.id])).rows;
  const blocker=await f.database.pool.connect();await blocker.query('begin');await blocker.query('select id from children where id=$1 for update',[c.childId]);
  const race=Promise.all([f.app.childTransfers.transfer(f.root.token,input(c.childId)),runBillingBatch(f.database,future)]);
  try{await expect.poll(async()=>Number((await f.database.pool.query("select count(*) n from pg_stat_activity where wait_event_type='Lock' and pid<>pg_backend_pid()")).rows[0].n)).toBeGreaterThanOrEqual(2);}finally{await blocker.query('rollback');blocker.release();}await race;
  expect((await f.database.pool.query('select * from recurrence_occurrences where agreement_id=$1 and service_period_start=$2 order by child_id',[a.id,current])).rows).toEqual(snapshot);
  await Promise.all([runBillingBatch(f.database,nextMonth(future)),runBillingBatch(f.database,nextMonth(future))]);
  const rows=(await f.database.pool.query('select o.child_id,o.branch_id,o.amount::text from recurrence_occurrences r join obligations o on o.id=r.obligation_id where r.agreement_id=$1 and r.service_period_start=$2 order by o.child_id',[a.id,nextMonth(future)])).rows;
  expect(rows).toHaveLength(2);expect(rows.find(r=>r.child_id===c.childId).branch_id).toBe(f.b.id);expect(rows.find(r=>r.child_id===s.childId).branch_id).toBe(f.a.id);expect(rows.map(r=>r.amount)).toEqual(['400001','400000']);
 });
 it('atomic rollback includes child/history/ownership/outbox/operation and same-key retry succeeds; replay rechecks authority and module',async()=>{
  const c=await f.child('TRANSFER-ROLLBACK');await f.charge(c.childId);const move=input(c.childId),before=await cash();
  await f.database.pool.query("create function transfer_test_failure() returns trigger language plpgsql as $$ begin raise exception 'transfer fixture failure'; end $$; create trigger transfer_test_failure before insert on child_integration_events for each row when (new.kind='child.branch_transferred') execute function transfer_test_failure()");
  await expect(f.app.childTransfers.transfer(f.root.token,move)).rejects.toThrow('transfer fixture failure');expect((await f.children.detail(f.root.token,c.childId)).child).toMatchObject({branchId:f.a.id,version:1});
  expect((await f.database.pool.query('select * from child_branch_transfers where child_id=$1',[c.childId])).rows).toEqual([]);expect(await f.core.operationStatus(f.root.token,move.operationId)).toEqual({status:'NOT_FOUND'});expect(await cash()).toEqual(before);
  await f.database.pool.query('drop trigger transfer_test_failure on child_integration_events; drop function transfer_test_failure()');
  const staff=await f.financeStaff([f.a.id,f.b.id],[],'BRANCH',['finance.read','billing.manage','children.manage']);await f.app.childTransfers.transfer(staff.token,move);
  await f.app.organization.assign(f.root.token,staff.id,{expectedVersion:2,roleIds:[],branchIds:[],classroomIds:[],scopeMode:'BRANCH'});await expect(f.app.childTransfers.transfer(staff.token,move)).rejects.toMatchObject({code:'FORBIDDEN'});
  const module=(await f.licensing.modules(f.root.token)).find(m=>m.moduleKey==='FINANCE')!;await f.licensing.saveModuleSetting(f.root.token,'FINANCE',{expectedVersion:module.version,enabled:false,reason:'Disable fixture'});
  await expect(f.app.childTransfers.preview(f.root.token,previewInput(input(c.childId,{sourceBranchId:f.b.id,destinationBranchId:f.a.id,destinationClassroomId:f.classes[0].id,expectedVersion:2})))).rejects.toMatchObject({code:'MODULE_DISABLED'});
  await f.licensing.saveModuleSetting(f.root.token,'FINANCE',{expectedVersion:module.version+1,enabled:true,reason:'Restore fixture',catchupAcknowledged:true});
 });
});
