import { afterEach,describe,expect,it } from 'vitest';
import { cairoIsoDate } from '@nursery/domain';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';

describe('Phase 16 sensitive corrections, credits and refunds on PostgreSQL',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;
 afterEach(async()=>{if(f){expect(await reconcileFinance(f.database)).toEqual([]);await f.close();}});
 async function setup(){f=await financeFixture();await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true) on conflict(account_id) do update set sensitive_financial_edit=true',[f.root.account.id]);return f.app.corrections;}
 const balance=async(id:string)=>(await f.database.pool.query('select balance::text from treasury_balances where id=$1',[id])).rows[0].balance as string;
 const due=async(id:string)=>(await f.database.pool.query('select remaining::text from installment_balances where id=$1',[id])).rows[0].remaining as string;

 it('A25: a paid tuition reduction creates source-linked noncash credit; application and concurrent refund cannot overuse it',async()=>{
  const c=await setup(),child=await f.child('REDUCE'),charge=await f.charge(child.childId);const payment=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0]));const cashBefore=await balance(f.cashA.id);
  const reduction={operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reductionAmount:'3000',reason:'Approved tuition reduction after payment'};
  const result=await c.reduceTuition(f.root.token,charge.installmentIds[0],reduction);expect(result).toMatchObject({creditAmount:'3000',restoredCreditAmount:'0'});expect(await c.reduceTuition(f.root.token,charge.installmentIds[0],reduction)).toEqual(result);expect(await due(charge.installmentIds[0])).toBe('0');expect(await balance(f.cashA.id)).toBe(cashBefore);
  const credit=(await c.options(f.root.token)).credits.find(x=>x.id===result.creditId)!;expect(credit).toMatchObject({amount:'3000',remaining:'3000'});expect(credit.origins[0]).toMatchObject({receiptId:payment.receiptIds[0],accountId:f.cashA.id,amount:'3000',remaining:'3000'});
  const later=await f.charge(child.childId,'1000');const movements=(await f.database.pool.query('select count(*)::int n from treasury_movements')).rows[0].n;await f.payments.applyCredit(f.root.token,{operationId:crypto.randomUUID(),creditId:credit.id,appliedOn:cairoIsoDate(),allocations:[{installmentId:later.installmentIds[0],amount:'1000'}]});expect((await f.database.pool.query('select count(*)::int n from treasury_movements')).rows[0].n).toBe(movements);
  const refund=(operationId:string)=>({operationId,creditId:credit.id,creditOriginId:credit.origins[0].id,accountId:f.cashA.id,method:'CASH' as const,amount:'2000',refundedOn:cairoIsoDate(),reason:'Actual cash returned to guardian',externalReference:'REF-1',alternativeAccountConfirmed:false});
  const race=await Promise.allSettled([c.refund(f.root.token,refund(crypto.randomUUID())),c.refund(f.root.token,refund(crypto.randomUUID()))]);expect(race.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(race.find(x=>x.status==='rejected')).toMatchObject({reason:{code:'VALIDATION_ERROR'}});expect((await f.database.pool.query('select remaining::text from credit_balances where id=$1',[credit.id])).rows[0].remaining).toBe('0');expect(await balance(f.cashA.id)).toBe((BigInt(cashBefore)-2000n).toString());
  await expect(c.refund(f.root.token,refund(crypto.randomUUID()))).rejects.toMatchObject({code:'VALIDATION_ERROR'});expect((await c.refunds(f.root.token,{}))[0]).toMatchObject({amount:'2000',originalReceiptReference:expect.stringMatching(/^FIN-/),originalAccountCode:'A-CASH',fundingAccountCode:'A-CASH'});
  for(const table of ['refunds','credit_origins'])await expect(f.database.pool.query(`delete from ${table}`)).rejects.toThrow();
 });

 it('TRIP reduction uses the identical source-linked noncash credit invariant and rejects BUS',async()=>{
  const c=await setup(),trip=await f.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:'TRIP',name:'Trip',kind:'TRIP'}),child=await f.child('TRIP-REDUCE'),charge=await f.charge(child.childId,'5000',trip.id),payment=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0],'5000'));
  const result=await c.reduceTuition(f.root.token,charge.installmentIds[0],{operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reductionAmount:'5000',reason:'Cancelled trip'});expect(result.creditAmount).toBe('5000');
  expect((await f.database.pool.query('select target_kind from financial_corrections where id=$1',[result.correctionId])).rows[0].target_kind).toBe('TRIP');expect((await f.database.pool.query('select count(*)::int n from credit_origins where credit_id=$1 and receipt_id=$2',[result.creditId,payment.receiptIds[0]])).rows[0].n).toBe(1);
  const bus=await f.charge(child.childId,'1000',f.bus.id);await expect(c.reduceTuition(f.root.token,bus.installmentIds[0],{operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reductionAmount:'1',reason:'Invalid bus reduction'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
 });

 it('A25: receipt reversal/replacement is sensitive, current-dated, scoped, retry-safe, and preserves the original',async()=>{
  const c=await setup(),child=await f.child('RECEIPT'),charge=await f.charge(child.childId),payment=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0],'5000'));
  const staff=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','finance.correct']);const input={operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reason:'Correct incorrectly recorded amount',replacement:{accountId:f.cashA.id,method:'CASH' as const,amount:'4000',payerName:'Corrected payer',externalReference:'CORRECTED',allocations:[{installmentId:charge.installmentIds[0],amount:'4000'}]}};
  await expect(c.correctReceipt(staff.token,payment.receiptIds[0],input)).rejects.toMatchObject({code:'FORBIDDEN'});await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true)',[staff.id]);
  const result=await c.correctReceipt(staff.token,payment.receiptIds[0],input);expect(await c.correctReceipt(staff.token,payment.receiptIds[0],input)).toEqual(result);expect(await due(charge.installmentIds[0])).toBe('6000');expect(await balance(f.cashA.id)).toBe('4000');
  const original=await f.payments.getReceipt(f.root.token,payment.receiptIds[0]);expect(original).toMatchObject({amount:'5000',correctionState:'REPLACED',replacementReceiptId:result.replacementReceiptId});expect((await f.payments.getReceipt(f.root.token,result.replacementReceiptId!))).toMatchObject({amount:'4000',correctionState:'ACTIVE'});
  await expect(c.correctReceipt(staff.token,payment.receiptIds[0],{...input,operationId:crypto.randomUUID(),effectiveOn:'2026-09-13'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});const foreign=await f.financeStaff([f.b.id],[],'BRANCH',['finance.read','finance.correct']);await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true)',[foreign.id]);await expect(c.correctReceipt(foreign.token,result.replacementReceiptId!,{...input,operationId:crypto.randomUUID(),replacement:null})).rejects.toMatchObject({code:'FORBIDDEN'});
 });

 it('A25: active counted dates block cash corrections until reopen, with complete rollback',async()=>{
  const c=await setup(),child=await f.child('CLOSED-CORR'),charge=await f.charge(child.childId),payment=await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0]));const count=await f.app.closing.count(f.root.token,{operationId:crypto.randomUUID(),accountId:f.cashA.id,on:cairoIsoDate(),countedAmount:'10000',expectedRevision:0,reason:'Physical close'});
  const correction={operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reason:'Reverse mistaken receipt after review',replacement:null};const before=(await f.database.pool.query('select count(*)::int n from financial_corrections')).rows[0].n;await expect(c.correctReceipt(f.root.token,payment.receiptIds[0],correction)).rejects.toMatchObject({messageKey:'closing.closedDate'});expect((await f.database.pool.query('select count(*)::int n from financial_corrections')).rows[0].n).toBe(before);expect(await due(charge.installmentIds[0])).toBe('0');
  await f.app.closing.reopen(f.root.token,count.id,{operationId:crypto.randomUUID(),expectedRevision:1,reason:'Authorized correction requires reopen'});await c.correctReceipt(f.root.token,payment.receiptIds[0],correction);expect(await due(charge.installmentIds[0])).toBe('10000');expect(await balance(f.cashA.id)).toBe('0');expect((await f.database.pool.query('select counted::text from daily_closings where id=$1',[count.id])).rows[0].counted).toBe('10000');
 });

 it('expense and transfer reversals/replacements retain originals, project effective spending, and conserve total cash',async()=>{
  const c=await setup(),child=await f.child('SPEND-CORR'),charge=await f.charge(child.childId,'20000');await f.payments.collect(f.root.token,f.collect(charge.installmentIds[0],'20000'));
  const category=await f.app.spending.category(f.root.token,{operationId:crypto.randomUUID(),code:'SUPPLY-CORR',name:'Supplies correction'});const expense=await f.app.spending.create(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,classroomId:null,categoryId:category.id,amount:'1000',dueOn:cairoIsoDate(),note:'Original planned expense'});await f.app.spending.pay(f.root.token,expense.id,{operationId:crypto.randomUUID(),accountId:f.cashA.id,method:'CASH',paidOn:cairoIsoDate(),externalReference:'E1',reason:'Original actual payment'});
  await c.correctExpense(f.root.token,expense.id,{operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reason:'Vendor invoice corrected',replacement:{accountId:f.cashA.id,method:'CASH',amount:'700',externalReference:'E2'}});const page=await f.app.spending.list(f.root.token,{branchId:f.a.id});expect(page).toMatchObject({totalPaid:'700'});expect(page.items.find(x=>x.id===expense.id)).toMatchObject({state:'CORRECTED',amount:'1000',paidAmount:'700',correctionReason:'Vendor invoice corrected'});
  const transfer=await f.app.spending.transfer(f.root.token,{operationId:crypto.randomUUID(),sourceAccountId:f.cashA.id,destinationAccountId:f.bankA.id,amount:'500',effectiveOn:cairoIsoDate(),reason:'Original internal transfer',externalReference:'T1'});const totalBefore=BigInt(await balance(f.cashA.id))+BigInt(await balance(f.bankA.id));await c.correctTransfer(f.root.token,transfer.id,{operationId:crypto.randomUUID(),effectiveOn:cairoIsoDate(),reason:'Correct internal transfer amount',replacement:{sourceAccountId:f.cashA.id,destinationAccountId:f.bankA.id,amount:'300',externalReference:'T2'}});expect(BigInt(await balance(f.cashA.id))+BigInt(await balance(f.bankA.id))).toBe(totalBefore);expect((await c.corrections(f.root.token,{})).map(x=>x.targetKind)).toEqual(expect.arrayContaining(['EXPENSE','TRANSFER']));
  for(const table of ['financial_corrections','expense_corrections','transfer_corrections'])await expect(f.database.pool.query(`delete from ${table}`)).rejects.toThrow();
 });
});
