import { afterEach,describe,expect,it } from 'vitest';
import { cairoIsoDate } from '@nursery/domain';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';
import { defaultLimitsInput } from '../helpers/licensing.js';

describe('Phase 19 employee financials and payroll on PostgreSQL',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;
 afterEach(async()=>{await f?.close();});
 const month=()=>cairoIsoDate().slice(0,7);
 const previousMonth=()=>{const [year,value]=month().split('-').map(Number);const date=new Date(Date.UTC(year,value-2,1));return date.toISOString().slice(0,7);};
 const nextMonth=()=>{const [year,value]=month().split('-').map(Number);const date=new Date(Date.UTC(year,value,1));return date.toISOString().slice(0,7);};
 async function setup() {
  f=await financeFixture();const funded=await f.treasuryAccount(`PAY-${crypto.randomUUID().slice(0,8)}`,f.a.id,'CASH','2000000');
  async function profile(code:string,salary='500000',start=month(),branchId=f.a.id,accountId=funded.id,loginUsername:string|null=null) {
   return f.app.payroll.createProfile(f.root.token,{operationId:crypto.randomUUID(),employeeCode:code,fullName:`Employee ${code}`,basicSalary:salary,effectiveMonth:start,payingBranchId:branchId,payingAccountId:accountId,loginUsername});
  }
  async function period(employeeId:string,target=month()) {return f.app.payroll.prepare(f.root.token,{operationId:crypto.randomUUID(),employeeId,month:target});}
  return {funded,profile,period};
 }
 it('A26: 5,000 salary minus 1,000 advance and 300 deduction pays 3,700 once and reports 4,700 cash',async()=>{
  const x=await setup(),employee=await x.profile('A26'),period=await x.period(employee.id);
  await f.app.payroll.advance(f.root.token,period.id,{operationId:crypto.randomUUID(),amount:'100000',paidOn:cairoIsoDate(),reason:'Authorized advance',externalReference:'ADV-A26'});
  await f.app.payroll.adjust(f.root.token,period.id,{operationId:crypto.randomUUID(),kind:'DEDUCTION',amount:'30000',reason:'Authorized deduction'});
  const operationId=crypto.randomUUID(),input={operationId,amount:'370000',settledOn:cairoIsoDate(),reason:'Full monthly salary remainder',externalReference:'PAY-A26'};
  const first=await f.app.payroll.settle(f.root.token,period.id,input),retry=await f.app.payroll.settle(f.root.token,period.id,input);expect(first).toEqual(retry);expect(first).toMatchObject({amount:'370000',noCash:false});
  const receipt=await f.app.payroll.receiptData(f.root.token,period.id);expect(receipt).toMatchObject({basicSalary:'500000',deductions:'30000',advances:'100000',finalPaid:'370000',totalCashOutflow:'470000'});
  await expect(f.app.payroll.adjust(f.root.token,period.id,{operationId:crypto.randomUUID(),kind:'ADDITION',amount:'1',reason:'Settled month must stay fixed'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
  expect((await f.database.pool.query("select (-sum(amount))::text as outflow,count(*)::int as count from treasury_movements where kind in ('PAYROLL_ADVANCE','PAYROLL_SETTLEMENT')")).rows[0]).toEqual({outflow:'470000',count:2});
  expect((await f.app.spending.list(f.root.token,{})).totalPaid).toBe('0');expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('A27: concurrent advance and deduction lock one monthly cap and cannot jointly exceed base salary',async()=>{
  const x=await setup(),employee=await x.profile('A27'),period=await x.period(employee.id);await f.app.payroll.adjust(f.root.token,period.id,{operationId:crypto.randomUUID(),kind:'ADDITION',amount:'1000000',reason:'Bonus does not raise the base-salary cap'});
  const first=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.manage','payroll.pay']),second=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.manage','payroll.pay']);
  const results=await Promise.allSettled([
   f.app.payroll.advance(first.token,period.id,{operationId:crypto.randomUUID(),amount:'250000',paidOn:cairoIsoDate(),reason:'Concurrent advance',externalReference:''}),
   f.app.payroll.adjust(second.token,period.id,{operationId:crypto.randomUUID(),kind:'PENALTY',amount:'300000',reason:'Concurrent penalty'})
  ]);
  expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);
  const detail=await f.app.payroll.period(f.root.token,period.id);expect(BigInt(detail.period.deductions)+BigInt(detail.period.advances)).toBeLessThanOrEqual(500000n);expect(BigInt(detail.period.remaining)).toBeGreaterThanOrEqual(0n);expect(await reconcileFinance(f.database)).toEqual([]);
  const secondPeriod=await x.period((await x.profile('ADJUST-RACE')).id);
  const adjustments=await Promise.allSettled([first,second].map(actor=>f.app.payroll.adjust(actor.token,secondPeriod.id,{operationId:crypto.randomUUID(),kind:'DEDUCTION',amount:'300000',reason:'Independent actors race monthly cap'})));expect(adjustments.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await f.app.payroll.period(f.root.token,secondPeriod.id)).period.deductions).toBe('300000');
 });
 it('A28: repeated and concurrent payout creates one settlement while an older unpaid month stays separate',async()=>{
  const x=await setup(),employee=await x.profile('A28','500000',previousMonth()),oldPeriod=await x.period(employee.id,previousMonth()),current=await x.period(employee.id);
  const input={operationId:crypto.randomUUID(),amount:'500000',settledOn:cairoIsoDate(),reason:'One full final payout',externalReference:''};const sameKey=await Promise.all([f.app.payroll.settle(f.root.token,current.id,input),f.app.payroll.settle(f.root.token,current.id,input)]);expect(sameKey[0]).toEqual(sameKey[1]);
  const concurrent=await Promise.allSettled([f.app.payroll.settle(f.root.token,current.id,{...input,operationId:crypto.randomUUID()}),f.app.payroll.settle(f.root.token,current.id,{...input,operationId:crypto.randomUUID()})]);expect(concurrent.every(r=>r.status==='rejected')).toBe(true);
  expect((await f.database.pool.query('select count(*)::int as count from payroll_final_settlements where period_id=$1',[current.id])).rows[0].count).toBe(1);
  const history=await f.app.payroll.employee(f.root.token,employee.id);expect(history.periods.find(p=>p.periodId===oldPeriod.id)?.state).toBe('UNPAID');expect(history.periods.find(p=>p.periodId===current.id)?.state).toBe('SETTLED');expect(await reconcileFinance(f.database)).toEqual([]);
  await expect(f.app.payroll.adjust(f.root.token,oldPeriod.id,{operationId:crypto.randomUUID(),kind:'DEDUCTION',amount:'1',reason:'Old month cutoff'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
  const first=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.pay']),second=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.pay']);const oldRace=await Promise.allSettled([first,second].map(actor=>f.app.payroll.settle(actor.token,oldPeriod.id,{...input,operationId:crypto.randomUUID()})));expect(oldRace.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await f.app.payroll.period(f.root.token,oldPeriod.id)).period.state).toBe('SETTLED');expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('rolls back source, movement, audit and operation on posting failure, then retries the same key',async()=>{
  const x=await setup(),period=await x.period((await x.profile('ROLLBACK')).id),input={operationId:crypto.randomUUID(),amount:'100000',paidOn:cairoIsoDate(),reason:'Paid advance rollback test',externalReference:''};
  const tables=['payroll_advances','payroll_final_settlements','treasury_movements','financial_audit_events','financial_operations'];const counts=()=>Promise.all(tables.map(async table=>(await f.database.pool.query(`select count(*)::int n from ${table}`)).rows[0].n));const before=await counts();
  await f.database.pool.query("create function fail_payroll_test() returns trigger language plpgsql as $$ begin if new.kind in ('PAYROLL_ADVANCE','PAYROLL_SETTLEMENT') then raise exception 'simulated payroll posting failure'; end if; return new; end $$; create trigger payroll_test_fail before insert on treasury_movements for each row execute function fail_payroll_test()");
  try {await expect(f.app.payroll.advance(f.root.token,period.id,input)).rejects.toThrow('simulated payroll posting failure');await expect(f.app.payroll.settle(f.root.token,period.id,{operationId:crypto.randomUUID(),amount:'500000',settledOn:cairoIsoDate(),reason:'Final rollback test',externalReference:''})).rejects.toThrow('simulated payroll posting failure');expect(await counts()).toEqual(before);expect(await f.core.operationStatus(f.root.token,input.operationId)).toEqual({status:'NOT_FOUND'});}finally {await f.database.pool.query('drop trigger payroll_test_fail on treasury_movements; drop function fail_payroll_test()');}
  await f.app.payroll.advance(f.root.token,period.id,input);expect((await f.app.payroll.period(f.root.token,period.id)).period.advances).toBe('100000');expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('rejects partial/stale payouts, insufficient funds and closed cash dates without partial records',async()=>{
  const x=await setup(),period=await x.period((await x.profile('GUARDS')).id),input={operationId:crypto.randomUUID(),amount:'499999',settledOn:cairoIsoDate(),reason:'No partial final salary',externalReference:''};await expect(f.app.payroll.settle(f.root.token,period.id,input)).rejects.toMatchObject({code:'STALE_VERSION'});
  const emptyPeriod=await x.period((await x.profile('UNFUNDED','500000',month(),f.a.id,f.cashA.id)).id);await expect(f.app.payroll.settle(f.root.token,emptyPeriod.id,{...input,amount:'500000'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
  await f.app.closing.count(f.root.token,{operationId:crypto.randomUUID(),accountId:x.funded.id,on:cairoIsoDate(),countedAmount:'2000000',expectedRevision:0,reason:'Explicit physical closing'});
  await expect(f.app.payroll.advance(f.root.token,period.id,{operationId:crypto.randomUUID(),amount:'1',paidOn:cairoIsoDate(),reason:'Closed date rejects cash',externalReference:''})).rejects.toMatchObject({messageKey:'closing.closedDate'});await expect(f.app.payroll.settle(f.root.token,period.id,{...input,amount:'500000'})).rejects.toMatchObject({messageKey:'closing.closedDate'});expect((await f.database.pool.query('select count(*)::int n from payroll_final_settlements')).rows[0].n).toBe(0);expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('A01: no classroom/guardian fallback; scope revocation denies detail, receipt and payout replay',async()=>{
  const x=await setup(),employee=await x.profile('REVOKE'),period=await x.period(employee.id),actor=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.pay']),input={operationId:crypto.randomUUID(),amount:'500000',settledOn:cairoIsoDate(),reason:'Scoped final salary',externalReference:''};await f.app.payroll.settle(actor.token,period.id,input);
  const teacher=await f.financeStaff([f.a.id],[f.classes[0].id],'CLASSROOM',['finance.read','payroll.manage','payroll.pay']);await expect(f.app.payroll.options(teacher.token)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.app.payroll.period(teacher.token,period.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  const child=await f.child('PAY-GUARDIAN'),parent=await f.parent(child.guardianIds[0],'parent-pay-guardian',child.credentials[0].temporaryPassword);await expect(f.app.payroll.roster(parent.token,{month:month()})).rejects.toMatchObject({code:'FORBIDDEN'});
  const role=await f.app.organization.save(f.root.token,'roles',{name:'Revoked payroll branch',capabilities:['finance.read','payroll.pay']});await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:2,roleIds:[role.id],branchIds:[f.b.id],classroomIds:[],scopeMode:'BRANCH'});
  for(const read of [()=>f.app.payroll.period(actor.token,period.id),()=>f.app.payroll.employee(actor.token,employee.id),()=>f.app.payroll.receiptData(actor.token,period.id),()=>f.core.operationStatus(actor.token,input.operationId),()=>f.app.payroll.settle(actor.token,period.id,input)])await expect(read()).rejects.toMatchObject({code:'FORBIDDEN'});
 });
 it('A05: login quota failure rolls back the entire profile and credential replay is redacted',async()=>{
  const x=await setup(),context=await f.licensing.context(f.root.token);await f.licensing.saveLimits(f.root.token,{expectedVersion:context.limits!.version,value:{...defaultLimitsInput,parentCapacity:20,employeeCapacity:1}});
  const input={operationId:crypto.randomUUID(),employeeCode:'LAST-SEAT',fullName:'Last payroll login',basicSalary:'500000',effectiveMonth:month(),payingBranchId:f.a.id,payingAccountId:x.funded.id,loginUsername:'payroll-last-seat'};const first=await f.app.payroll.createProfile(f.root.token,input),replay=await f.app.payroll.createProfile(f.root.token,input);expect(first.temporaryPassword).toBeTruthy();expect(replay).toEqual({...first,temporaryPassword:null});expect((await f.core.operationStatus(f.root.token,input.operationId)).result).toEqual(replay);
  await expect(x.profile('NO-SEAT','500000',month(),f.a.id,x.funded.id,'payroll-no-seat')).rejects.toMatchObject({messageKey:'licensing.capacityExceeded'});expect((await f.database.pool.query("select count(*)::int n from accounts where username_normalized='payroll-no-seat'")).rows[0].n).toBe(0);expect((await f.database.pool.query("select count(*)::int n from employee_profiles where employee_code='NO-SEAT'")).rows[0].n).toBe(0);expect((await f.database.pool.query('select count(*)::int n from salary_history')).rows[0].n).toBe(1);expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('creates an optional login later through quota service without changing salary or monthly history',async()=>{
  const x=await setup(),employee=await x.profile('LATER-LOGIN'),period=await x.period(employee.id),input={operationId:crypto.randomUUID(),username:'later-payroll-login',reason:'Employee now needs authorized app access'};
  const staff=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.manage']);await expect(f.app.payroll.provisionLogin(staff.token,employee.id,input)).rejects.toMatchObject({code:'FORBIDDEN'});
  const [first,replay]=await Promise.all([f.app.payroll.provisionLogin(f.root.token,employee.id,input),f.app.payroll.provisionLogin(f.root.token,employee.id,input)]);expect(first.temporaryPassword).toBeTruthy();expect(replay).toEqual({...first,temporaryPassword:null});expect((await f.licensing.context(f.root.token)).employeeReserved).toBe(1);
  expect((await f.app.payroll.employee(f.root.token,employee.id)).employee.accountId).toBe(first.accountId);expect((await f.app.payroll.period(f.root.token,period.id)).period).toMatchObject({basicSalary:'500000',remaining:'500000',accountIdSnapshot:x.funded.id,accountId:first.accountId});await expect(f.app.payroll.provisionLogin(f.root.token,employee.id,{...input,operationId:crypto.randomUUID(),username:'duplicate-payroll-login'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});expect((await f.licensing.context(f.root.token)).employeeReserved).toBe(1);expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('records an explicit zero-payable settlement with no zero-valued treasury movement',async()=>{
  const x=await setup(),employee=await x.profile('ZERO'),period=await x.period(employee.id);await f.app.payroll.advance(f.root.token,period.id,{operationId:crypto.randomUUID(),amount:'500000',paidOn:cairoIsoDate(),reason:'Full salary advance',externalReference:''});
  const before=(await f.database.pool.query('select count(*)::int as count from treasury_movements')).rows[0].count;const settled=await f.app.payroll.settle(f.root.token,period.id,{operationId:crypto.randomUUID(),amount:'0',settledOn:cairoIsoDate(),reason:'Explicit no-cash close',externalReference:''});expect(settled).toMatchObject({amount:'0',noCash:true});
  expect((await f.database.pool.query('select count(*)::int as count from treasury_movements')).rows[0].count).toBe(before);expect((await f.app.payroll.receiptData(f.root.token,period.id)).noCash).toBe(true);expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('database defenses reject wrong salary snapshots, unattached cash sources and wrong cash method',async()=>{
  const x=await setup(),employee=await x.profile('SQL-GUARDS'),period=await x.period(employee.id);
  const rawAdvance=(method:string,post:boolean)=>f.database.transaction(async tx=>{const operationId=crypto.randomUUID(),id=crypto.randomUUID();await tx.query("insert into financial_operations(actor_id,operation_id,request_hash,action,result,resources) values($1,$2,'sql-test','SQL_TEST','{}','[]')",[f.root.account.id,operationId]);await tx.query("insert into payroll_advances(id,period_id,branch_id,account_id,amount,paid_on,method,reason,external_reference,actor_id,operation_id) values($1,$2,$3,$4,1,$5,$6,'SQL defense test','',$7,$8)",[id,period.id,f.a.id,x.funded.id,cairoIsoDate(),method,f.root.account.id,operationId]);if(post)await tx.query("insert into treasury_movements(id,account_id,kind,payroll_advance_id,amount,effective_on,reason,actor_id) values($1,$2,'PAYROLL_ADVANCE',$3,-1,$4,'SQL defense test',$5)",[crypto.randomUUID(),x.funded.id,id,cairoIsoDate(),f.root.account.id]);});
  await expect(rawAdvance('CASH',false)).rejects.toThrow('Invalid payroll advance source');await expect(rawAdvance('BANK',true)).rejects.toThrow('Invalid payroll advance source');expect((await f.app.payroll.period(f.root.token,period.id)).period.advances).toBe('0');
  const other=await x.profile('SQL-SNAPSHOT');await expect(f.database.transaction(async tx=>{const operationId=crypto.randomUUID();await tx.query("insert into financial_operations(actor_id,operation_id,request_hash,action,result,resources) values($1,$2,'sql-test','SQL_TEST','{}','[]')",[f.root.account.id,operationId]);await tx.query("insert into payroll_periods(id,employee_id,month,employee_code,employee_name,paying_branch_id,paying_account_id,basic_salary,actor_id,operation_id) values($1,$2,$3,'SQL-SNAPSHOT','Employee SQL-SNAPSHOT',$4,$5,499999,$6,$7)",[crypto.randomUUID(),other.id,`${month()}-01`,f.a.id,x.funded.id,f.root.account.id,operationId]);})).rejects.toThrow('Invalid payroll salary snapshot');
  await expect(f.database.pool.query('delete from payroll_periods where id=$1',[period.id])).rejects.toThrow();expect(await reconcileFinance(f.database)).toEqual([]);
 });
 it('D27: a future salary/branch change preserves the existing monthly snapshot',async()=>{
  const x=await setup(),employee=await x.profile('D27'),period=await x.period(employee.id),other=await f.treasuryAccount(`FUT-${crypto.randomUUID().slice(0,8)}`,f.b.id,'BANK','1000000');
  await expect(f.app.payroll.changeSalary(f.root.token,employee.id,{operationId:crypto.randomUUID(),effectiveMonth:month(),basicSalary:'600000',payingBranchId:f.b.id,payingAccountId:other.id,reason:'Current month is already in effect'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});
  await f.app.payroll.changeSalary(f.root.token,employee.id,{operationId:crypto.randomUUID(),effectiveMonth:nextMonth(),basicSalary:'600000',payingBranchId:f.b.id,payingAccountId:other.id,reason:'Authorized future payroll attribution'});
  const current=await f.app.payroll.period(f.root.token,period.id),history=await f.app.payroll.employee(f.root.token,employee.id);expect(current.period).toMatchObject({basicSalary:'500000',branchId:f.a.id,accountIdSnapshot:x.funded.id});expect(history.salaryHistory.at(-1)).toMatchObject({effectiveMonth:nextMonth(),basicSalary:'600000',branchId:f.b.id,accountId:other.id});
 });
 it('A01/A05: branch payroll scope is exact and profile deactivation never releases a login seat',async()=>{
  const x=await setup(),profileOnly=await x.profile('PROFILE'),withLogin=await x.profile('LOGIN','500000',month(),f.a.id,x.funded.id,`payroll-${crypto.randomUUID()}`),otherAccount=await f.treasuryAccount(`PAY-B-${crypto.randomUUID().slice(0,8)}`,f.b.id,'CASH','1000000'),foreign=await x.profile('FOREIGN','500000',month(),f.b.id,otherAccount.id),foreignPeriod=await x.period(foreign.id);
  expect(profileOnly.accountId).toBeNull();expect(withLogin.accountId).toBeTruthy();expect(withLogin.temporaryPassword).toBeTruthy();expect((await f.database.pool.query("select count(*)::int as count from seat_reservations where kind='EMPLOYEE' and released_at is null")).rows[0].count).toBe(1);
  const staff=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','payroll.manage','payroll.pay']);const roster=await f.app.payroll.roster(staff.token,{month:month()});expect(roster.items.map(i=>i.employeeCode).sort()).toEqual(['LOGIN','PROFILE']);await expect(f.app.payroll.roster(staff.token,{month:month(),branchId:f.b.id})).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.app.payroll.period(staff.token,foreignPeriod.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.app.payroll.profileStatus(f.root.token,withLogin.id,{operationId:crypto.randomUUID(),active:false,reason:'Financial profile no longer active'});expect((await f.database.pool.query("select count(*)::int as count from seat_reservations where kind='EMPLOYEE' and released_at is null")).rows[0].count).toBe(1);expect((await f.database.pool.query('select status from accounts where id=$1',[withLogin.accountId])).rows[0].status).toBe('ACTIVE');expect(await reconcileFinance(f.database)).toEqual([]);
  expect((await f.database.pool.query('select details::text from financial_audit_events where action=\'EMPLOYEE_PROFILE_CREATE\' and details::text like \'%LOGIN%\'')).rows[0].details).not.toContain(withLogin.temporaryPassword);
  const payrollModule=(await f.licensing.modules(f.root.token)).find(x=>x.moduleKey==='PAYROLL')!;await f.licensing.saveModuleSetting(f.root.token,'PAYROLL',{expectedVersion:payrollModule.version,enabled:false,reason:'Module history acceptance'});expect((await f.app.payroll.roster(staff.token,{month:month()})).items.length).toBe(2);await expect(x.profile('BLOCKED')).rejects.toMatchObject({code:'MODULE_DISABLED'});
 });
});
