import { afterEach,describe,expect,it } from 'vitest';
import { mkdir,writeFile,readdir,stat } from 'node:fs/promises';
import { resolve,join } from 'node:path';
import ExcelJS from 'exceljs';
import { PDFDocument,PDFName } from 'pdf-lib';
import { cairoIsoDate } from '@nursery/domain';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';
describe('real report export content, lifecycle and current authorization',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;afterEach(async()=>{if(f){expect(await reconcileFinance(f.database)).toEqual([]);await f.close();}});
 const input=(kind='CHILDREN',format='XLSX',locale='en')=>({operationId:crypto.randomUUID(),kind,format,locale,from:cairoIsoDate(),to:cairoIsoDate()});
 it('creator-only downloads, pending status, permission/scope revocation and physical expiry cleanup',async()=>{
  f=await financeFixture();await f.child('PRIVATE');const actor=await f.financeStaff([f.a.id],[],'BRANCH',['children.read']),other=await f.financeStaff([f.a.id],[],'BRANCH',['children.read']),job=await f.app.reports.createExport(actor.token,input());
  expect(await f.app.reports.download(actor.token,job.id)).toEqual({pending:true});await expect(f.app.reports.status(other.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.app.reports.download(other.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  await Promise.all([f.app.reports.runBatch(f.database),f.app.reports.runBatch(f.database)]);expect((await f.app.reports.status(actor.token,job.id)).status).toBe('READY');expect(await readdir(join(f.config.privateFilesDir,'report-exports'))).toHaveLength(1);
  const files=await readdir(join(f.config.privateFilesDir,'report-exports'));expect((await stat(join(f.config.privateFilesDir,'report-exports',files[0]))).size).toBeGreaterThan(1000);
  const role=await f.app.organization.save(f.root.token,'roles',{name:'Moved report reader',capabilities:['children.read']});await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:2,roleIds:[role.id],branchIds:[f.b.id],classroomIds:[],scopeMode:'BRANCH'});await expect(f.app.reports.download(actor.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:3,roleIds:[role.id],branchIds:[f.a.id],classroomIds:[],scopeMode:'BRANCH'});
  await f.database.pool.query("update report_exports set expires_at=now()-interval '1 second' where id=$1",[job.id]);expect((await f.app.reports.status(actor.token,job.id)).status).toBe('EXPIRED');await expect(f.app.reports.download(actor.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});expect(await f.app.reports.cleanupBatch(f.database)).toEqual({expired:1});expect(await readdir(join(f.config.privateFilesDir,'report-exports'))).toEqual([]);
  const denied=await f.app.reports.createExport(actor.token,input());await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:4,roleIds:[],branchIds:[],classroomIds:[],scopeMode:'BRANCH'});await f.app.reports.runBatch(f.database);expect((await f.database.pool.query('select status,error_code from report_exports where id=$1',[denied.id])).rows[0]).toEqual({status:'FAILED',error_code:'auth.forbidden'});
 },60000);
 it('real English and Arabic PDF/XLSX contain complete scoped monetary rows, dates, branding and safe cells',async()=>{
  f=await financeFixture();const child=await f.child('CONTENT'),other=await f.child('FOREIGN',f.b.id);await f.database.pool.query('update children set full_name=$2 where id=$1',[child.childId,'=HYPERLINK("https://invalid") طفل عربي']);const a=await f.charge(child.childId,'12345'),b=await f.charge(other.childId,'99999');await f.payments.collect(f.root.token,f.collect(a.installmentIds[0],'12345'));await f.payments.collect(f.root.token,f.collect(b.installmentIds[0],'99999',f.b.id,f.cashB.id));
  const actor=await f.financeStaff([f.a.id],[],'BRANCH',['finance.read','children.read']);const directory=resolve('output/phase20');await mkdir(directory,{recursive:true});
  await expect(f.app.reports.createExport(actor.token,{...input(),classroomId:f.classes[2].id})).rejects.toMatchObject({code:'FORBIDDEN'});
  await expect(f.app.reports.report(actor.token,{kind:'CHILDREN',from:cairoIsoDate(),to:cairoIsoDate(),classroomId:f.classes[2].id})).rejects.toMatchObject({code:'FORBIDDEN'});
  for(const locale of ['en','ar-EG'])for(const format of ['PDF','XLSX']){
   const job=await f.app.reports.createExport(actor.token,{...input('COLLECTIONS',format,locale),branchId:f.a.id});expect(await f.app.reports.runBatch(f.database)).toEqual({processed:1});const file=await f.app.reports.download(actor.token,job.id);if(file.pending)throw new Error('Generation incomplete');await writeFile(join(directory,`collections-${locale}.${format.toLowerCase()}`),file.bytes);
   if(format==='XLSX') {const book=new ExcelJS.Workbook();await book.xlsx.load(file.bytes as never);expect(book.worksheets).toHaveLength(1);const s=book.worksheets[0];expect(s.name).toBe(locale==='en'?'Report':'التقرير');expect(s.rowCount).toBe(8);expect(s.getCell('A7').value).toBe(locale==='en'?'Date':'التاريخ');expect(s.getCell('D5').value).toBe(123.45);expect(s.getCell('D8').value).toBe(123.45);expect(s.getCell('E8').value).toBe("'12345");expect(s.getCell('A8').value).toEqual(new Date(`${cairoIsoDate()}T00:00:00Z`));expect(String(s.getCell('H8').value)).toContain('طفل عربي');expect(s.getCell('F8').value).toBe('A');expect(s.views[0].rightToLeft).toBe(locale==='ar-EG');s.eachRow(row=>row.eachCell(cell=>{expect(cell.type).not.toBe(ExcelJS.ValueType.Formula);expect(JSON.stringify(cell.value)).not.toContain('FOREIGN');}));}
   else {const pdf=await PDFDocument.load(file.bytes);expect(pdf.getPageCount()).toBeGreaterThan(0);for(const p of pdf.getPages()){expect(p.getWidth()).toBeCloseTo(595.276,2);expect(p.getHeight()).toBeCloseTo(841.89,2);expect(p.node.Resources()?.get(PDFName.of('XObject'))).toBeDefined();}expect(JSON.parse(pdf.getSubject()!)).toMatchObject({kind:'COLLECTIONS',rows:1,totals:{amount:'12345'},branch:f.a.id,locale});expect(pdf.getTitle()).toContain(locale==='en'?'Collections':'التحصيلات');}
  }
  const childExport=await f.app.reports.createExport(actor.token,input());await f.app.reports.runBatch(f.database);const file=await f.app.reports.download(actor.token,childExport.id);if(file.pending)throw new Error('Generation incomplete');const book=new ExcelJS.Workbook();await book.xlsx.load(file.bytes as never);expect(book.worksheets[0].getCell('B8').value).toBe("'=HYPERLINK(\"https://invalid\") طفل عربي");
 },60000);
 it('fails row-cap exports explicitly without truncation or files and measures real bounded report plans',async()=>{
  f=await financeFixture();await f.database.pool.query("insert into children(id,code,full_name,birth_date,branch_id,classroom_id) select gen_random_uuid(),'PERF_'||n,'Synthetic child '||n,'2022-01-01',$1,$2 from generate_series(1,10001) n",[f.a.id,f.classes[0].id]);await f.database.pool.query('analyze children');
  const page=await f.app.reports.report(f.root.token,{kind:'CHILDREN',from:cairoIsoDate(),to:cairoIsoDate(),limit:20,offset:0});expect(page.totalCount).toBe(10001);expect(page.rows).toHaveLength(20);
  const job=await f.app.reports.createExport(f.root.token,input());await f.app.reports.runBatch(f.database);expect(await f.app.reports.status(f.root.token,job.id)).toMatchObject({status:'FAILED',error:'reports.tooLarge',rowCount:null});await expect(f.app.reports.download(f.root.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  await f.database.pool.query("insert into children(id,code,full_name,birth_date,branch_id,classroom_id) select gen_random_uuid(),'SMALL_'||n,'Scoped synthetic child '||n,'2022-01-01',$1,$2 from generate_series(1,30) n",[f.b.id,f.classes[2].id]);await f.database.pool.query('analyze children');
  const actor=await f.financeStaff([f.b.id],[],'BRANCH',['children.read','finance.read']);const plans:Record<string,unknown>={fixture:{children:10031,selectedBranchChildren:30,branches:2,classrooms:3}};
  for(const kind of ['CHILDREN','CAPACITY','CASH_RESULT','OUTSTANDING','PAYROLL'] as const)plans[kind]=await f.children.withPolicy(actor.token,(tx,p)=>f.app.reports.engine.explain(tx,p,{kind,from:cairoIsoDate(),to:cairoIsoDate(),branchId:f.b.id,limit:20,offset:0}));
  expect(JSON.stringify(plans.CHILDREN)).toContain('children_scope');const directory=resolve('output/phase20');await mkdir(directory,{recursive:true});await writeFile(join(directory,'query-plans.json'),JSON.stringify(plans,null,2));
 });
 it('renders complete multipage Arabic and English reports with long child text and bounded A4 content',async()=>{
  f=await financeFixture();await f.database.pool.query("insert into children(id,code,full_name,birth_date,branch_id,classroom_id) select gen_random_uuid(),'LONG_'||n,$3||' '||n,'2022-01-01',$1,$2 from generate_series(1,30) n",[f.a.id,f.classes[0].id,'طفل عربي للاختبار طويل الاسم — English long name '.repeat(3)]);
  const directory=resolve('output/phase20');await mkdir(directory,{recursive:true});
  for(const locale of ['en','ar-EG']) {const job=await f.app.reports.createExport(f.root.token,input('CHILDREN','PDF',locale));await f.app.reports.runBatch(f.database);const file=await f.app.reports.download(f.root.token,job.id);if(file.pending)throw new Error('Generation incomplete');const pdf=await PDFDocument.load(file.bytes);expect(pdf.getPageCount()).toBeGreaterThan(2);let images=0;for(const p of pdf.getPages()){expect(p.getWidth()).toBeCloseTo(595.276,2);expect(p.getHeight()).toBeCloseTo(841.89,2);const resources=p.node.Resources()!.lookup(PDFName.of('XObject')) as {keys():unknown[]};images+=resources.keys().length;}expect(images).toBeGreaterThanOrEqual(30*5);expect(JSON.parse(pdf.getSubject()!).rows).toBe(30);await writeFile(join(directory,`long-children-${locale}.pdf`),file.bytes);}
 },60000);
 it('saved scope cannot widen, classroom narrowing/current placement is rechecked, and private HTTP paths never expose files',async()=>{
  f=await financeFixture();const a=await f.child('SCOPE-A');await f.child('SCOPE-B',f.b.id);const actor=await f.financeStaff([f.a.id],[],'BRANCH',['children.read']),job=await f.app.reports.createExport(actor.token,input());const role=await f.app.organization.save(f.root.token,'roles',{name:'Expanded reader',capabilities:['children.read']});await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:2,roleIds:[role.id],branchIds:[f.a.id,f.b.id],classroomIds:[],scopeMode:'BRANCH'});
  await f.app.reports.runBatch(f.database);const file=await f.app.reports.download(actor.token,job.id);if(file.pending)throw new Error('Incomplete');const book=new ExcelJS.Workbook();await book.xlsx.load(file.bytes as never);expect(book.worksheets[0].rowCount).toBe(8);expect(book.worksheets[0].getCell('B8').value).toBe('Child SCOPE-A');await expect(f.app.reports.download(f.root.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  const cookie={cookie:`__Host-nursery_session=${actor.token}`},response=await f.app.inject({method:'GET',url:`/api/v1/reports/exports/${job.id}/download`,headers:cookie});expect(response.statusCode).toBe(200);expect(response.headers['cache-control']).toBe('private, no-store');expect(response.headers['content-disposition']).toContain('attachment;');expect(JSON.stringify(await f.app.reports.status(actor.token,job.id))).not.toMatch(/storage_key|sha256|scope|resources/);
  expect((await f.app.inject({method:'GET',url:`/api/v1/reports/exports/${job.id}/download`})).statusCode).toBe(401);expect((await f.app.inject({method:'GET',url:'/api/v1/reports/exports/%2e%2e%2fsecret/download',headers:cookie})).statusCode).toBe(400);const key=(await f.database.pool.query('select storage_key from report_exports where id=$1',[job.id])).rows[0].storage_key;expect((await f.app.inject({method:'GET',url:`/report-exports/${key}.blob`,headers:cookie})).statusCode).toBe(404);
  await f.app.organization.assign(f.root.token,actor.id,{expectedVersion:3,roleIds:[role.id],branchIds:[f.a.id],classroomIds:[f.classes[0].id],scopeMode:'CLASSROOM'});await expect(f.app.reports.download(actor.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
  const fresh=await f.app.reports.createExport(actor.token,input());await f.app.reports.runBatch(f.database);await f.children.moveClassroom(f.root.token,a.childId,{expectedVersion:1,classroomId:f.classes[1].id,reason:'Authorized placement change'});await expect(f.app.reports.download(actor.token,fresh.id)).rejects.toMatchObject({code:'FORBIDDEN'});
 });
 it('three actual database failures terminate generation without a successful artifact or financial effect',async()=>{
  f=await financeFixture();const job=await f.app.reports.createExport(f.root.token,input());await f.database.pool.query("create function fail_export_commit() returns trigger language plpgsql as $$ begin if new.status='READY' then raise exception 'disposable permanent generation failure'; end if; return new; end $$; create trigger fail_export_commit before update on report_exports for each row execute function fail_export_commit()");
  for(let n=0;n<3;n++){await expect(f.app.reports.runBatch(f.database)).rejects.toThrow('disposable permanent generation failure');await f.database.pool.query('update report_exports set next_attempt_at=now() where id=$1',[job.id]);}
  expect(await f.app.reports.status(f.root.token,job.id)).toMatchObject({status:'FAILED',error:'reports.generationFailed',rowCount:null});expect((await f.database.pool.query('select attempts from report_exports where id=$1',[job.id])).rows[0].attempts).toBe(3);expect(await readdir(join(f.config.privateFilesDir,'report-exports'))).toEqual([]);expect(await f.app.reports.runBatch(f.database)).toEqual({processed:0});await expect(f.app.reports.download(f.root.token,job.id)).rejects.toMatchObject({code:'FORBIDDEN'});
 });
});
