import { it,expect } from 'vitest';
import { PDFDocument } from 'pdf-lib';
import { examsFixture } from '../helpers/exams.js';
import { HomeworkService } from '../../apps/api/src/modules/homework/service.js';
it('operational reports retain zero/label grades, independent exams, missing work, corrected attendance, transport and private incidents/documents',async()=>{
 const f=await examsFixture();try {
  const a=await f.onboard('OP-A'),b=await f.onboard('OP-B'),foreign=await f.onboard('OP-HIDDEN',f.classes[1].id),id=a.childIds[0],other=b.childIds[0],date=f.date(),homework=new HomeworkService(f.children,f.learning,f.date);
  const draft=await f.attendance.classroom(f.root.token,f.classes[0].id,date),status=(outcome:string)=>draft.entries[0].definition.statuses.find(s=>s.outcome===outcome)!.id;
  await f.attendance.publishClassroom(f.root.token,{classroomId:f.classes[0].id,date,operationId:crypto.randomUUID(),entries:[{childId:id,statusId:status('ABSENT'),absenceReason:'Confirmed absence',expectedVersion:0}]});await f.attendance.correct(f.root.token,{childId:id,date,statusId:status('PRESENT'),absenceReason:null,expectedVersion:1,reason:'Verified correction',operationId:crypto.randomUUID()});
  const subject=await f.catalogItem('subjects','Maths'),type=await f.catalogItem('exam_types','Written');
  for(const format of ['NUMERIC','LABEL'] as const){const exam=await f.exams.create(f.root.token,{name:`Independent ${format}`,subjectId:subject.id,typeId:type.id,classroomId:f.classes[0].id,assessedOn:date,gradeFormat:format,maximumMarks:format==='NUMERIC'?10:null,decimalAllowed:false,labelOptions:format==='LABEL'?['جيد','Excellent']:null,operationId:crypto.randomUUID()});const entry=(await f.exams.roster(f.root.token,exam.id)).entries.find(e=>e.childId===id)!;await f.exams.publishResults(f.root.token,{examId:exam.id,operationId:crypto.randomUUID(),entries:[{childId:id,outcome:'RESULT',score:format==='NUMERIC'?0:null,label:format==='LABEL'?'جيد':null,comment:null,expectedVersion:entry.slotRevision}]});}
  const assignment=await homework.publish(f.root.token,{classroomId:f.classes[0].id,title:'Shared homework',instructions:'Real retained content',assignedOn:date,dueOn:date,childIds:[id,other],operationId:crypto.randomUUID()}),slot=(await f.learning.daily(f.root.token,id,date)).slots.find(s=>s.definition.kind==='HOMEWORK')!;
  await homework.publishOutcomes(f.root.token,{assignmentId:assignment.id,date,operationId:crypto.randomUUID(),entries:[{childId:id,statusId:slot.definition.statuses.find(s=>s.outcome==='COMPLETED')!.id,expectedVersion:0}]});
  const bus=await f.app.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:'OP-BUS',name:'Bus',kind:'BUS'}),trip=await f.app.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:'OP-TRIP',name:'Trip',kind:'TRIP'});
  await f.app.transport.subscribe(f.root.token,{operationId:crypto.randomUUID(),childId:id,categoryId:bus.id,periodStart:date,periodEnd:date,amount:'50000',dueOn:date,administrativePermission:true});const activity=await f.app.transport.createActivity(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,categoryId:trip.id,title:'Free visit',details:'Consent stays distinct',eventDate:date,fee:'0',dueOn:date,childIds:[id,other]});await f.app.transport.consent(f.root.token,activity.id,id,{operationId:crypto.randomUUID(),consented:true,reason:'Recorded consent'});
  await f.app.safety.reportIncident(f.root.token,id,{occurredOn:date,occurredTime:'12:30',description:'Private incident description',actionTaken:'Staff reviewed',guardianInformed:true,contactMethod:'CALL',followUp:'Review tomorrow'});
  const pdf=await PDFDocument.create();pdf.addPage();await f.documents.upload(f.root.token,id,{name:'Medical document',expiresOn:date,mimeType:'application/pdf',contentBase64:Buffer.from(await pdf.save()).toString('base64')});
  const actor=await f.learningStaff([f.classes[0].id],['learning.read','transport.read','activities.read','incidents.read','documents.manage','children.read']);const report=(kind:string)=>f.app.reports.report(actor.token,{kind,from:date,to:date});
  const attendance=await report('ATTENDANCE');expect(attendance.rows.find(r=>r.childId===id)?.category).toBe('PRESENT');expect(attendance.rows.find(r=>r.childId===other)?.category).toBe('MISSING');
  const exams=await report('EXAMS');expect(exams.totalCount).toBe(4);expect(exams.rows.find(r=>r.details.format==='NUMERIC'&&r.childId===id)?.details.score).toBe('0.00');expect(exams.rows.find(r=>r.details.format==='LABEL'&&r.childId===id)?.details.gradeLabel).toBe('جيد');expect(exams.rows.filter(r=>r.category==='MISSING')).toHaveLength(2);expect(exams.totals.amount).toBe('0');
  const hw=await report('HOMEWORK');expect(hw.rows.find(r=>r.childId===id)?.category).toBe('COMPLETED');expect(hw.rows.find(r=>r.childId===other)?.category).toBe('PENDING');expect((await report('BUS')).rows[0].details).toMatchObject({paid:'false',permission:'true'});const trips=await report('TRIPS');expect(trips.rows.find(r=>r.childId===id)?.details).toMatchObject({paid:'true',consented:'true'});expect(trips.rows.find(r=>r.childId===other)?.details.consented).toBe('false');expect((await report('INCIDENTS')).rows[0].details.description).toBe('Private incident description');expect((await report('DOCUMENT_EXPIRY')).rows[0].label).toBe('Medical document');expect((await report('CAPACITY')).rows).toHaveLength(1);
  for(const kind of ['ATTENDANCE','EXAMS','HOMEWORK','BUS','TRIPS','INCIDENTS','DOCUMENT_EXPIRY','CHILDREN'])expect((await report(kind)).rows.map(r=>r.childId)).not.toContain(foreign.childIds[0]);await expect(report('PAYROLL')).rejects.toMatchObject({code:'FORBIDDEN'});
 }finally{await f.close();}
},60000);
