import { afterEach,describe,expect,it } from 'vitest';
import { cairoIsoDate } from '@nursery/domain';
import { runReminderBatch } from '@nursery/db';
import { financeFixture,reconcileFinance } from '../helpers/finance.js';

describe('Phase 18 transport and activity finance on PostgreSQL',()=>{
 let f:Awaited<ReturnType<typeof financeFixture>>;
 afterEach(async()=>{if(f){expect(await reconcileFinance(f.database)).toEqual([]);await f.close();}});
 async function setup(code:string){
  f=await financeFixture();await f.database.pool.query('insert into sensitive_grants(account_id,sensitive_financial_edit) values($1,true) on conflict(account_id) do update set sensitive_financial_edit=true',[f.root.account.id]);
  const trip=await f.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:`TRIP-${code}`,name:'Trip',kind:'TRIP'}),child=await f.child(code);
  const activity=await f.app.transport.createActivity(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,categoryId:trip.id,title:'Museum trip',details:'Guided museum visit',eventDate:cairoIsoDate(),fee:'50000',dueOn:cairoIsoDate(),childIds:[child.childId]});
  const row=(await f.database.pool.query<{installment_id:string}>('select installment_id from activity_children where activity_id=$1',[activity.id])).rows[0];const payment=await f.payments.collect(f.root.token,f.collect(row.installment_id,'50000'));return {activity,child,row,payment};
 }
 async function setModule(key:'TRANSPORT'|'ACTIVITIES'|'FINANCE',enabled:boolean){const row=(await f.licensing.modules(f.root.token)).find(x=>x.moduleKey===key)!;return f.licensing.saveModuleSetting(f.root.token,key,{expectedVersion:row.version,enabled,reason:'Phase 18 acceptance fixture',...(key==='FINANCE'&&enabled?{catchupAcknowledged:true}:{})});}
 it('paid cancellation atomically creates one source-linked TRIP credit and retry is idempotent',async()=>{
  const x=await setup('TRIP-CANCEL'),input={operationId:crypto.randomUUID(),reason:'Trip cancelled by venue'};const cash=(await f.database.pool.query('select balance::text from treasury_balances where id=$1',[f.cashA.id])).rows[0].balance;
  const result=await f.app.transport.cancel(f.root.token,x.activity.id,input);expect(await f.app.transport.cancel(f.root.token,x.activity.id,input)).toEqual(result);
  expect((await f.database.pool.query('select status from activities where id=$1',[x.activity.id])).rows[0].status).toBe('CANCELLED');expect((await f.database.pool.query('select count(*)::int n from activity_cancellations where activity_id=$1',[x.activity.id])).rows[0].n).toBe(1);
  const credit=(await f.database.pool.query('select c.id,c.amount::text,o.receipt_id,fc.target_kind from credits c join credit_origins o on o.credit_id=c.id join financial_corrections fc on fc.id=c.correction_id where fc.operation_id=$1',[input.operationId])).rows[0];expect(credit).toMatchObject({amount:'50000',receipt_id:x.payment.receiptIds[0],target_kind:'TRIP'});expect((await f.app.corrections.corrections(f.root.token,{})).some(c=>c.targetKind==='TRIP'&&c.reason===input.reason)).toBe(true);expect((await f.database.pool.query('select balance::text from treasury_balances where id=$1',[f.cashA.id])).rows[0].balance).toBe(cash);
 });
 it('injected credit failure rolls back cancellation history/status and every correction',async()=>{
  const x=await setup('TRIP-ROLLBACK'),operationId=crypto.randomUUID();await f.database.pool.query("create function fail_trip_credit() returns trigger language plpgsql as $$ begin raise exception 'trip credit failure'; end $$; create trigger fail_trip_credit before insert on credits for each row execute function fail_trip_credit()");
  await expect(f.app.transport.cancel(f.root.token,x.activity.id,{operationId,reason:'Rollback fixture'})).rejects.toThrow('trip credit failure');await f.database.pool.query('drop trigger fail_trip_credit on credits; drop function fail_trip_credit()');
  expect((await f.database.pool.query('select status from activities where id=$1',[x.activity.id])).rows[0].status).toBe('ACTIVE');expect((await f.database.pool.query('select count(*)::int n from activity_cancellations where activity_id=$1',[x.activity.id])).rows[0].n).toBe(0);expect((await f.database.pool.query('select count(*)::int n from financial_corrections where operation_id=$1',[operationId])).rows[0].n).toBe(0);
 });
 it('concurrent distinct cancellations serialize and cannot duplicate credits/history',async()=>{
  const x=await setup('TRIP-RACE');const results=await Promise.allSettled([f.app.transport.cancel(f.root.token,x.activity.id,{operationId:crypto.randomUUID(),reason:'Concurrent cancellation A'}),f.app.transport.cancel(f.root.token,x.activity.id,{operationId:crypto.randomUUID(),reason:'Concurrent cancellation B'})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await f.database.pool.query('select count(*)::int n from activity_cancellations where activity_id=$1',[x.activity.id])).rows[0].n).toBe(1);expect((await f.database.pool.query('select count(*)::int n from credits c join financial_corrections fc on fc.id=c.correction_id join tuition_corrections tc on tc.correction_id=fc.id join activity_children ac on ac.installment_id=tc.installment_id where ac.activity_id=$1',[x.activity.id])).rows[0].n).toBe(1);
 });
 it('A20: bus 500 rejects 250, accepts exact settlement once, and retry creates no cash',async()=>{
  f=await financeFixture();const today=cairoIsoDate(),child=await f.child('BUS-A20'),subscription=await f.app.transport.subscribe(f.root.token,{operationId:crypto.randomUUID(),childId:child.childId,categoryId:f.bus.id,periodStart:today,periodEnd:today,amount:'50000',dueOn:today,administrativePermission:true});
  await expect(f.payments.collect(f.root.token,f.collect(subscription.installmentId,'25000'))).rejects.toMatchObject({code:'VALIDATION_ERROR'});const input=f.collect(subscription.installmentId,'50000'),settled=await f.payments.collect(f.root.token,input),before=(await f.database.pool.query('select balance::text from treasury_balances where id=$1',[f.cashA.id])).rows[0].balance;expect(await f.payments.collect(f.root.token,input)).toEqual(settled);expect((await f.database.pool.query('select balance::text from treasury_balances where id=$1',[f.cashA.id])).rows[0].balance).toBe(before);expect((await f.app.transport.subscriptions(f.root.token,{}))[0]).toMatchObject({paid:true,administrativePermission:true,eligible:true,noFee:false});
 });
 it('A32/A31: payment and consent remain distinct, free trips work, disable blocks actions/notices but retains history',async()=>{
  f=await financeFixture();const trip=await f.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:'TRIP-A32',name:'Trip',kind:'TRIP'}),paid=await f.child('TRIP-PAID'),consented=await f.child('TRIP-CONSENT'),created=await f.app.transport.createActivity(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,categoryId:trip.id,title:'Zoo trip',details:'Day visit',eventDate:cairoIsoDate(),fee:'10000',dueOn:cairoIsoDate(),childIds:[paid.childId,consented.childId]});
  const links=(await f.database.pool.query<{child_id:string;installment_id:string}>('select child_id,installment_id from activity_children where activity_id=$1',[created.id])).rows;await f.payments.collect(f.root.token,f.collect(links.find(x=>x.child_id===paid.childId)!.installment_id,'10000'));await f.app.transport.consent(f.root.token,created.id,consented.childId,{operationId:crypto.randomUUID(),consented:true,reason:'Guardian consent recorded by phone'});
  const rows=(await f.app.transport.activities(f.root.token,{}))[0].items;expect(rows.find(x=>x.childId===paid.childId)).toMatchObject({paid:true,consented:false,participating:false});expect(rows.find(x=>x.childId===consented.childId)).toMatchObject({paid:false,consented:true,participating:false});
  const free=await f.app.transport.createActivity(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,categoryId:trip.id,title:'Free garden day',details:'No-fee activity',eventDate:cairoIsoDate(),fee:'0',dueOn:cairoIsoDate(),childIds:[consented.childId]});await f.app.transport.consent(f.root.token,free.id,consented.childId,{operationId:crypto.randomUUID(),consented:true,reason:'Guardian consent recorded'});expect((await f.app.transport.activities(f.root.token,{})).find(x=>x.id===free.id)!.items[0]).toMatchObject({noFee:true,paid:true,consented:true,participating:true});
  const credential=paid.credentials[0];let parent=await f.app.auth.login(credential.username,credential.temporaryPassword);await f.app.auth.changePassword(parent.token,credential.temporaryPassword,'Permanent trip parent password 2026');parent=await f.app.auth.login(credential.username,'Permanent trip parent password 2026');expect((await f.app.communication.notifications(parent.token,{})).items.some(n=>n.kind==='TRIP'&&n.href.includes('/parent/payments'))).toBe(true);
  await setModule('ACTIVITIES',false);await expect(f.app.transport.consent(f.root.token,created.id,paid.childId,{operationId:crypto.randomUUID(),consented:true,reason:'Should be blocked'})).rejects.toMatchObject({code:'MODULE_DISABLED'});expect((await f.app.transport.activities(f.root.token,{})).some(x=>x.id===created.id)).toBe(true);expect((await f.app.communication.notifications(parent.token,{})).items.some(n=>n.kind==='TRIP')).toBe(false);
 });
 it('A01/A02/A31: classroom roster is exact; finance permission stays separate; transport disable stops actions and reminders',async()=>{
  f=await financeFixture();const trip=await f.ledger.category(f.root.token,{operationId:crypto.randomUUID(),code:'TRIP-SCOPE',name:'Scoped trip',kind:'TRIP'}),one=await f.child('SCOPE-ONE',f.a.id,f.classes[0].id),two=await f.child('SCOPE-TWO',f.a.id,f.classes[1].id);await f.app.transport.createActivity(f.root.token,{operationId:crypto.randomUUID(),branchId:f.a.id,categoryId:trip.id,title:'Scoped trip',details:'Two-class invitation',eventDate:cairoIsoDate(),fee:'0',dueOn:cairoIsoDate(),childIds:[one.childId,two.childId]});const teacher=await f.financeStaff([f.a.id],[f.classes[0].id],'CLASSROOM',['activities.read']);const roster=await f.app.transport.activities(teacher.token,{});expect(roster.flatMap(x=>x.items).map(x=>x.childId)).toEqual([one.childId]);await expect(f.ledger.outstanding(teacher.token,{childId:one.childId})).rejects.toMatchObject({code:'FORBIDDEN'});
  const bus=await f.app.transport.subscribe(f.root.token,{operationId:crypto.randomUUID(),childId:one.childId,categoryId:f.bus.id,periodStart:'2026-01-01',periodEnd:'2026-12-31',amount:'50000',dueOn:'2026-01-01',administrativePermission:true});await setModule('TRANSPORT',false);await expect(f.app.transport.permission(f.root.token,bus.id,{operationId:crypto.randomUUID(),expectedVersion:1,enabled:false,reason:'Blocked while disabled'})).rejects.toMatchObject({code:'MODULE_DISABLED'});expect((await f.app.transport.subscriptions(f.root.token,{})).some(x=>x.id===bus.id)).toBe(true);expect((await runReminderBatch(f.database,cairoIsoDate())).notices).toBe(0);
 });
});
