export const childTransferEn={
 'childTransfer.title':'Child branch transfers','childTransfer.help':'Move the child and their remaining debt today. Original charges, due dates and receipts stay unchanged. This creates no cash movement. Later recurring charges use the new branch; existing bus and trip links need staff review.',
 'childTransfer.preview':'Preview transfer','childTransfer.commit':'Transfer child and remaining debt','childTransfer.source':'Current branch','childTransfer.destination':'New branch','childTransfer.classroom':'New classroom','childTransfer.none':'No classroom','childTransfer.choose':'Choose a child','childTransfer.review':'Review the transfer','childTransfer.confirm':'I confirm this child and their remaining debt should move today, with no cash transfer. The final balance is recalculated when saved.',
 'childTransfer.history':'Branch transfer history','childTransfer.in':'Receivables transferred in','childTransfer.out':'Receivables transferred out','childTransfer.amount':'Outstanding amount transferred','childTransfer.empty':'No branch transfers in this view.','childTransfer.reference':'Original debt reference','childTransfer.today':'Transfers take effect today. Scheduled and backdated transfers are unavailable.'
};
export const childTransferAr:Record<keyof typeof childTransferEn,string>={
 'childTransfer.title':'نقل الطفل بين الفروع','childTransfer.help':'انقل الطفل والمديونية المتبقية عليه بتاريخ النهارده. المطالبات الأصلية ومواعيد الاستحقاق والإيصالات بتفضل محفوظة. النقل مش بيحرك فلوس. الرسوم الدورية الجديدة بتتسجل على الفرع الجديد؛ اشتراكات الأتوبيس والرحلات الحالية محتاجة مراجعة الإدارة.',
 'childTransfer.preview':'معاينة النقل','childTransfer.commit':'نقل الطفل والمديونية المتبقية','childTransfer.source':'الفرع الحالي','childTransfer.destination':'الفرع الجديد','childTransfer.classroom':'الفصل الجديد','childTransfer.none':'من غير فصل','childTransfer.choose':'اختار طفل','childTransfer.review':'مراجعة النقل','childTransfer.confirm':'بأكد نقل الطفل والمديونية المتبقية عليه النهارده من غير تحويل فلوس. الرصيد النهائي بيتحسب تاني وقت الحفظ.',
 'childTransfer.history':'سجل النقل بين الفروع','childTransfer.in':'مديونية منقولة للفرع','childTransfer.out':'مديونية منقولة من الفرع','childTransfer.amount':'المديونية المتبقية اللي اتنقلت','childTransfer.empty':'مفيش عمليات نقل في العرض ده.','childTransfer.reference':'مرجع المديونية الأصلي','childTransfer.today':'النقل بيسري من النهارده. النقل بتاريخ قديم أو تحديد موعد مستقبلي مش متاح.'
};
