import { useEffect,useState,type FormEvent } from 'react';
import { Link } from 'react-router';
import type { CorrectionOptions,FinancialCorrectionRecord,RefundRecord } from '@nursery/contracts';
import { cairoIsoDate,egpToPiastres,formatDateOnly,formatEgp,piastres } from '@nursery/domain';
import { Button,SelectField,TextField } from '../../components/controls.js';
import { Card } from '../../components/surfaces.js';
import { LanguageSwitcher } from '../../layout/AppShell.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import { useScoped } from '../children/scoped.js';
import { OperationNotice } from './spending-screen.js';
import { useFinancialOperation } from './use-operation.js';

const money=(v:string)=>formatEgp(piastres(BigInt(v)));
function Confirm({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}) {const {t}=useLocale();return <label><input type="checkbox" required checked={checked} onChange={e=>onChange(e.target.checked)}/>{t('corrections.confirmCash')}</label>;}
export function CorrectionsScreen() {
 const {t}=useLocale(),options=useScoped<CorrectionOptions>('finance/correction-options'),history=useScoped<FinancialCorrectionRecord[]>('finance/corrections?limit=50'),refundHistory=useScoped<RefundRecord[]>('finance/refunds?limit=50');
 const [receiptId,setReceiptId]=useState(''),[receiptReplace,setReceiptReplace]=useState(false),[receiptAccount,setReceiptAccount]=useState(''),[receiptInstallment,setReceiptInstallment]=useState(''),[receiptAmount,setReceiptAmount]=useState(''),[receiptReason,setReceiptReason]=useState(''),[receiptConfirm,setReceiptConfirm]=useState(false);
 const [expenseId,setExpenseId]=useState(''),[expenseReplace,setExpenseReplace]=useState(false),[expenseAccount,setExpenseAccount]=useState(''),[expenseAmount,setExpenseAmount]=useState(''),[expenseReason,setExpenseReason]=useState(''),[expenseConfirm,setExpenseConfirm]=useState(false);
 const [transferId,setTransferId]=useState(''),[transferReplace,setTransferReplace]=useState(false),[transferSource,setTransferSource]=useState(''),[transferDestination,setTransferDestination]=useState(''),[transferAmount,setTransferAmount]=useState(''),[transferReason,setTransferReason]=useState(''),[transferConfirm,setTransferConfirm]=useState(false);
 const [tuitionId,setTuitionId]=useState(''),[reduction,setReduction]=useState(''),[tuitionReason,setTuitionReason]=useState(''),[tuitionConfirm,setTuitionConfirm]=useState(false);
 const [creditId,setCreditId]=useState(''),[originId,setOriginId]=useState(''),[refundAccount,setRefundAccount]=useState(''),[refundAmount,setRefundAmount]=useState(''),[refundReason,setRefundReason]=useState(''),[refundExternal,setRefundExternal]=useState(''),[alternative,setAlternative]=useState(false),[refundConfirm,setRefundConfirm]=useState(false);
 const clear=()=>{setReceiptId('');setExpenseId('');setTransferId('');setTuitionId('');setCreditId('');setReceiptConfirm(false);setExpenseConfirm(false);setTransferConfirm(false);setTuitionConfirm(false);setRefundConfirm(false);};
 const op=useFinancialOperation(()=>{options.reload();history.reload();refundHistory.reload();clear();});
 useEffect(()=>{window.addEventListener('blur',clear);window.addEventListener('nursery:scope-refresh',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);window.removeEventListener('nursery:scope-refresh',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 const receipt=options.data?.receipts.find(x=>x.id===receiptId),expense=options.data?.expenses.find(x=>x.id===expenseId),transfer=options.data?.transfers.find(x=>x.id===transferId),credit=options.data?.credits.find(x=>x.id===creditId),origin=credit?.origins.find(x=>x.id===originId);
 function selectReceipt(id:string){setReceiptId(id);const r=options.data?.receipts.find(x=>x.id===id);setReceiptAccount(r?.accountId??'');setReceiptInstallment(r?.allocations[0]?.installmentId??'');setReceiptAmount('');setReceiptConfirm(false);}
 function correctReceipt(e:FormEvent){e.preventDefault();if(!receipt||!receiptConfirm)return;try{const account=options.data!.accounts.find(x=>x.id===receiptAccount);op.submit(`finance/receipts/${receipt.id}/correct`,{effectiveOn:cairoIsoDate(),reason:receiptReason,replacement:receiptReplace?{accountId:receiptAccount,method:account!.type,amount:egpToPiastres(receiptAmount),payerName:receipt.payerName,externalReference:'',allocations:[{installmentId:receiptInstallment,amount:egpToPiastres(receiptAmount)}]}:null});}catch{op.invalid();}}
 function correctExpense(e:FormEvent){e.preventDefault();if(!expense||!expenseConfirm)return;try{const account=options.data!.accounts.find(x=>x.id===expenseAccount);op.submit(`expenses/${expense.id}/correct`,{effectiveOn:cairoIsoDate(),reason:expenseReason,replacement:expenseReplace?{accountId:expenseAccount,method:account!.type,amount:egpToPiastres(expenseAmount),externalReference:''}:null});}catch{op.invalid();}}
 function correctTransfer(e:FormEvent){e.preventDefault();if(!transfer||!transferConfirm)return;try{op.submit(`finance/transfers/${transfer.id}/correct`,{effectiveOn:cairoIsoDate(),reason:transferReason,replacement:transferReplace?{sourceAccountId:transferSource,destinationAccountId:transferDestination,amount:egpToPiastres(transferAmount),externalReference:''}:null});}catch{op.invalid();}}
 function reduce(e:FormEvent){e.preventDefault();if(!tuitionId||!tuitionConfirm)return;try{op.submit(`finance/installments/${tuitionId}/reduce`,{effectiveOn:cairoIsoDate(),reductionAmount:egpToPiastres(reduction),reason:tuitionReason});}catch{op.invalid();}}
 function selectCredit(id:string){setCreditId(id);const c=options.data?.credits.find(x=>x.id===id),o=c?.origins[0];setOriginId(o?.id??'');setRefundAccount(o?.accountId??'');setAlternative(false);setRefundConfirm(false);}
 function refund(e:FormEvent){e.preventDefault();if(!credit||!origin||!refundConfirm)return;try{const account=options.data!.accounts.find(x=>x.id===refundAccount);op.submit('finance/refunds',{creditId:credit.id,creditOriginId:origin.id,accountId:refundAccount,method:account!.type,amount:egpToPiastres(refundAmount),refundedOn:cairoIsoDate(),reason:refundReason,externalReference:refundExternal,alternativeAccountConfirmed:alternative});}catch{op.invalid();}}
 const error=options.error||history.error||refundHistory.error;
 return <main className="organization-page"><LanguageSwitcher/><Link to="/account">{t('auth.account')}</Link><Link to="/administration/finance">{t('finance.title')}</Link><Link to="/administration/expenses">{t('spending.title')}</Link><h1>{t('corrections.title')}</h1><p>{t('corrections.help')}</p><p>{t('corrections.currentOnly')} {formatDateOnly(cairoIsoDate())}</p><OperationNotice op={op}/>{error&&<p role="alert">{t(error)}</p>}
 {options.data&&!options.data.canCorrect&&<p>{t('corrections.readOnly')}</p>}{options.data?.canCorrect&&<>
 <form onSubmit={correctReceipt}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('corrections.receipt')}</legend><SelectField label={t('corrections.originalReceipt')} value={receiptId} required onChange={e=>selectReceipt(e.target.value)}><option value="">{t('corrections.choose')}</option>{options.data.receipts.map(r=><option key={r.id} value={r.id}>{r.reference} — {money(r.amount)} — {r.accountCode}</option>)}</SelectField>{receipt&&<><p>{t('corrections.originalKept')}</p><label><input type="checkbox" checked={receiptReplace} onChange={e=>setReceiptReplace(e.target.checked)}/>{t('corrections.replace')}</label>{receiptReplace&&<><SelectField label={t('corrections.replacementAccount')} required value={receiptAccount} onChange={e=>setReceiptAccount(e.target.value)}>{options.data.accounts.filter(a=>a.branchId===receipt.branchId).map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField><SelectField label={t('corrections.replacementAllocation')} required value={receiptInstallment} onChange={e=>setReceiptInstallment(e.target.value)}>{receipt.allocations.map(a=><option key={a.id} value={a.installmentId}>{a.childCode} — {a.categoryName} — {money(a.activeAmount)}</option>)}</SelectField><TextField label={t('corrections.replacementAmount')} inputMode="decimal" required value={receiptAmount} onChange={e=>setReceiptAmount(e.target.value)}/></>}<TextField label={t('spending.reason')} required maxLength={500} value={receiptReason} onChange={e=>setReceiptReason(e.target.value)}/><Confirm checked={receiptConfirm} onChange={setReceiptConfirm}/><Button type="submit">{t(receiptReplace?'corrections.replace':'corrections.reverse')}</Button></>}</fieldset></form>
 <form onSubmit={correctExpense}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('corrections.expense')}</legend><SelectField label={t('corrections.originalExpense')} value={expenseId} required onChange={e=>{setExpenseId(e.target.value);const x=options.data!.expenses.find(v=>v.id===e.target.value);setExpenseAccount(x?.accountId??'');setExpenseConfirm(false);}}><option value="">{t('corrections.choose')}</option>{options.data.expenses.map(x=><option key={x.id} value={x.id}>{x.categoryName} — {money(x.paidAmount)} — {x.accountCode}</option>)}</SelectField>{expense&&<><label><input type="checkbox" checked={expenseReplace} onChange={e=>setExpenseReplace(e.target.checked)}/>{t('corrections.replace')}</label>{expenseReplace&&<><SelectField label={t('corrections.replacementAccount')} required value={expenseAccount} onChange={e=>setExpenseAccount(e.target.value)}>{options.data.accounts.filter(a=>a.branchId===expense.branchId).map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField><TextField label={t('corrections.replacementAmount')} inputMode="decimal" required value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)}/></>}<TextField label={t('spending.reason')} required maxLength={500} value={expenseReason} onChange={e=>setExpenseReason(e.target.value)}/><Confirm checked={expenseConfirm} onChange={setExpenseConfirm}/><Button type="submit">{t(expenseReplace?'corrections.replace':'corrections.reverse')}</Button></>}</fieldset></form>
 <form onSubmit={correctTransfer}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('corrections.transfer')}</legend><SelectField label={t('corrections.originalTransfer')} value={transferId} required onChange={e=>{setTransferId(e.target.value);const x=options.data!.transfers.find(v=>v.id===e.target.value);setTransferSource(x?.sourceAccountId??'');setTransferDestination(x?.destinationAccountId??'');setTransferConfirm(false);}}><option value="">{t('corrections.choose')}</option>{options.data.transfers.map(x=><option key={x.id} value={x.id}>{x.sourceCode} → {x.destinationCode} — {money(x.amount)}</option>)}</SelectField>{transfer&&<><label><input type="checkbox" checked={transferReplace} onChange={e=>setTransferReplace(e.target.checked)}/>{t('corrections.replace')}</label>{transferReplace&&<><SelectField label={t('transfer.source')} required value={transferSource} onChange={e=>setTransferSource(e.target.value)}>{options.data.accounts.map(a=><option key={a.id} value={a.id}>{a.code}</option>)}</SelectField><SelectField label={t('transfer.destination')} required value={transferDestination} onChange={e=>setTransferDestination(e.target.value)}>{options.data.accounts.map(a=><option key={a.id} value={a.id}>{a.code}</option>)}</SelectField><TextField label={t('corrections.replacementAmount')} inputMode="decimal" required value={transferAmount} onChange={e=>setTransferAmount(e.target.value)}/></>}<TextField label={t('spending.reason')} required maxLength={500} value={transferReason} onChange={e=>setTransferReason(e.target.value)}/><Confirm checked={transferConfirm} onChange={setTransferConfirm}/><Button type="submit">{t(transferReplace?'corrections.replace':'corrections.reverse')}</Button></>}</fieldset></form>
 <form onSubmit={reduce}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('corrections.tuition')}</legend><SelectField label={t('corrections.tuitionInstallment')} value={tuitionId} required onChange={e=>{setTuitionId(e.target.value);setTuitionConfirm(false);}}><option value="">{t('corrections.choose')}</option>{options.data.tuition.map(x=><option key={x.installmentId} value={x.installmentId}>{x.childCode} — {money(x.effectiveAmount)} — {t('collections.remaining')} {money(x.remaining)}</option>)}</SelectField><TextField label={t('corrections.reductionAmount')} inputMode="decimal" required value={reduction} onChange={e=>setReduction(e.target.value)}/><TextField label={t('spending.reason')} required maxLength={500} value={tuitionReason} onChange={e=>setTuitionReason(e.target.value)}/><label><input type="checkbox" required checked={tuitionConfirm} onChange={e=>setTuitionConfirm(e.target.checked)}/>{t('corrections.confirmTuition')}</label><p>{t('corrections.creditHelp')}</p><Button type="submit">{t('corrections.reduce')}</Button></fieldset></form>
 <form onSubmit={refund}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('corrections.refund')}</legend><SelectField label={t('corrections.credit')} value={creditId} required onChange={e=>selectCredit(e.target.value)}><option value="">{t('corrections.choose')}</option>{options.data.credits.map(c=><option key={c.id} value={c.id}>{c.childCode} — {money(c.remaining)}</option>)}</SelectField>{credit&&<><SelectField label={t('corrections.originalSource')} value={originId} required onChange={e=>{setOriginId(e.target.value);const o=credit.origins.find(v=>v.id===e.target.value);setRefundAccount(o?.accountId??'');setAlternative(false);}}>{credit.origins.map(o=><option key={o.id} value={o.id}>{o.receiptReference} — {o.accountCode} — {money(o.remaining)}</option>)}</SelectField><SelectField label={t('corrections.fundingAccount')} value={refundAccount} required onChange={e=>{setRefundAccount(e.target.value);setAlternative(false);}}>{options.data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField>{refundAccount!==origin?.accountId&&<label><input type="checkbox" required checked={alternative} onChange={e=>setAlternative(e.target.checked)}/>{t('corrections.confirmAlternative')}</label>}<TextField label={t('corrections.refundAmount')} inputMode="decimal" required value={refundAmount} onChange={e=>setRefundAmount(e.target.value)}/><TextField label={t('spending.external')} maxLength={120} value={refundExternal} onChange={e=>setRefundExternal(e.target.value)}/><TextField label={t('spending.reason')} required maxLength={500} value={refundReason} onChange={e=>setRefundReason(e.target.value)}/><Confirm checked={refundConfirm} onChange={setRefundConfirm}/><Button type="submit">{t('corrections.refund')}</Button></>}</fieldset></form></>}
 <h2>{t('corrections.history')}</h2>{history.data?.map(x=><Card key={x.id} title={`${t(`corrections.${x.targetKind}`)} — ${t(`corrections.${x.action}`)}`}><p>{formatDateOnly(x.effectiveOn)} — {x.actor}</p><p>{x.reason}</p></Card>)}{refundHistory.data?.map(x=><Card key={x.id} title={`${t('corrections.refund')} — ${x.childCode}`}><p>{money(x.amount)} — {formatDateOnly(x.refundedOn)}</p><p>{x.originalReceiptReference} — {x.originalAccountCode} → {x.fundingAccountCode}</p><p>{x.reason}</p></Card>)}</main>;
}
