export const payrollEn={
 'organization.cap.payroll.manage':'Manage employee financial profiles and adjustments','organization.cap.payroll.pay':'Record salary advances and full final payroll',
 'licensing.module.PAYROLL':'Payroll',
 'payroll.title':'Employee financials and payroll','payroll.help':'Each employee-month keeps its own salary and paying account. Advances move cash immediately; final payroll pays the full remainder once. Old unpaid months remain separate.',
 'payroll.disabled':'Payroll is disabled. Authorized financial history is retained; new payroll actions are unavailable.',
 'payroll.amountChanged':'The payroll remainder has changed. Review the refreshed amount before confirming a new settlement.',
 'payroll.month':'Payroll month','payroll.monthHint':'YYYY-MM; no automatic carry-forward','payroll.roster':'Monthly payroll roster','payroll.create':'Create employee financial profile',
 'payroll.code':'Employee code','payroll.name':'Employee full name','payroll.salary':'Basic salary (EGP)','payroll.effective':'Effective month','payroll.branch':'Paying branch','payroll.account':'Paying account',
 'payroll.login':'Create an optional staff login','payroll.username':'Staff login username','payroll.profileOnly':'Profile only — no login slot reserved','payroll.loginHelp':'A staff login reserves an employee slot. Financial deactivation does not deactivate the login or release its slot.',
 'payroll.provisionLogin':'Create a login for this existing financial profile',
 'payroll.secretHelp':'Deliver this temporary password privately. It is shown only in this response and is not stored in payroll history. If the response is lost, use the existing Superadmin password reset.',
 'payroll.prepare':'Snapshot this employee-month','payroll.UNPREPARED':'Not snapshotted','payroll.UNPAID':'Unpaid','payroll.SETTLED':'Settled','payroll.inactive':'Inactive financial profile',
 'payroll.details':'Employee financial detail and history','payroll.salaryHistory':'Salary history','payroll.periodHistory':'Retained payroll months','payroll.openMonth':'Open this payroll month','payroll.changeSalary':'Schedule future salary and paying account','payroll.salaryHelp':'Salary changes take effect from a future month; already snapshotted months are never recalculated.',
 'payroll.deactivate':'Deactivate financial profile','payroll.reactivate':'Reactivate financial profile','payroll.statusHelp':'This changes only the financial profile. Existing unpaid months, login status and seat reservations are retained.',
 'payroll.adjust':'Record current-month adjustment','payroll.kind':'Adjustment kind','payroll.ADDITION':'Addition / bonus','payroll.DEDUCTION':'Deduction','payroll.PENALTY':'Penalty',
 'payroll.advance':'Record paid advance','payroll.settle':'Pay the full remaining salary','payroll.zeroSettle':'Record explicit no-cash settlement','payroll.confirm':'I confirm the displayed full remainder was actually paid from the snapshotted account, or that a zero remainder is being explicitly closed without cash.',
 'payroll.confirmAdvance':'I confirm this advance was actually paid from the snapshotted account.',
 'payroll.cutoff':'Adjustments and advances are allowed only in the current Cairo month, before final settlement. Advances plus deductions/penalties cannot exceed basic salary, even with bonuses.',
 'payroll.additions':'Additions / bonuses','payroll.deductions':'Deductions / penalties','payroll.advances':'Already-paid advances','payroll.remaining':'Remaining final payable','payroll.totalSalary':'Salary snapshots / unsnapshotted forecast','payroll.totalRemaining':'Outstanding snapshotted payroll','payroll.totalPaid':'Final salary cash paid','payroll.receipt':'Salary receipt / export data','payroll.cashTotal':'Total actual payroll cash outflow','payroll.noCash':'Explicit no-cash settlement','payroll.empty':'No employees with applicable salary terms in this branch/month.'
} as const;
export const payrollAr:Record<keyof typeof payrollEn,string>={
 'organization.cap.payroll.manage':'إدارة الحسابات المالية للموظفين والتعديلات','organization.cap.payroll.pay':'تسجيل سلف المرتب وصرف باقي المرتب بالكامل',
 'licensing.module.PAYROLL':'المرتبات',
 'payroll.title':'حسابات الموظفين والمرتبات','payroll.help':'كل موظف وشهر ليهم مرتب وحساب صرف مستقل. السلفة بتخصم فلوس فوراً؛ الصرف النهائي بيكون باقي المرتب بالكامل مرة واحدة. الشهور القديمة غير المدفوعة بتفضل منفصلة.',
 'payroll.disabled':'المرتبات متعطلة. السجل المالي المصرح به محفوظ، والإجراءات الجديدة مش متاحة.',
 'payroll.amountChanged':'باقي المرتب اتغيّر. راجع المبلغ المحدّث قبل ما تأكد صرف جديد.',
 'payroll.month':'شهر المرتب','payroll.monthHint':'YYYY-MM؛ من غير ترحيل تلقائي','payroll.roster':'كشف مرتبات الشهر','payroll.create':'إضافة ملف مالي لموظف',
 'payroll.code':'كود الموظف','payroll.name':'اسم الموظف بالكامل','payroll.salary':'المرتب الأساسي (جنيه)','payroll.effective':'شهر بداية التطبيق','payroll.branch':'فرع صرف المرتب','payroll.account':'حساب صرف المرتب',
 'payroll.login':'إنشاء حساب دخول اختياري للموظف','payroll.username':'اسم مستخدم الموظف','payroll.profileOnly':'ملف مالي فقط — مفيش حجز لحساب دخول','payroll.loginHelp':'حساب الدخول بيحجز مكان موظف. تعطيل الملف المالي مش بيعطل الدخول ولا بيحرر مكانه.',
 'payroll.provisionLogin':'إنشاء حساب دخول للملف المالي الموجود',
 'payroll.secretHelp':'وصّل كلمة السر المؤقتة بشكل خاص. بتظهر في الرد ده فقط ومش بتتخزن في سجل المرتبات. لو الرد ضاع، استخدم إعادة تعيين كلمة السر بواسطة مسؤول النظام.',
 'payroll.prepare':'تثبيت مرتب وحساب الموظف للشهر ده','payroll.UNPREPARED':'مش متثبت للشهر','payroll.UNPAID':'غير مدفوع','payroll.SETTLED':'تمت التسوية','payroll.inactive':'الملف المالي غير نشط',
 'payroll.details':'تفاصيل وسجل حساب الموظف','payroll.salaryHistory':'سجل المرتب الأساسي','payroll.periodHistory':'شهور المرتب المحفوظة','payroll.openMonth':'فتح شهر المرتب ده','payroll.changeSalary':'تحديد مرتب وحساب صرف لشهر قادم','payroll.salaryHelp':'تغيير المرتب بيبدأ من شهر قادم؛ الشهور المتثبتة مش بتتحسب من جديد.',
 'payroll.deactivate':'تعطيل الملف المالي','payroll.reactivate':'إعادة تفعيل الملف المالي','payroll.statusHelp':'ده بيغيّر الملف المالي فقط. الشهور المستحقة وحالة الدخول وحجز الحساب محفوظين.',
 'payroll.adjust':'تسجيل تعديل لشهر المرتب الحالي','payroll.kind':'نوع التعديل','payroll.ADDITION':'إضافة / مكافأة','payroll.DEDUCTION':'خصم','payroll.PENALTY':'جزاء',
 'payroll.advance':'تسجيل سلفة اتدفعت','payroll.settle':'صرف باقي المرتب بالكامل','payroll.zeroSettle':'تسجيل تسوية صريحة من غير فلوس','payroll.confirm':'بأكد إن باقي المرتب المعروض بالكامل اتدفع فعلاً من الحساب المتثبت، أو إن الباقي صفر وبيتقفل بشكل صريح من غير حركة فلوس.',
 'payroll.confirmAdvance':'بأكد إن السلفة دي اتدفعت فعلاً من حساب المرتب المتثبت.',
 'payroll.cutoff':'التعديلات والسلف متاحة في شهر القاهرة الحالي فقط وقبل التسوية النهائية. السلف والخصومات والجزاءات مع بعض مينفعش يعدّوا المرتب الأساسي حتى لو فيه مكافآت.',
 'payroll.additions':'الإضافات / المكافآت','payroll.deductions':'الخصومات / الجزاءات','payroll.advances':'السلف اللي اتدفعت','payroll.remaining':'باقي المرتب للصرف النهائي','payroll.totalSalary':'المرتبات المتثبتة / توقع الملفات غير المتثبتة','payroll.totalRemaining':'المرتبات المتثبتة اللي لسه مستحقة','payroll.totalPaid':'فلوس الصرف النهائي للمرتب','payroll.receipt':'بيانات إيصال المرتب / التصدير','payroll.cashTotal':'إجمالي فلوس المرتب اللي اتصرفت فعلاً','payroll.noCash':'تسوية صريحة من غير حركة فلوس','payroll.empty':'مفيش موظفين بمرتب سارٍ في الفرع والشهر دول.'
};
