import { useEffect,useState,type FormEvent } from 'react';
import { Link } from 'react-router';
import type { EmployeePayrollHistory,PayrollOptions,PayrollPage,PayrollPeriodDetail,PayrollReceiptData,PayrollRosterItem } from '@nursery/contracts';
import { cairoIsoDate,egpToPiastres,formatEgp,formatDateOnly,piastres } from '@nursery/domain';
import { Button,DateField,SelectField,TextField } from '../../components/controls.js';
import { Card } from '../../components/surfaces.js';
import { Icon } from '../../components/Icon.js';
import { StatCard,StatGrid, PageHeader, EmptyState } from '../../components/data-display.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import { useScoped } from '../children/scoped.js';
import { useFinancialOperation } from './use-operation.js';
import { OperationNotice } from './spending-screen.js';

type Operation=ReturnType<typeof useFinancialOperation>;
const money=(v:string)=>formatEgp(piastres(BigInt(v)));
const thisMonth=()=>cairoIsoDate().slice(0,7);
const nextMonth=()=>{const [y,m]=thisMonth().split('-').map(Number);return `${m===12?y+1:y}-${String(m===12?1:m+1).padStart(2,'0')}`;};

function PayingFields({options,branch,setBranch,account,setAccount}:{options:PayrollOptions;branch:string;setBranch:(v:string)=>void;account:string;setAccount:(v:string)=>void}) {
 const {t}=useLocale();return <><div className="filter-bar"><SelectField label={t('payroll.branch')} required value={branch} onChange={e=>{setBranch(e.target.value);setAccount('');}}><option value="">{t('transfer.choose')}</option>{options.branches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</SelectField><SelectField label={t('payroll.account')} required value={account} onChange={e=>setAccount(e.target.value)}><option value="">{t('transfer.choose')}</option>{options.accounts.filter(a=>a.branchId===branch).map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField></div></>;
}
function ProfileForm({options,op}:{options:PayrollOptions;op:Operation}) {
 const {t}=useLocale();const [code,setCode]=useState(''),[name,setName]=useState(''),[salary,setSalary]=useState(''),[effective,setEffective]=useState(thisMonth()),[branch,setBranch]=useState(''),[account,setAccount]=useState(''),[login,setLogin]=useState(false),[username,setUsername]=useState('');
 function submit(e:FormEvent) {e.preventDefault();try {op.submit('payroll/employees',{employeeCode:code,fullName:name,basicSalary:egpToPiastres(salary),effectiveMonth:effective,payingBranchId:branch,payingAccountId:account,loginUsername:login?username:null});}catch {op.invalid();}}
 return <form className="form-stack" onSubmit={submit}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.create')}</legend><TextField label={t('payroll.code')} required maxLength={32} pattern="[A-Za-z0-9_-]+" value={code} onChange={e=>setCode(e.target.value)}/><TextField label={t('payroll.name')} required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/><TextField label={t('payroll.salary')} required dir="ltr" inputMode="decimal" value={salary} onChange={e=>setSalary(e.target.value)}/><TextField label={t('payroll.effective')} required pattern="[1-9][0-9]{3}-(0[1-9]|1[0-2])" dir="ltr" value={effective} onChange={e=>setEffective(e.target.value)}/><PayingFields options={options} branch={branch} setBranch={setBranch} account={account} setAccount={setAccount}/><p>{t('payroll.loginHelp')}</p>{options.canProvisionLogin&&<><label className="choice-field"><input type="checkbox" checked={login} onChange={e=>setLogin(e.target.checked)}/>{t('payroll.login')}</label>{login&&<TextField label={t('payroll.username')} required autoComplete="off" maxLength={64} value={username} onChange={e=>setUsername(e.target.value)}/>}</>}{!login&&<p>{t('payroll.profileOnly')}</p>}<Button icon="plus" type="submit">{t('payroll.create')}</Button></fieldset></form>;
}
function Totals({row}:{row:PayrollRosterItem}) {
 const {t}=useLocale();return <><p>{row.month} — {row.branchCode} — {row.accountCode} — {t(`finance.${row.method}`)}</p><p>{t('payroll.salary')}: {money(row.basicSalary)}</p><p>{t('payroll.additions')}: {money(row.additions)} — {t('payroll.deductions')}: {money(row.deductions)}</p><p>{t('payroll.advances')}: {money(row.advances)} — {t('payroll.remaining')}: {money(row.remaining)}</p><p>{t(`payroll.${row.state}`)}{!row.active&&` — ${t('payroll.inactive')}`}</p></>;
}
function EmployeeDetail({id,options,op,openPeriod}:{id:string;options:PayrollOptions;op:Operation;openPeriod:(id:string)=>void}) {
 const {t}=useLocale(),history=useScoped<EmployeePayrollHistory>(`payroll/employees/${id}`);
 const [salary,setSalary]=useState(''),[effective,setEffective]=useState(nextMonth()),[branch,setBranch]=useState(''),[account,setAccount]=useState(''),[reason,setReason]=useState(''),[statusReason,setStatusReason]=useState(''),[username,setUsername]=useState(''),[loginReason,setLoginReason]=useState('');
 function change(e:FormEvent) {e.preventDefault();try {op.submit(`payroll/employees/${id}/salary`,{basicSalary:egpToPiastres(salary),effectiveMonth:effective,payingBranchId:branch,payingAccountId:account,reason});}catch {op.invalid();}}
 return <Card title={t('payroll.details')}>{history.error&&<p className="inline-notice inline-notice--danger" role="alert">{t(history.error)}</p>}{history.data&&<><h3>{history.data.employee.employeeCode} — {history.data.employee.fullName}</h3><p>{history.data.employee.accountId?`${t('auth.accountId')}: ${history.data.employee.accountId}`:t('payroll.profileOnly')}</p><h3>{t('payroll.salaryHistory')}</h3>{history.data.salaryHistory.map(h=><p key={h.id}>{h.effectiveMonth} — {money(h.basicSalary)} — {h.branchCode} — {h.accountCode} — {h.actor} — {h.reason}</p>)}<h3>{t('payroll.periodHistory')}</h3>{history.data.periods.map(p=><div key={p.periodId}><Totals row={p}/><Button disabled={op.locked} onClick={()=>openPeriod(p.periodId!)}>{t('payroll.openMonth')} — {p.month}</Button></div>)}
 {options.canProvisionLogin&&!history.data.employee.accountId&&<form className="form-stack" onSubmit={e=>{e.preventDefault();op.submit(`payroll/employees/${id}/login`,{username,reason:loginReason});}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.provisionLogin')}</legend><p>{t('payroll.loginHelp')}</p><TextField label={t('payroll.username')} required maxLength={64} autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)}/><TextField label={t('spending.reason')} required maxLength={500} value={loginReason} onChange={e=>setLoginReason(e.target.value)}/><Button type="submit">{t('payroll.provisionLogin')}</Button></fieldset></form>}
 {options.canManage&&<><form className="form-stack" onSubmit={change}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.changeSalary')}</legend><p>{t('payroll.salaryHelp')}</p><TextField label={t('payroll.salary')} required inputMode="decimal" dir="ltr" value={salary} onChange={e=>setSalary(e.target.value)}/><TextField label={t('payroll.effective')} required dir="ltr" pattern="[1-9][0-9]{3}-(0[1-9]|1[0-2])" value={effective} onChange={e=>setEffective(e.target.value)}/><PayingFields options={options} branch={branch} setBranch={setBranch} account={account} setAccount={setAccount}/><TextField label={t('spending.reason')} required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit">{t('payroll.changeSalary')}</Button></fieldset></form><form className="form-stack" onSubmit={e=>{e.preventDefault();op.submit(`payroll/employees/${id}/status`,{active:!history.data!.employee.active,reason:statusReason});}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t(history.data.employee.active?'payroll.deactivate':'payroll.reactivate')}</legend><p>{t('payroll.statusHelp')}</p><TextField label={t('spending.reason')} required maxLength={500} value={statusReason} onChange={e=>setStatusReason(e.target.value)}/><Button variant={history.data.employee.active?'danger':'success'} type="submit">{t(history.data.employee.active?'payroll.deactivate':'payroll.reactivate')}</Button></fieldset></form></>}</>}</Card>;
}
function Receipt({id}:{id:string}) {
 const {t}=useLocale(),receipt=useScoped<PayrollReceiptData>(`payroll/periods/${id}/receipt-data`);
 return <Card title={t('payroll.receipt')}>{receipt.error&&<p className="inline-notice inline-notice--danger" role="alert">{t(receipt.error)}</p>}{receipt.data&&<><p>{receipt.data.employeeCode} — {receipt.data.employeeName} — {receipt.data.month} — {receipt.data.branchCode} — {receipt.data.accountCode}</p><p>{formatDateOnly(receipt.data.settledOn)} — {receipt.data.noCash?t('payroll.noCash'):t(`finance.${receipt.data.method!}`)}</p><p>{t('payroll.salary')}: {money(receipt.data.basicSalary)} — {t('payroll.additions')}: {money(receipt.data.additions)} — {t('payroll.deductions')}: {money(receipt.data.deductions)}</p><p>{t('payroll.advances')}: {money(receipt.data.advances)} — {t('payroll.totalPaid')}: {money(receipt.data.finalPaid)}</p><p>{t('payroll.cashTotal')}: {money(receipt.data.totalCashOutflow)}</p>{receipt.data.adjustments.map((a,i)=><p key={i}>{t(`payroll.${a.kind}`)} — {money(a.amount)} — {a.reason}</p>)}{receipt.data.advanceLines.map((a,i)=><p key={i}>{formatDateOnly(a.paidOn)} — {money(a.amount)} — {a.reason}</p>)}</>}</Card>;
}
function PeriodDetail({id,options,op}:{id:string;options:PayrollOptions;op:Operation}) {
 const {t}=useLocale(),detail=useScoped<PayrollPeriodDetail>(`payroll/periods/${id}`);
 const [kind,setKind]=useState('ADDITION'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[advance,setAdvance]=useState(''),[advanceReason,setAdvanceReason]=useState(''),[date,setDate]=useState(cairoIsoDate()),[external,setExternal]=useState(''),[confirmed,setConfirmed]=useState(false),[advanceConfirmed,setAdvanceConfirmed]=useState(false),[settlementReason,setSettlementReason]=useState(''),[settlementDate,setSettlementDate]=useState(cairoIsoDate()),[settlementExternal,setSettlementExternal]=useState(''),[receipt,setReceipt]=useState(false);
 // A changing amount invalidates confirmation, including a concurrent actor's adjustment.
 useEffect(()=>{setConfirmed(false);},[detail.data?.period.remaining]);
 function adjust(e:FormEvent) {e.preventDefault();try {op.submit(`payroll/periods/${id}/adjustments`,{kind,amount:egpToPiastres(amount),reason});}catch {op.invalid();}}
 function paidAdvance(e:FormEvent) {e.preventDefault();if(!advanceConfirmed)return;try {op.submit(`payroll/periods/${id}/advances`,{amount:egpToPiastres(advance),paidOn:date,reason:advanceReason,externalReference:external});}catch {op.invalid();}}
 return <Card title={t('payroll.openMonth')}>{detail.error&&<p className="inline-notice inline-notice--danger" role="alert">{t(detail.error)}</p>}{detail.data&&<><h3>{detail.data.period.employeeCode} — {detail.data.period.fullName}</h3><Totals row={detail.data.period}/><p>{t('payroll.cutoff')}</p>{detail.data.adjustments.map(a=><p key={a.id}>{t(`payroll.${a.kind}`)} — {money(a.amount)} — {a.actor} — {a.reason}</p>)}{detail.data.advances.map(a=><p key={a.id}>{t('payroll.advance')} — {formatDateOnly(a.paidOn)} — {money(a.amount)} — {a.accountCode} — {t(`finance.${a.method}`)} — {a.actor} — {a.reason} — {a.externalReference}</p>)}{detail.data.settlement&&<><p>{formatDateOnly(detail.data.settlement.settledOn)} — {money(detail.data.settlement.amount)} — {detail.data.settlement.actor} — {detail.data.settlement.reason} — {detail.data.settlement.externalReference}</p><Button onClick={()=>setReceipt(!receipt)}>{t('payroll.receipt')}</Button>{receipt&&<Receipt id={id}/>}</>}
 {detail.data.period.state==='UNPAID'&&<>{detail.data.period.month===thisMonth()&&<>{options.canManage&&<form className="form-stack" onSubmit={adjust}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.adjust')}</legend><SelectField label={t('payroll.kind')} value={kind} onChange={e=>setKind(e.target.value)}>{(['ADDITION','DEDUCTION','PENALTY'] as const).map(k=><option key={k} value={k}>{t(`payroll.${k}`)}</option>)}</SelectField><TextField label={t('spending.amount')} required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><TextField label={t('spending.reason')} required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit">{t('payroll.adjust')}</Button></fieldset></form>}{options.canPay&&<form className="form-stack" onSubmit={paidAdvance}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.advance')}</legend><TextField label={t('spending.amount')} required inputMode="decimal" value={advance} onChange={e=>setAdvance(e.target.value)}/><DateField label={t('spending.date')} required value={date} onValueChange={setDate}/><TextField label={t('spending.reason')} required maxLength={500} value={advanceReason} onChange={e=>setAdvanceReason(e.target.value)}/><TextField label={t('spending.external')} maxLength={120} value={external} onChange={e=>setExternal(e.target.value)}/><label className="choice-field"><input type="checkbox" required checked={advanceConfirmed} onChange={e=>setAdvanceConfirmed(e.target.checked)}/>{t('payroll.confirmAdvance')}</label><Button type="submit">{t('payroll.advance')}</Button></fieldset></form>}</>}
 {options.canPay&&<form className="form-stack" onSubmit={e=>{e.preventDefault();if(!confirmed)return;op.submit(`payroll/periods/${id}/settlements`,{amount:detail.data!.period.remaining,settledOn:settlementDate,reason:settlementReason,externalReference:settlementExternal});}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t(detail.data.period.remaining==='0'?'payroll.zeroSettle':'payroll.settle')}</legend><p>{money(detail.data.period.remaining)} — {detail.data.period.branchCode} — {detail.data.period.accountCode}</p><DateField label={t('spending.date')} required value={settlementDate} onValueChange={setSettlementDate}/><TextField label={t('spending.reason')} required maxLength={500} value={settlementReason} onChange={e=>setSettlementReason(e.target.value)}/><TextField label={t('spending.external')} maxLength={120} value={settlementExternal} onChange={e=>setSettlementExternal(e.target.value)}/><label className="choice-field"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('payroll.confirm')}</label><Button type="submit">{t(detail.data.period.remaining==='0'?'payroll.zeroSettle':'payroll.settle')}</Button></fieldset></form>}</>}</>}</Card>;
}
export function PayrollScreen() {
 const {t}=useLocale(),options=useScoped<PayrollOptions>('payroll/options');
 const [month,setMonth]=useState(thisMonth()),[draft,setDraft]=useState(thisMonth()),[branch,setBranch]=useState(''),[offset,setOffset]=useState(0),[employee,setEmployee]=useState<string|null>(null),[period,setPeriod]=useState<string|null>(null),[revision,setRevision]=useState(0),[secret,setSecret]=useState<{accountId:string;temporaryPassword:string|null}|null>(null);
 const rows=useScoped<PayrollPage>(`payroll?month=${month}&limit=20&offset=${offset}${branch?`&branchId=${branch}`:''}`);
 const op=useFinancialOperation(result=>{rows.reload();options.reload();setRevision(r=>r+1);if(result&&typeof result==='object'&&'accountId' in result&&typeof result.accountId==='string'&&'temporaryPassword' in result)setSecret({accountId:result.accountId,temporaryPassword:typeof result.temporaryPassword==='string'?result.temporaryPassword:null});});
 useEffect(()=>{const clear=()=>{setEmployee(null);setPeriod(null);setSecret(null);setRevision(r=>r+1);};window.addEventListener('blur',clear);window.addEventListener('nursery:scope-refresh',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);window.removeEventListener('nursery:scope-refresh',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 useEffect(()=>{if(options.error||rows.error){setEmployee(null);setPeriod(null);setSecret(null);}},[options.error,rows.error]);
 return <main className="organization-page"><PageHeader description={t('payroll.help')} title={t('payroll.title')} icon="wallet" /><OperationNotice op={op}/>{(options.error||rows.error)&&<p className="inline-notice inline-notice--danger" role="alert">{t(options.error||rows.error!)}</p>}{options.data&&<>{(!options.data.modules.payroll||!options.data.modules.finance)&&<p className="inline-notice" role="status">{t('payroll.disabled')}</p>}{secret&&<div role="status"><p>{t('auth.accountId')}: {secret.accountId}</p><p>{t('payroll.secretHelp')}</p>{secret.temporaryPassword&&<code className="auth-temporary" dir="ltr">{secret.temporaryPassword}</code>}<Button onClick={()=>setSecret(null)}>{t('auth.dismissSecret')}</Button></div>}
 <form className="form-stack" onSubmit={e=>{e.preventDefault();if(!/^[1-9]\d{3}-(0[1-9]|1[0-2])$/.test(draft)){op.invalid();return;}setMonth(draft);setOffset(0);setEmployee(null);setPeriod(null);}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('payroll.roster')}</legend><TextField label={t('payroll.month')} hint={t('payroll.monthHint')} required dir="ltr" pattern="[1-9][0-9]{3}-(0[1-9]|1[0-2])" value={draft} onChange={e=>setDraft(e.target.value)}/><Button type="submit">{t('payroll.roster')}</Button></fieldset></form><SelectField label={t('payroll.branch')} disabled={op.locked} value={branch} onChange={e=>{setBranch(e.target.value);setOffset(0);setEmployee(null);setPeriod(null);}}><option value="">{t('spending.all')}</option>{options.data.branches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</SelectField>
 {options.data.canManage&&<ProfileForm key={revision} options={options.data} op={op}/>}{rows.data&&<><StatGrid label={t('payroll.title')}><StatCard tone="violet" icon="staff" label={t('payroll.totalSalary')} value={money(rows.data.totalSalary)} numeric/><StatCard tone="warning" icon="wallet" label={t('payroll.totalRemaining')} value={money(rows.data.totalRemaining)} numeric/><StatCard tone="success" icon="check" label={t('payroll.totalPaid')} value={money(rows.data.totalSettled)} numeric/></StatGrid>{!rows.data.items.length&&<EmptyState title={t('payroll.empty')} art="sky" />}{rows.data.items.map(row=><Card key={row.employeeId} title={`${row.employeeCode} — ${row.fullName}`}><Totals row={row}/><Button icon="arrow" variant="secondary" disabled={op.locked} onClick={()=>{setEmployee(row.employeeId);setPeriod(row.periodId);}}>{t('payroll.details')}</Button>{row.periodId?<Button disabled={op.locked} onClick={()=>{setEmployee(null);setPeriod(row.periodId);}}>{t('payroll.openMonth')}</Button>:options.data!.canManage&&row.active&&month<=thisMonth()&&<Button variant="secondary" disabled={op.locked} onClick={()=>op.submit('payroll/periods',{employeeId:row.employeeId,month})}>{t('payroll.prepare')}</Button>}</Card>)}<div className="action-group"><Button icon="back" variant="secondary" disabled={op.locked||offset===0} onClick={()=>setOffset(offset-20)}>{t('hub.previous')}</Button><Button icon="arrow" variant="secondary" disabled={op.locked||offset+20>=rows.data.totalCount} onClick={()=>setOffset(offset+20)}>{t('hub.next')}</Button></div></>}
 {employee&&<EmployeeDetail key={`${employee}-${revision}`} id={employee} options={options.data} op={op} openPeriod={setPeriod}/>} {period&&<PeriodDetail key={`${period}-${revision}`} id={period} options={options.data} op={op}/>}</>}</main>;
}
export function PayrollNavigation() {
 // Rendered inside the signed-in hub's destination grid, so it wears the same affordance as its
 // neighbours. The module/capability condition and the target route are unchanged.
 const {t}=useLocale(),options=useScoped<PayrollOptions>('payroll/options');return options.data?.modules.payroll&&options.data.modules.finance?<Link className="quick-action quick-action--mint" to="/administration/payroll"><span className="quick-action__icon"><Icon name="wallet"/></span><span className="quick-action__text"><strong>{t('payroll.title')}</strong></span><Icon name="chevron" className="icon--chevron"/></Link>:null;
}
