export const spendingEn={
 'organization.cap.expenses.manage':'Manage operating expenses','organization.cap.expenses.pay':'Record expense disbursements','organization.cap.expenses.approve':'Approve operating expenses',
 'transfer.choose':'Choose an account',
 'spending.reason':'Reason','spending.date':'Effective business date',
 'spending.saved':'Financial operation saved.',
 'closing.title':'Daily cash closing','closing.help':'Enter the actual physical count. Closing reports the difference and creates no cash movement. Reopening preserves the original count; posting a shortage/surplus is a separate sensitive action.',
 'closing.record':'Record physical count','closing.counted':'Counted amount (EGP)','closing.expected':'Expected cash','closing.difference':'Count difference','closing.revision':'Revision','closing.COUNTED':'Counted and closed','closing.REOPENED':'Reopened with original count retained',
 'closing.reopen':'Reopen this count','closing.adjust':'Post this difference today','closing.confirm':'I confirm this difference adjustment should change the recorded cash balance today.','closing.adjusted':'Difference adjustment posted on',
 'organization.cap.treasury.close':'Count and close cash accounts','closing.closedDate':'This posting affects a counted cash date. Obtain an authorized reopen or use an explicit current-date correction.','closing.reopenFirst':'This count is closed. Reopen it through an authorized reasoned action before recording another count.',
 'spending.approvalRequired':'This expense needs approval under the current nursery threshold before it can be paid.','spending.insufficientFunds':'The selected source account does not have enough recorded funds.',
 'spending.title':'Expenses','spending.create':'Create pending expense','spending.help':'Pending expenses do not move cash. Record payment only after money was actually disbursed. Payroll is recorded through its own source, not as a manual operating expense.',
 'spending.category':'Expense category','spending.classroom':'Classroom attribution','spending.branchCost':'Unattributed branch cost','spending.due':'Due date','spending.note':'Expense note','spending.amount':'Amount (EGP)',
 'spending.PENDING':'Pending','spending.APPROVED':'Approved','spending.PAID':'Paid','spending.CANCELLED':'Cancelled','spending.approve':'Approve expense','spending.cancel':'Cancel unpaid expense','spending.pay':'Record actual disbursement',
 'spending.pendingTotal':'Pending spending','spending.paidTotal':'Actual operating outflows','spending.details':'Documents and audit history','spending.close':'Close details','spending.destination':'Paying account','spending.confirm':'I confirm this money was actually paid from the selected account.',
 'spending.threshold':'Approval threshold (EGP; 0 disables)','spending.approver':'Approving capability','spending.configure':'Save approval settings','spending.approvalHelp':'Amounts strictly above an enabled threshold require scoped approval before settlement.',
 'spending.categoryCreate':'Create expense category','spending.external':'External reference','spending.all':'All states',
 'transfer.title':'Account transfers','transfer.source':'Source account','transfer.destination':'Destination account','transfer.help':'Record an externally completed internal transfer. This deducts the source and adds the destination atomically. Transfers are separate from collections and operating expenses.',
 'transfer.confirm':'I confirm the transfer actually occurred between these accounts.','transfer.record':'Record paired transfer','transfer.history':'Transfer history',
} as const;
export const spendingAr:Record<keyof typeof spendingEn,string>={
 'organization.cap.expenses.manage':'إدارة مصروفات التشغيل','organization.cap.expenses.pay':'تسجيل صرف المصروفات','organization.cap.expenses.approve':'اعتماد مصروفات التشغيل',
 'transfer.choose':'اختار حساب',
 'spending.reason':'السبب','spending.date':'التاريخ الفعلي للعملية',
 'spending.saved':'تم حفظ العملية المالية.',
 'closing.title':'جرد وقفل النقدية اليومي','closing.help':'اكتب الجرد الفعلي للفلوس. القفل بيعرض الفرق من غير حركة نقدية. إعادة الفتح بتحتفظ بالجرد الأصلي؛ تسجيل العجز أو الزيادة إجراء مالي حساس منفصل.',
 'closing.record':'تسجيل جرد فعلي','closing.counted':'المبلغ المعدود (جنيه)','closing.expected':'النقدية المتوقعة','closing.difference':'فرق الجرد','closing.revision':'المراجعة','closing.COUNTED':'اتجرد واتقفل','closing.REOPENED':'اتفتح تاني مع حفظ الجرد الأصلي',
 'closing.reopen':'إعادة فتح الجرد','closing.adjust':'تسجيل الفرق بتاريخ النهارده','closing.confirm':'بأكد إن تسوية فرق الجرد دي هتغير الرصيد النقدي المسجل النهارده.','closing.adjusted':'اتسجل فرق الجرد بتاريخ',
 'organization.cap.treasury.close':'جرد وقفل الحسابات النقدية','closing.closedDate':'العملية بتأثر على يوم اتجرد واتقفل. محتاجة إعادة فتح مصرح بها أو تصحيح صريح بتاريخ النهارده.','closing.reopenFirst':'الجرد ده مقفول. محتاج إعادة فتح مصرح بها وبسبب قبل تسجيل جرد جديد.',
 'spending.approvalRequired':'المصروف محتاج اعتماد حسب الحد الحالي للحضانة قبل الصرف.','spending.insufficientFunds':'الحساب المصدر مفيهوش رصيد مسجل كفاية للمبلغ.',
 'spending.title':'المصروفات','spending.create':'إضافة مصروف مستحق','spending.help':'المصروف المستحق مش بيحرك فلوس الخزنة. سجل الدفع بعد ما الفلوس اتصرفت فعلاً. المرتبات ليها سجلاتها الخاصة، مش مصروف تشغيل يدوي.',
 'spending.category':'بند المصروف','spending.classroom':'نسبة المصروف للفصل','spending.branchCost':'مصروف فرع من غير نسبة لفصل','spending.due':'تاريخ الاستحقاق','spending.note':'ملاحظة المصروف','spending.amount':'المبلغ (جنيه)',
 'spending.PENDING':'مستحق','spending.APPROVED':'معتمد','spending.PAID':'مدفوع','spending.CANCELLED':'ملغي','spending.approve':'اعتماد المصروف','spending.cancel':'إلغاء المصروف غير المدفوع','spending.pay':'تسجيل صرف فعلي',
 'spending.pendingTotal':'مصروفات مستحقة','spending.paidTotal':'مصروفات تشغيل اتصرفت فعلاً','spending.details':'المستندات وسجل الإجراءات','spending.close':'قفل التفاصيل','spending.destination':'الحساب اللي اتصرف منه','spending.confirm':'بأكد إن المبلغ اتدفع فعلاً من الحساب المحدد.',
 'spending.threshold':'حد اعتماد المصروفات (جنيه؛ صفر للتعطيل)','spending.approver':'صلاحية الاعتماد','spending.configure':'حفظ إعدادات الاعتماد','spending.approvalHelp':'المبلغ الأكبر من الحد المفعّل محتاج اعتماد في نفس النطاق قبل الصرف.',
 'spending.categoryCreate':'إضافة بند مصروف','spending.external':'مرجع خارجي','spending.all':'كل الحالات',
 'transfer.title':'تحويلات بين الحسابات','transfer.source':'الحساب المصدر','transfer.destination':'الحساب المستلم','transfer.help':'سجل تحويل داخلي اتنفذ خارج البرنامج. بيخصم من المصدر ويضيف للمستلم في عملية واحدة. التحويلات منفصلة عن التحصيل ومصروفات التشغيل.',
 'transfer.confirm':'بأكد إن التحويل حصل فعلاً بين الحسابين.','transfer.record':'تسجيل التحويل بالقيدين','transfer.history':'سجل التحويلات',
};
