import { useEffect,useState,type FormEvent } from 'react';
import { Link } from 'react-router';
import { capabilityKeys,type Expense,type ExpensePage,type ExpenseDocument,type SpendingOptions } from '@nursery/contracts';
import { cairoIsoDate,egpToPiastres,formatEgp,formatDateOnly,piastres } from '@nursery/domain';
import { Button,DateField,SelectField,TextField } from '../../components/controls.js';
import { Card } from '../../components/surfaces.js';
import { StatCard,StatGrid, PageHeader , Badge } from '../../components/data-display.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import { useAuth } from '../auth/AuthProvider.js';
import { useScoped } from '../children/scoped.js';
import { useFinancialOperation } from './use-operation.js';

const money=(v:string)=>formatEgp(piastres(BigInt(v)));
type History={events:{id:string;kind:'APPROVED'|'CANCELLED';reason:string;actor:string}[];settlements:{id:string;amount:string;paidOn:string;method:'CASH'|'BANK'|'WALLET';accountCode:string;reason:string;actor:string}[]};
export function OperationNotice({op}:{op:ReturnType<typeof useFinancialOperation>}) {
 const {t}=useLocale();return <>{op.message&&<p className="inline-notice" role={op.uncertain?'alert':'status'}>{t(op.message)}</p>}{op.uncertain&&<><div className="action-group"><Button variant="secondary" disabled={op.busy} onClick={()=>{void op.check();}}>{t('finance.check')}</Button>{op.canRetry&&<Button loading={op.busy} icon="refresh" variant="secondary" disabled={op.busy} onClick={op.retry}>{t('finance.retry')}</Button>}</div></>}</>;
}
function ExpenseDetails({expense,onClose}:{expense:Expense;onClose:()=>void}) {
 const {t}=useLocale(),auth=useAuth(),history=useScoped<History>(`expenses/${expense.id}/history`);
 const canDocs=auth.session?.account.capabilities.includes('documents.manage');
 return <Card title={t('spending.details')}><Button variant="secondary" onClick={onClose}>{t('spending.close')}</Button>{history.error&&<p className="inline-notice inline-notice--danger" role="alert">{t(history.error)}</p>}
 {history.data?.events.map(e=><p key={e.id}>{t(`spending.${e.kind}`)} — {e.actor} — {e.reason}</p>)}{history.data?.settlements.map(s=><p key={s.id}><Badge tone={'success'}>{t('spending.PAID')}</Badge> — {formatDateOnly(s.paidOn)} — {money(s.amount)} — {s.accountCode} — {t(`finance.${s.method}`)} — {s.actor} — {s.reason}</p>)}
 {canDocs&&<ExpenseDocuments expenseId={expense.id}/>}</Card>;
}
function ExpenseDocuments({expenseId}:{expenseId:string}) {
 const {t}=useLocale(),auth=useAuth(),docs=useScoped<ExpenseDocument[]>(`expenses/${expenseId}/documents`);
 const [name,setName]=useState(''),[file,setFile]=useState<File|null>(null),[reason,setReason]=useState('');
 const op=useFinancialOperation(()=>{docs.reload();setFile(null);setName('');});const canManage=auth.session?.account.capabilities.includes('expenses.manage');
 async function upload(e:FormEvent) {
  e.preventDefault();if(!file||op.locked) return;
  try {const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});op.submit(`expenses/${expenseId}/documents`,{name,expiresOn:null,mimeType:file.type,contentBase64});}catch {op.invalid();}
 }
 return <><OperationNotice op={op}/>{docs.error&&<p className="inline-notice inline-notice--danger" role="alert">{t(docs.error)}</p>}<ul className="record-list">{docs.data?.map(d=><li key={d.id}>{d.name} <a className="button button--outline button--compact" href={`/api/v1/expense-documents/${d.id}/download`}>{t('children.download')}</a>{canManage&&<Button icon="trash" variant="danger" disabled={op.locked||!reason.trim()} onClick={()=>op.submit(`expense-documents/${d.id}/retire`,{reason})}>{t('children.retire')}</Button>}</li>)}</ul>
 {canManage&&<><TextField label={t('spending.reason')} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/><form className="form-stack" onSubmit={e=>{void upload(e);}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('children.documents')}</legend><p>{t('children.fileHelp')}</p><TextField label={t('finance.name')} required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><TextField label={t('children.documents')} type="file" required accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/><Button icon="upload" type="submit">{t('children.upload')}</Button></fieldset></form></>}</>;
}
export function ExpensesScreen() {
 const {t}=useLocale(),options=useScoped<SpendingOptions>('expenses/options');const [branch,setBranch]=useState(''),[state,setState]=useState(''),[offset,setOffset]=useState(0);
 const branchId=branch||options.data?.branches[0]?.id||'',rows=useScoped<ExpensePage>(`expenses?limit=20&offset=${offset}${branchId?`&branchId=${branchId}`:''}${state?`&state=${state}`:''}`);
 const [category,setCategory]=useState(''),[classroom,setClassroom]=useState(''),[amount,setAmount]=useState(''),[due,setDue]=useState(cairoIsoDate()),[note,setNote]=useState('');
 const [code,setCode]=useState(''),[name,setName]=useState(''),[threshold,setThreshold]=useState(''),[approver,setApprover]=useState('expenses.approve');
 const [selected,setSelected]=useState<Expense|null>(null),[details,setDetails]=useState<Expense|null>(null),[action,setAction]=useState<'pay'|'approve'|'cancel'>('pay'),[account,setAccount]=useState(''),[date,setDate]=useState(cairoIsoDate()),[reason,setReason]=useState(''),[external,setExternal]=useState(''),[confirmed,setConfirmed]=useState(false);
 const op=useFinancialOperation(()=>{rows.reload();options.reload();setSelected(null);setDetails(null);setConfirmed(false);});
 useEffect(()=>{const clear=()=>{setSelected(null);setDetails(null);setNote('');setReason('');setConfirmed(false);};window.addEventListener('blur',clear);window.addEventListener('nursery:scope-refresh',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('blur',clear);window.removeEventListener('nursery:scope-refresh',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 useEffect(()=>{if(options.error||options.data&&!options.data.branches.some(b=>b.id===branchId)||rows.data&&selected&&!rows.data.items.some(e=>e.id===selected.id)) {setSelected(null);setDetails(null);setConfirmed(false);}},[options.error,options.data,rows.data,branchId,selected]);
 function create(e:FormEvent) {e.preventDefault();try {op.submit('expenses',{branchId,classroomId:classroom||null,categoryId:category||options.data?.categories[0]?.id,amount:egpToPiastres(amount),dueOn:due,note});}catch {op.invalid();}}
 function select(e:Expense,next:'pay'|'approve'|'cancel') {setSelected(e);setDetails(null);setAction(next);setReason('');setConfirmed(false);setAccount(options.data?.accounts.find(a=>a.branchId===e.branchId&&a.type==='CASH')?.id??'');}
 function settle(e:FormEvent) {e.preventDefault();if(!selected) return;const a=options.data?.accounts.find(a=>a.id===account);if(action==='pay'&&(!confirmed||!a)) return;op.submit(`expenses/${selected.id}/${action}`,action==='pay'?{reason,accountId:account,method:a!.type,paidOn:date,externalReference:external}:{reason});}
 return <main className="organization-page"><PageHeader description={t('spending.help')} actions={<><div className="action-group"><Link className="button button--outline" to="/administration/transfers">{t('transfer.title')}</Link><Link className="button button--outline" to="/administration/corrections">{t('corrections.title')}</Link></div></>} title={t('spending.title')} icon="wallet" /><OperationNotice op={op}/>
 {(options.error||rows.error)&&<p className="inline-notice inline-notice--danger" role="alert">{t(options.error||rows.error!)}</p>}{options.data&&<><div className="filter-bar"><SelectField label={t('finance.branch')} value={branchId} disabled={op.locked} onChange={e=>{setBranch(e.target.value);setClassroom('');setOffset(0);setSelected(null);setDetails(null);}}>{options.data.branches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</SelectField>
 <SelectField label={t('collections.status')} value={state} disabled={op.locked} onChange={e=>{setState(e.target.value);setOffset(0);setSelected(null);setDetails(null);}}><option value="">{t('spending.all')}</option>{(['PENDING','APPROVED','PAID','CORRECTED','REVERSED','CANCELLED'] as const).map(s=><option key={s} value={s}>{t(`spending.${s}`)}</option>)}</SelectField></div>
 {options.data.canManage&&<form className="form-stack" onSubmit={create}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('spending.create')}</legend><SelectField label={t('spending.category')} required value={category||options.data.categories[0]?.id||''} onChange={e=>setCategory(e.target.value)}>{options.data.categories.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</SelectField><SelectField label={t('spending.classroom')} value={classroom} onChange={e=>setClassroom(e.target.value)}><option value="">{t('spending.branchCost')}</option>{options.data.classrooms.filter(c=>c.branchId===branchId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><TextField label={t('spending.amount')} required inputMode="decimal" dir="ltr" value={amount} onChange={e=>setAmount(e.target.value)}/><DateField label={t('spending.due')} required value={due} onValueChange={setDue}/><TextField label={t('spending.note')} required maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/><Button icon="plus" type="submit">{t('spending.create')}</Button></fieldset></form>}
 {rows.data&&<><StatGrid label={t('spending.title')}><StatCard tone="warning" icon="wallet" label={t('spending.pendingTotal')} value={money(rows.data.totalPending)} numeric/><StatCard tone="success" icon="check" label={t('spending.paidTotal')} value={money(rows.data.totalPaid)} numeric/></StatGrid>{rows.data.items.map(e=><Card key={e.id} title={e.categoryName}><p>{money(e.amount)} — {formatDateOnly(e.dueOn)} — <Badge tone={e.state==='PAID'?'success':e.state==='PENDING'?'warning':'neutral'}>{t(`spending.${e.state}`)}</Badge></p>{e.state==='CORRECTED'&&<p>{money(e.paidAmount)}</p>}<p>{e.note}</p>{e.correctionReason&&<p>{e.correctionReason}</p>}<Button icon="arrow" variant="secondary" disabled={op.locked} onClick={()=>{setDetails(e);setSelected(null);}}>{t('spending.details')}</Button>{(e.state==='PENDING'||e.state==='APPROVED')&&<><div className="action-group">{options.data!.canPay&&<Button disabled={op.locked} onClick={()=>select(e,'pay')}>{t('spending.pay')}</Button>}{e.state==='PENDING'&&options.data!.canApprove&&<Button icon="check" disabled={op.locked} onClick={()=>select(e,'approve')}>{t('spending.approve')}</Button>}{options.data!.canManage&&<Button variant="danger" disabled={op.locked} onClick={()=>select(e,'cancel')}>{t('spending.cancel')}</Button>}</div></>}</Card>)}<div className="action-group"><Button icon="back" variant="secondary" disabled={offset===0||op.locked} onClick={()=>setOffset(offset-20)}>{t('hub.previous')}</Button><Button icon="arrow" variant="secondary" disabled={offset+20>=rows.data.totalCount||op.locked} onClick={()=>setOffset(offset+20)}>{t('hub.next')}</Button></div></>}
 {selected&&<form className="form-stack" onSubmit={settle}><fieldset className="organization-fields" disabled={op.locked}><legend>{t(`spending.${action==='pay'?'pay':action==='approve'?'approve':'cancel'}`)} — {selected.categoryName}</legend><p>{money(selected.amount)}</p><TextField label={t('spending.reason')} required value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/>{action==='pay'&&<><SelectField label={t('spending.destination')} required value={account} onChange={e=>setAccount(e.target.value)}>{options.data.accounts.filter(a=>a.branchId===selected.branchId).map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField><DateField label={t('spending.date')} required value={date} onValueChange={setDate}/><TextField label={t('spending.external')} maxLength={120} value={external} onChange={e=>setExternal(e.target.value)}/><label className="choice-field"><input type="checkbox" checked={confirmed} required onChange={e=>setConfirmed(e.target.checked)}/>{t('spending.confirm')}</label><p>{t('spending.approvalHelp')}</p></>}<Button variant={action==='cancel'?'danger':'primary'} type="submit">{t(action==='pay'?'spending.pay':action==='approve'?'spending.approve':'spending.cancel')}</Button></fieldset></form>}
 {details&&<ExpenseDetails key={details.id} expense={details} onClose={()=>setDetails(null)}/>}
 {options.data.canManage&&<form className="form-stack" onSubmit={e=>{e.preventDefault();op.submit('expenses/categories',{code,name});}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('spending.categoryCreate')}</legend><TextField label={t('finance.code')} required maxLength={32} value={code} onChange={e=>setCode(e.target.value)}/><TextField label={t('finance.name')} required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><Button type="submit">{t('spending.categoryCreate')}</Button></fieldset></form>}
 {options.data.canConfigure&&<form className="form-stack" onSubmit={e=>{e.preventDefault();try {op.submit('expenses/settings',{expectedVersion:options.data!.settings.version,approvalThreshold:egpToPiastres(threshold),approvingCapability:approver,reason});}catch {op.invalid();}}}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('spending.configure')}</legend><p>{t('spending.approvalHelp')} {money(options.data.settings.approvalThreshold)} — {options.data.settings.approvingCapability}</p><TextField label={t('spending.threshold')} required inputMode="decimal" value={threshold} onChange={e=>setThreshold(e.target.value)}/><SelectField label={t('spending.approver')} value={approver} onChange={e=>setApprover(e.target.value)}>{capabilityKeys.map(c=><option key={c} value={c}>{t(`organization.cap.${c}`)}</option>)}</SelectField><TextField label={t('spending.reason')} required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit">{t('spending.configure')}</Button></fieldset></form>}</>}
 </main>;
}
export function TransfersScreen() {
 const {t}=useLocale(),options=useScoped<SpendingOptions>('expenses/options'),history=useScoped<{id:string;sourceCode:string;destinationCode:string;amount:string;effectiveOn:string;reason:string}[]>('finance/transfers?limit=20');
 const [source,setSource]=useState(''),[destination,setDestination]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(cairoIsoDate()),[reason,setReason]=useState(''),[external,setExternal]=useState(''),[confirmed,setConfirmed]=useState(false);
 const op=useFinancialOperation(()=>{history.reload();options.reload();setConfirmed(false);});
 function submit(e:FormEvent) {e.preventDefault();if(!confirmed) return;try {op.submit('finance/transfers',{sourceAccountId:source,destinationAccountId:destination,amount:egpToPiastres(amount),effectiveOn:date,reason,externalReference:external});}catch {op.invalid();}}
 return <main className="organization-page"><PageHeader description={t('transfer.help')} actions={<><div className="action-group"><Link className="button button--outline" to="/administration/expenses">{t('spending.title')}</Link><Link className="button button--outline" to="/administration/corrections">{t('corrections.title')}</Link></div></>} title={t('transfer.title')} icon="wallet" /><OperationNotice op={op}/>{(options.error||history.error)&&<p className="inline-notice inline-notice--danger" role="alert">{t(options.error||history.error!)}</p>}
 {options.data?.canTransfer&&<form className="form-stack" onSubmit={submit}><fieldset className="organization-fields" disabled={op.locked}><legend>{t('transfer.record')}</legend>{(['source','destination'] as const).map(key=><SelectField key={key} label={t(`transfer.${key}`)} required value={key==='source'?source:destination} onChange={e=>(key==='source'?setSource:setDestination)(e.target.value)}><option value="">{t('transfer.choose')}</option>{options.data!.accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {t(`finance.${a.type}`)}</option>)}</SelectField>)}<TextField label={t('spending.amount')} required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><DateField label={t('spending.date')} required value={date} onValueChange={setDate}/><TextField label={t('spending.reason')} required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><TextField label={t('spending.external')} maxLength={120} value={external} onChange={e=>setExternal(e.target.value)}/><label className="choice-field"><input type="checkbox" checked={confirmed} required onChange={e=>setConfirmed(e.target.checked)}/>{t('transfer.confirm')}</label><Button icon="check" type="submit">{t('transfer.record')}</Button></fieldset></form>}
 {history.data?.map(row=><Card key={row.id} title={`${row.sourceCode} → ${row.destinationCode}`}><p>{money(row.amount)} — {formatDateOnly(row.effectiveOn)}</p><p>{row.reason}</p></Card>)}
 </main>;
}
