import { useRef,useState,type FormEvent } from 'react';
import { Link,useSearchParams } from 'react-router';
import type { Activity,BusSubscription,TransportOptions } from '@nursery/contracts';
import { cairoIsoDate,egpToPiastres,formatDateOnly,formatEgp,piastres } from '@nursery/domain';
import { Button,DateField,SelectField,TextField } from '../../components/controls.js';
import { Card } from '../../components/surfaces.js';
import { LanguageSwitcher } from '../../layout/AppShell.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import type { MessageKey } from '../../i18n/catalogs.js';
import { useAuth } from '../auth/AuthProvider.js';
import { AuthError } from '../auth/client.js';
import { errorKey,useScoped } from '../children/scoped.js';

type OperationBody={operationId:string}&Record<string,unknown>;
function useOperation(after:()=>void) {
 const auth=useAuth(),{t}=useLocale(),pending=useRef<{path:string;body:OperationBody}|null>(null);const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[canRetry,setCanRetry]=useState(false),[message,setMessage]=useState<MessageKey|null>(null);
 async function send() {if(!pending.current)return;setBusy(true);setMessage(null);try{await auth.client.business(pending.current.path,'POST',pending.current.body);pending.current=null;setUncertain(false);setCanRetry(false);setMessage('transport.saved');after();}catch(error){auth.handleError(error);if(!(error instanceof AuthError)||['INTERNAL_ERROR','DATABASE_UNAVAILABLE'].includes(error.detail.code)){setUncertain(true);setCanRetry(false);setMessage('finance.uncertain');}else{pending.current=null;setUncertain(false);setMessage(errorKey(error));}}finally{setBusy(false);}}
 function begin(path:string,body:OperationBody){if(pending.current||busy)return;pending.current={path,body};void send();}
 async function check(){if(!pending.current)return;setBusy(true);try{const result=await auth.client.business<{status:'COMMITTED'|'NOT_FOUND'}>(`finance/operations/${pending.current.body.operationId}`);if(result.status==='COMMITTED'){pending.current=null;setUncertain(false);setCanRetry(false);setMessage('transport.saved');after();}else{setCanRetry(true);setMessage('finance.notFound');}}catch(error){auth.handleError(error);setMessage(errorKey(error));}finally{setBusy(false);}}
 return {begin,busy,uncertain,message,controls:uncertain&&<><Button disabled={busy} onClick={()=>{void check();}}>{t('finance.check')}</Button>{canRetry&&<Button disabled={busy} onClick={()=>{void send();}}>{t('finance.retry')}</Button>}</>};
}
const money=(amount:string)=>formatEgp(piastres(BigInt(amount)));
function Notice({message,uncertain}:{message:MessageKey|null;uncertain:boolean}){const {t}=useLocale();return message?<p role={uncertain?'alert':'status'}>{t(message)}</p>:null;}

function BusCard({item,canManage,enabled,reload}:{item:BusSubscription;canManage:boolean;enabled:boolean;reload:()=>void}){
 const {t}=useLocale();const [reason,setReason]=useState('');const op=useOperation(reload);
 return <Card title={`${item.childCode} — ${item.childName}`}><p><bdi dir="ltr">{formatDateOnly(item.periodStart)} — {formatDateOnly(item.periodEnd)}</bdi></p><p>{item.noFee?t('transport.noFee'):`${money(item.amount)} — ${t(item.paid?'transport.paid':'transport.unpaid')}`}</p><p>{t(item.administrativePermission?'transport.permissionOn':'transport.permissionOff')} · {t(item.eligible?'transport.eligible':'transport.notEligible')}</p><Notice message={op.message} uncertain={op.uncertain}/>{op.controls}{canManage&&enabled&&<><TextField label={t('transport.permissionReason')} maxLength={500} required value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={op.busy||!reason.trim()} onClick={()=>op.begin(`transport/subscriptions/${item.id}/permission`,{operationId:crypto.randomUUID(),expectedVersion:item.version,enabled:!item.administrativePermission,reason})}>{t(item.administrativePermission?'transport.block':'transport.allow')}</Button></>}</Card>;
}
function BusList({canManage,enabled}:{canManage:boolean;enabled:boolean}){const {t}=useLocale();const state=useScoped<BusSubscription[]>('transport/subscriptions?limit=100&offset=0');return <section><h2>{t('transport.busTitle')}</h2>{state.error&&<p role="alert">{t(state.error)}</p>}{!state.data&&!state.error&&<p role="status">{t('state.loading')}</p>}{state.data?.length===0&&<p>{t('transport.empty')}</p>}<div className="organization-records">{state.data?.map(x=><BusCard key={x.id} item={x} canManage={canManage} enabled={enabled} reload={state.reload}/>)}</div></section>;}

function ActivityCard({activity,canManage,canFinance,enabled,reload}:{activity:Activity;canManage:boolean;canFinance:boolean;enabled:boolean;reload:()=>void}){
 const {t}=useLocale();const [consentReason,setConsentReason]=useState(''),[cancelReason,setCancelReason]=useState('');const op=useOperation(reload);
 return <Card title={activity.title}><p>{activity.details}</p><p><bdi dir="ltr">{formatDateOnly(activity.eventDate)}</bdi> · {activity.fee==='0'?t('transport.noFee'):money(activity.fee)} · {t(activity.status==='ACTIVE'?'transport.active':'transport.cancelled')}</p><Notice message={op.message} uncertain={op.uncertain}/>{op.controls}{canManage&&enabled&&activity.status==='ACTIVE'&&<TextField label={t('transport.consentReason')} maxLength={500} value={consentReason} onChange={e=>setConsentReason(e.target.value)}/>}<ul>{activity.items.map(item=><li key={item.childId}><strong>{item.childCode} — {item.childName}</strong><br/>{t('transport.selected')} · {t(item.noFee?'transport.noFee':item.paid?'transport.paid':'transport.unpaid')} · {t(item.consented?'transport.consentYes':'transport.consentNo')} · {t(item.participating?'transport.participating':'transport.notParticipating')}{canFinance&&item.installmentId&&!item.paid&&<> · <Link to={`/administration/collections?childId=${item.childId}`}>{t('transport.payment')}</Link></>}{canManage&&enabled&&activity.status==='ACTIVE'&&<><br/><Button disabled={op.busy||!consentReason.trim()} onClick={()=>op.begin(`activities/${activity.id}/children/${item.childId}/consent`,{operationId:crypto.randomUUID(),consented:!item.consented,reason:consentReason})}>{t(item.consented?'transport.withdrawConsent':'transport.recordConsent')}</Button></>}</li>)}</ul>{canManage&&enabled&&activity.status==='ACTIVE'&&<><TextField label={t('transport.cancelReason')} maxLength={500} value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/><Button variant="danger" disabled={op.busy||!cancelReason.trim()} onClick={()=>op.begin(`activities/${activity.id}/cancel`,{operationId:crypto.randomUUID(),reason:cancelReason})}>{t('transport.cancel')}</Button></>}</Card>;
}
function ActivityList({canManage,canFinance,enabled}:{canManage:boolean;canFinance:boolean;enabled:boolean}){const {t}=useLocale();const state=useScoped<Activity[]>('activities?limit=100&offset=0');return <section><h2>{t('transport.activities')}</h2>{state.error&&<p role="alert">{t(state.error)}</p>}{!state.data&&!state.error&&<p role="status">{t('state.loading')}</p>}{state.data?.length===0&&<p>{t('transport.noActivities')}</p>}<div className="organization-records">{state.data?.map(a=><ActivityCard key={a.id} activity={a} canManage={canManage} canFinance={canFinance} enabled={enabled} reload={state.reload}/>)}</div></section>;}

function BusForm({options,initialChildId}:{options:TransportOptions;initialChildId:string|null}){
 const {t}=useLocale();const children=options.children;const categories=options.categories.filter(c=>c.kind==='BUS');const [childId,setChild]=useState(children.some(c=>c.id===initialChildId)?initialChildId!:children[0]?.id??''),[categoryId,setCategory]=useState(categories[0]?.id??''),[start,setStart]=useState(cairoIsoDate()),[end,setEnd]=useState(cairoIsoDate()),[due,setDue]=useState(cairoIsoDate()),[amount,setAmount]=useState('0.00'),[permission,setPermission]=useState(true),[invalid,setInvalid]=useState(false);const op=useOperation(()=>window.dispatchEvent(new Event('nursery:scope-refresh')));
 function submit(e:FormEvent){e.preventDefault();try{op.begin('transport/subscriptions',{operationId:crypto.randomUUID(),childId,categoryId,periodStart:start,periodEnd:end,amount:egpToPiastres(amount),dueOn:due,administrativePermission:permission});setInvalid(false);}catch{setInvalid(true);}}
 return <Card title={t('transport.busCreate')}>{invalid&&<p role="alert">{t('transport.invalid')}</p>}<Notice message={op.message} uncertain={op.uncertain}/>{op.controls}<form onSubmit={submit}><fieldset className="organization-fields" disabled={op.busy||op.uncertain}><SelectField label={t('transport.child')} required value={childId} onChange={e=>setChild(e.target.value)}><option value="">{t('transport.pickOne')}</option>{children.map(c=><option key={c.id} value={c.id}>{c.code} — {c.fullName}</option>)}</SelectField><SelectField label={t('transport.category')} required value={categoryId} onChange={e=>setCategory(e.target.value)}><option value="">{t('transport.pickOne')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</SelectField><DateField label={t('transport.periodStart')} required value={start} onValueChange={setStart}/><DateField label={t('transport.periodEnd')} required value={end} onValueChange={setEnd}/><DateField label={t('transport.due')} required value={due} onValueChange={setDue}/><TextField label={t('transport.amount')} inputMode="decimal" dir="ltr" required value={amount} onChange={e=>setAmount(e.target.value)}/><label><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/>{t('transport.permission')}</label><Button type="submit">{t('transport.busCreate')}</Button></fieldset></form></Card>;
}

function ActivityForm({options}:{options:TransportOptions}){
 const {t}=useLocale();const categories=options.categories.filter(c=>c.kind==='TRIP');const [branchId,setBranch]=useState(options.branches[0]?.id??''),[categoryId,setCategory]=useState(categories[0]?.id??''),[title,setTitle]=useState(''),[details,setDetails]=useState(''),[date,setDate]=useState(cairoIsoDate()),[due,setDue]=useState(cairoIsoDate()),[fee,setFee]=useState('0.00'),[selected,setSelected]=useState<string[]>([]),[invalid,setInvalid]=useState(false);const op=useOperation(()=>window.dispatchEvent(new Event('nursery:scope-refresh')));const children=options.children.filter(c=>c.branchId===branchId);
 function submit(e:FormEvent){e.preventDefault();try{if(!selected.length)throw new Error();op.begin('activities',{operationId:crypto.randomUUID(),branchId,categoryId,title,details,eventDate:date,fee:egpToPiastres(fee),dueOn:due,childIds:selected});setInvalid(false);}catch{setInvalid(true);}}
 return <Card title={t('transport.activityCreate')}>{invalid&&<p role="alert">{t(selected.length?'transport.invalid':'transport.noneSelected')}</p>}<Notice message={op.message} uncertain={op.uncertain}/>{op.controls}<form onSubmit={submit}><fieldset className="organization-fields" disabled={op.busy||op.uncertain}><SelectField label={t('transport.branch')} required value={branchId} onChange={e=>{setBranch(e.target.value);setSelected([]);}}>{options.branches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</SelectField><SelectField label={t('transport.category')} required value={categoryId} onChange={e=>setCategory(e.target.value)}><option value="">{t('transport.pickOne')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</SelectField><TextField label={t('transport.titleField')} required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/><TextField label={t('transport.details')} required maxLength={500} value={details} onChange={e=>setDetails(e.target.value)}/><DateField label={t('transport.eventDate')} required value={date} onValueChange={setDate}/><DateField label={t('transport.due')} required value={due} onValueChange={setDue}/><TextField label={t('transport.fee')} inputMode="decimal" dir="ltr" required value={fee} onChange={e=>setFee(e.target.value)}/><fieldset><legend>{t('transport.children')}</legend>{children.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>{c.code} — {c.fullName}</label>)}</fieldset><Button type="submit">{t('transport.activityCreate')}</Button></fieldset></form></Card>;
}

function ManagedBody({rosterOnly,canTransportRead,canActivitiesRead,canTransportManage,canActivitiesManage,canFinance}:{rosterOnly:boolean;canTransportRead:boolean;canActivitiesRead:boolean;canTransportManage:boolean;canActivitiesManage:boolean;canFinance:boolean}){
 const {t}=useLocale();const [query]=useSearchParams();const options=useScoped<TransportOptions>('transport/options');if(!options.data)return <>{options.error?<p role="alert">{t(options.error)}</p>:<p role="status">{t('state.loading')}</p>}{canActivitiesRead&&<ActivityList canManage={false} canFinance={canFinance} enabled={false}/>}</>;
 return <>{!rosterOnly&&canTransportRead&&<BusList canManage={canTransportManage} enabled={options.data.modules.transport}/>} {!rosterOnly&&canTransportManage&&(options.data.modules.transport?<BusForm options={options.data} initialChildId={query.get('childId')}/>:<p role="status">{t('transport.disabled')}</p>)}{canActivitiesRead&&<ActivityList canManage={canActivitiesManage} canFinance={canFinance} enabled={options.data.modules.activities}/>} {canActivitiesManage&&(options.data.modules.activities?<ActivityForm options={options.data}/>:<p role="status">{t('activities.disabled')}</p>)}</>;
}
export function TransportScreen({rosterOnly=false}:{rosterOnly?:boolean}){
 const {t}=useLocale(),auth=useAuth(),caps=auth.session!.account.capabilities;const canTransportRead=caps.includes('transport.read'),canActivitiesRead=caps.includes('activities.read'),canTransportManage=caps.includes('transport.manage'),canActivitiesManage=caps.includes('activities.manage'),managed=canTransportManage||canActivitiesManage;
 return <main className="organization-page"><LanguageSwitcher/><Link to="/account">{t('auth.account')}</Link>{!rosterOnly&&<Link to="/administration/collections">{t('collections.title')}</Link>}<h1>{t(rosterOnly?'transport.rosterTitle':'transport.title')}</h1><p>{t(rosterOnly?'transport.rosterHelp':'transport.help')}</p>{managed?<ManagedBody rosterOnly={rosterOnly} canTransportRead={canTransportRead} canActivitiesRead={canActivitiesRead} canTransportManage={canTransportManage} canActivitiesManage={canActivitiesManage} canFinance={caps.includes('finance.read')}/>:<>{!rosterOnly&&canTransportRead&&<BusList canManage={false} enabled={false}/>} {canActivitiesRead&&<ActivityList canManage={false} canFinance={caps.includes('finance.read')} enabled={false}/>} {!canTransportRead&&!canActivitiesRead&&<p role="alert">{t('auth.forbidden')}</p>}</>}</main>;
}
