import { Skeleton } from '../../components/surfaces.js';
import { EmptyState, PageHeader } from '../../components/data-display.js';
import { useState,type FormEvent } from 'react';
import { cairoIsoDate,formatDateOnly } from '@nursery/domain';
import type { CheckpointStatus,DailyLearning,HomeworkAssignment,HomeworkRoster,HomeworkOutcome,HomeworkHistoryEntry } from '@nursery/contracts';
import { Button,SelectField,TextField } from '../../components/controls.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import type { MessageKey } from '../../i18n/catalogs.js';
import { useAuth } from '../auth/AuthProvider.js';
import { errorKey,useScoped } from '../children/scoped.js';
type ChildRow={ id: string; fullName: string; classroomId: string; classroomName: string };
function useMutation() {
 const auth=useAuth(); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null); const [saved,setSaved]=useState(false);
 async function save(path: string,input: unknown,after: () => void) { setBusy(true); setError(null); setSaved(false); try { await auth.client.business(path,'POST',input); setSaved(true); after(); } catch(e) { setError(errorKey(e)); auth.handleError(e); } finally { setBusy(false); } }
 return { busy,error,saved,save };
}
function Notice({ mutation }: { mutation: ReturnType<typeof useMutation> }) { const { t }=useLocale(); return <>{mutation.error && <p className="inline-notice inline-notice--danger" role="alert">{t(mutation.error)}</p>}{mutation.saved && <p className="inline-notice" role="status">{t('homework.saved')}</p>}</>; }
function AssignmentForm({ classroomId,date,children,reload }: { classroomId: string; date: string; children: ChildRow[]; reload: () => void }) {
 const { t }=useLocale(); const [title,setTitle]=useState(''); const [instructions,setInstructions]=useState(''); const [due,setDue]=useState(date); const [selected,setSelected]=useState<string[]>(children.map((c) => c.id)); const [operation,setOperation]=useState(crypto.randomUUID()); const m=useMutation();
 const edit=(fn: () => void) => { fn(); setOperation(crypto.randomUUID()); };
 function submit(e: FormEvent) { e.preventDefault(); void m.save('homework',{ classroomId,title,instructions,assignedOn: date,dueOn: due,childIds: selected,operationId: operation },() => { setTitle(''); setInstructions(''); setOperation(crypto.randomUUID()); reload(); }); }
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={m.busy} className="organization-fields"><legend>{t('homework.create')}</legend><Notice mutation={m} />
 <TextField label={t('homework.assignmentTitle')} required maxLength={160} value={title} onChange={(e) => edit(() => setTitle(e.target.value))} />
 <TextField label={t('homework.instructions')} required maxLength={4000} value={instructions} onChange={(e) => edit(() => setInstructions(e.target.value))} />
 <TextField label={t('homework.due')} type="date" required min={date} value={due} onChange={(e) => edit(() => setDue(e.target.value))} />
 {children.map((c) => <label className="choice-field" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={(e) => edit(() => setSelected(e.target.checked ? [...selected,c.id] : selected.filter((id) => id!==c.id)))} />{c.fullName}</label>)}
 <Button loading={m.busy} icon="plus" type="submit" disabled={!selected.length}>{t('homework.create')}</Button></fieldset></form>;
}
function ContentCorrection({ assignment:a,reload }: { assignment: HomeworkAssignment; reload: () => void }) {
 const { t }=useLocale(); const [title,setTitle]=useState(a.title); const [instructions,setInstructions]=useState(a.instructions); const [reason,setReason]=useState(''); const [operation,setOperation]=useState(crypto.randomUUID()); const m=useMutation(); const history=useScoped<{ revision: number; title: string; instructions: string; reason: string|null }[]>(`homework/${a.id}/versions`);
 const edit=(fn: () => void) => { fn(); setOperation(crypto.randomUUID()); };
 return <details className="disclosure"><summary>{t('homework.correctContent')}</summary><ol className="record-list">{history.data?.map((v) => <li key={v.revision}>{v.revision}: {v.title} — {v.instructions}{v.reason && ` — ${v.reason}`}</li>)}</ol><form className="form-stack" onSubmit={(e) => { e.preventDefault(); void m.save(`homework/${a.id}/corrections`,{ title,instructions,reason,expectedVersion: a.version,operationId: operation },reload); }}><fieldset disabled={m.busy} className="organization-fields"><legend>{t('homework.correctContent')}</legend><Notice mutation={m} /><TextField label={t('homework.assignmentTitle')} required value={title} maxLength={160} onChange={(e) => edit(() => setTitle(e.target.value))} /><TextField label={t('homework.instructions')} required value={instructions} maxLength={4000} onChange={(e) => edit(() => setInstructions(e.target.value))} /><TextField label={t('homework.reason')} required value={reason} maxLength={500} onChange={(e) => edit(() => setReason(e.target.value))} /><Button type="submit">{t('homework.correctContent')}</Button></fieldset></form></details>;
}
function OutcomeCorrection({ a,childId,current,statuses,date,reload }: { a: HomeworkAssignment; childId: string; current: HomeworkOutcome; statuses: CheckpointStatus[]; date: string; reload: () => void }) {
 const { t,locale }=useLocale(); const [statusId,setStatus]=useState(current.status.id); const [note,setNote]=useState(current.note ?? ''); const [reason,setReason]=useState(''); const [operation,setOperation]=useState(crypto.randomUUID()); const m=useMutation(); const edit=(fn: () => void) => { fn(); setOperation(crypto.randomUUID()); };
 return <details className="disclosure"><summary>{t('homework.correctOutcome')}</summary><form className="form-stack" onSubmit={(e) => { e.preventDefault(); void m.save('homework/outcomes/corrections',{ assignmentId: a.id,childId,date,statusId,note: note || null,expectedVersion: current.version,reason,operationId: operation },reload); }}><fieldset disabled={m.busy} className="organization-fields"><legend>{t('homework.correctOutcome')}</legend><Notice mutation={m} /><SelectField label={t('homework.outcome')} value={statusId} onChange={(e) => edit(() => setStatus(e.target.value))}>{statuses.map((s) => <option key={s.id} value={s.id}>{s.label[locale]}</option>)}</SelectField><TextField label={t('homework.note')} value={note} maxLength={2000} onChange={(e) => edit(() => setNote(e.target.value))} /><TextField label={t('homework.reason')} required value={reason} maxLength={500} onChange={(e) => edit(() => setReason(e.target.value))} /><Button type="submit">{t('homework.correctOutcome')}</Button></fieldset></form></details>;
}
function AssignmentChecklist({ assignmentId,date,contentReload,canPublish }: { assignmentId: string; date: string; contentReload: () => void; canPublish: boolean }) {
 const { t,locale }=useLocale(); const state=useScoped<HomeworkRoster>(`homework/${assignmentId}/roster?date=${date}`); const [choices,setChoices]=useState<Record<string,{ include: boolean; statusId: string; note: string }>>({}); const [operation,setOperation]=useState(crypto.randomUUID()); const m=useMutation(); const a=state.data?.assignment;
 if (state.error) return <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>; if (!a || !state.data) return <Skeleton label={t('state.loading')} />; const draft=state.data;
 async function publish() { await m.save('homework/outcomes',{ assignmentId,date,operationId: operation,entries: draft.entries.filter((e) => !e.outcome && e.canRecord && choices[e.childId]?.include).map((e) => ({ childId: e.childId,statusId: choices[e.childId].statusId,note: choices[e.childId].note || null,expectedVersion: 0 })) },() => { setChoices({}); setOperation(crypto.randomUUID()); state.reload(); }); }
 return <section className="workspace-section"><h2>{a.title}</h2><p>{a.instructions}</p><p>{formatDateOnly(a.assignedOn)} — {t('homework.due')}: {formatDateOnly(a.dueOn)} — {t('homework.version')} {a.version}</p>
 {canPublish && <ContentCorrection key={`${a.id}/${a.version}`} assignment={a} reload={() => { state.reload(); contentReload(); }} />}<Notice mutation={m} /><p>{t('homework.help')}</p><fieldset disabled={m.busy || !canPublish} className="organization-fields"><legend>{t('homework.checklist')}</legend>
 {draft.entries.map((e) => { const choice=choices[e.childId] ?? { include: false,statusId: draft.statuses[0]?.id ?? '',note: '' }; const edit=(next: typeof choice) => { setChoices({ ...choices,[e.childId]: next }); setOperation(crypto.randomUUID()); }; return <fieldset key={e.childId} className="organization-fields"><legend>{e.fullName}</legend>
 {e.outcome ? <><strong>{e.outcome.status.label[locale]}</strong>{e.outcome.note && <p>{e.outcome.note}</p>}{e.outcome.version>1 && <p>{t('homework.corrected')}</p>}{e.canRecord && canPublish && <OutcomeCorrection key={`${e.childId}/${e.outcome.version}`} a={a} childId={e.childId} current={e.outcome} statuses={draft.statuses} date={date} reload={state.reload} />}</> : <><p>{t('homework.missing')}</p>{e.canRecord ? <><label className="choice-field"><input type="checkbox" checked={choice.include} onChange={(v) => edit({ ...choice,include: v.target.checked })} />{t('homework.select')}</label><SelectField label={t('homework.outcome')} value={choice.statusId} onChange={(v) => edit({ ...choice,statusId: v.target.value })}>{draft.statuses.map((s) => <option key={s.id} value={s.id}>{s.label[locale]}</option>)}</SelectField><TextField label={t('homework.note')} value={choice.note} maxLength={2000} onChange={(v) => edit({ ...choice,note: v.target.value })} /></> : <p>{t('homework.scopeLost')}</p>}</>}
 </fieldset>; })}
 <Button loading={m.busy} icon="check" disabled={!Object.values(choices).some((c) => c.include)} onClick={() => { void publish(); }}>{t('homework.publish')}</Button></fieldset></section>;
}
function NoDay({ classroomId,date,children }: { classroomId: string; date: string; children: ChildRow[] }) {
 const { t,locale }=useLocale(); const m=useMutation(); const [choices,setChoices]=useState<Record<string,{ statusId: string; revision: number }>>({}); const [operation,setOperation]=useState(crypto.randomUUID()); const [loading,setLoading]=useState(false); const auth=useAuth();
 async function review() { setLoading(true); try { const next: typeof choices={}; for (const c of children) { const day=await auth.client.business<DailyLearning>(`learning/children/${c.id}/daily?date=${date}`); const slot=day.slots.find((s) => s.definition.kind==='HOMEWORK'); if (slot) next[c.id]={ statusId: slot.definition.statuses.find((s) => s.outcome==='NO_HOMEWORK')!.id,revision: slot.event?.revision ?? 0 }; } setChoices(next); setOperation(crypto.randomUUID()); } catch(e) { auth.handleError(e); } finally { setLoading(false); } }
 // Existing mapped outcome IDs are stable; labels come from each child's frozen daily config.
 const first=useScoped<DailyLearning>(`learning/children/${children[0]?.id}/daily?date=${date}`); const statuses=first.data?.slots.find((s) => s.definition.kind==='HOMEWORK')?.definition.statuses.filter((s) => s.enabled && ['NO_HOMEWORK','EXCUSED'].includes(s.outcome ?? '')) ?? [];
 return <details className="disclosure"><summary>{t('homework.noDay')}</summary><p>{t('homework.noDayHelp')}</p><Notice mutation={m} /><Button loading={m.busy} icon="check" disabled={loading || m.busy} onClick={() => { void review(); }}>{t('homework.review')}</Button><fieldset className="organization-fields" disabled={m.busy}><legend>{t('homework.noDay')}</legend>{children.filter((c) => choices[c.id]).map((c) => <label key={c.id}>{c.fullName}<select className="field__control" aria-label={c.fullName} value={choices[c.id].statusId} onChange={(e) => { setChoices({ ...choices,[c.id]: { ...choices[c.id],statusId: e.target.value } }); setOperation(crypto.randomUUID()); }}>{statuses.map((s) => <option key={s.id} value={s.id}>{s.label[locale]}</option>)}</select><Button icon="trash" variant="quiet" onClick={() => { const next={ ...choices }; delete next[c.id]; setChoices(next); setOperation(crypto.randomUUID()); }}>{t('children.remove')}</Button></label>)}<Button disabled={!Object.keys(choices).length} onClick={() => { void m.save('homework/no-homework-day',{ classroomId,date,operationId: operation,entries: Object.entries(choices).map(([childId,c]) => ({ childId,statusId: c.statusId,expectedVersion: c.revision,note: null })) },() => setChoices({})); }}>{t('homework.noDay')}</Button></fieldset></details>;
}
function ClassroomWork({ classroomId,date,children,canPublish }: { classroomId: string; date: string; children: ChildRow[]; canPublish: boolean }) {
 const { t }=useLocale(); const [overdue,setOverdue]=useState(false); const [selected,setSelected]=useState(''); const state=useScoped<HomeworkAssignment[]>(`homework?classroomId=${classroomId}&date=${date}&overdue=${overdue}`); const id=state.data?.some((a) => a.id===selected) ? selected : state.data?.[0]?.id;
 return <>{canPublish && <AssignmentForm classroomId={classroomId} date={date} children={children} reload={state.reload} />}<label className="choice-field"><input type="checkbox" checked={overdue} onChange={(e) => { setOverdue(e.target.checked); setSelected(''); }} />{t('homework.overdue')}</label>{state.error && <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>}
 {state.data?.length ? <><SelectField label={t('homework.assignment')} value={id} onChange={(e) => setSelected(e.target.value)}>{state.data.map((a) => <option key={a.id} value={a.id}>{a.title} — {formatDateOnly(a.dueOn)}</option>)}</SelectField>{id && <AssignmentChecklist key={id} assignmentId={id} date={date} contentReload={state.reload} canPublish={canPublish} />}</> : <EmptyState title={t('homework.empty')} art="classroom" />}{canPublish && children.length>0 && <NoDay classroomId={classroomId} date={date} children={children} />}</>;
}
export function TeacherHomeworkScreen() {
 const { t }=useLocale(); const [date,setDate]=useState(cairoIsoDate()); const [selected,setSelected]=useState(''); const [offset,setOffset]=useState(0); const roster=useScoped<ChildRow[]>(`learning/roster?offset=${offset}`); const context=useScoped<{ modules: string[]; canPublish: boolean }>('learning/context'); const classrooms=roster.data?.filter((c,i,all) => all.findIndex((v) => v.classroomId===c.classroomId)===i) ?? []; const id=classrooms.some((c) => c.classroomId===selected) ? selected : classrooms[0]?.classroomId;
 return <main className="organization-page"><PageHeader title={t('homework.title')} icon="learning" />{(roster.error || context.error) && <p className="inline-notice inline-notice--danger" role="alert">{t(roster.error ?? context.error!)}</p>}
 {context.data && !context.data.modules.includes('HOMEWORK') && <p className="inline-notice inline-notice--danger" role="alert">{t('learning.disabled')}</p>}{context.data?.modules.includes('HOMEWORK') && <><div className="action-group"><Button icon="back" variant="secondary" disabled={offset===0} onClick={() => { setOffset(offset-100); setSelected(''); }}>{t('homework.previous')}</Button><Button icon="arrow" variant="secondary" disabled={!roster.data || roster.data.length<100} onClick={() => { setOffset(offset+100); setSelected(''); }}>{t('homework.next')}</Button></div><div className="filter-bar"><TextField label={t('homework.date')} type="date" max={cairoIsoDate()} value={date} onChange={(e) => setDate(e.target.value)} /><SelectField label={t('homework.classroom')} value={id ?? ''} onChange={(e) => setSelected(e.target.value)}>{classrooms.map((c) => <option key={c.classroomId} value={c.classroomId}>{c.classroomName}</option>)}</SelectField></div>{id && date && <ClassroomWork key={`${id}/${date}`} classroomId={id} date={date} children={roster.data!.filter((c) => c.classroomId===id)} canPublish={context.data.canPublish} />}</>}</main>;
}
export function GuardianHomeworkHistoryPanel({ childId,date }: { childId: string;date?: string }) {
 const { t,locale }=useLocale(); const [overdue,setOverdue]=useState(false); const [offset,setOffset]=useState(0); const state=useScoped<{ items: HomeworkHistoryEntry[]; total: number }>(`homework/children/${childId}/history?overdue=${overdue}&limit=20&offset=${offset}${date ? `&on=${date}` : ''}`);
 const daily=useScoped<DailyLearning>(`learning/children/${childId}/daily?date=${cairoIsoDate()}`); const slot=daily.data?.slots.find((s) => s.definition.kind==='HOMEWORK');
 if (state.error==='learning.disabled') return null;
 return <section className="workspace-section"><h2>{t('homework.history')}</h2><p>{t('homework.readOnly')}</p>{slot && <p>{slot.homework?.future && !slot.homework.due ? t('homework.future') : slot.status.label[locale]} — {t(`learning.${slot.homework?.meaning ?? slot.status.meaning}`)}</p>}<label className="choice-field"><input type="checkbox" checked={overdue} onChange={(e) => { setOverdue(e.target.checked); setOffset(0); }} />{t('homework.overdue')}</label>{state.error && <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>}
 <ul className="record-list">{state.data?.items.filter((i) => !date || i.assignment.assignedOn===date || i.assignment.dueOn===date).map((i) => <li key={i.assignment.id}><strong>{i.assignment.title}</strong><p>{i.assignment.instructions}</p><p>{formatDateOnly(i.assignment.assignedOn)} — {t('homework.due')}: {formatDateOnly(i.assignment.dueOn)}{i.assignment.corrected && ` — ${t('homework.corrected')}`} — {i.outcome ? i.outcome.status.label[locale] : t('homework.missing')}{i.outcome?.version && i.outcome.version>1 && ` — ${t('homework.corrected')}`}{i.overdue && ` — ${t('homework.overdue')}`}</p>{i.outcome?.note && <p>{i.outcome.note}</p>}</li>)}</ul>
 <div className="action-group"><Button icon="back" variant="secondary" disabled={offset===0} onClick={() => setOffset(offset-20)}>{t('homework.previous')}</Button><Button icon="arrow" variant="secondary" disabled={!state.data || offset+20>=state.data.total} onClick={() => setOffset(offset+20)}>{t('homework.next')}</Button></div></section>;
}
