export const childrenEnglish = {
 'children.title': 'Children and families', 'children.onboard': 'Add a family', 'children.parents': 'Guardian accounts', 'children.childFields': 'Child details', 'children.review': 'Review and create', 'children.next': 'Next', 'children.back': 'Back',
 'children.fullName': 'Full name', 'children.mobile': 'Mobile', 'children.username': 'Username', 'children.kind': 'Guardian account', 'children.newGuardian': 'Create new account', 'children.existingGuardian': 'Link existing account', 'children.chooseGuardian': 'Choose a permitted guardian',
 'children.birthDate': 'Date of birth', 'children.code': 'Child code', 'children.branch': 'Branch', 'children.classroom': 'Classroom', 'children.unassigned': 'Not assigned yet', 'children.classroomHelp': 'A classroom is required before daily classroom operations.',
 'children.relationship': 'Relationship', 'children.contacts': 'Secondary contacts', 'children.addContact': 'Add contact', 'children.remove': 'Remove', 'children.addGuardian': 'Add guardian', 'children.addChild': 'Add another child',
 'children.read': 'Read child records', 'children.finance': 'View child finance', 'children.pickup': 'Pickup permission', 'children.notify': 'Receive notifications', 'children.link': 'Link to this child', 'children.activeLink': 'Active link',
 'children.search': 'Search children', 'children.guardianSearch': 'Search permitted guardians', 'children.all': 'All', 'children.status': 'Status', 'children.ACTIVE': 'Active', 'children.PAUSED': 'Paused', 'children.ARCHIVED': 'Archived / left',
 'children.open': 'Open child record', 'children.save': 'Save', 'children.edit': 'Edit record', 'children.reason': 'Reason', 'children.publicMessage': 'Parent contact message', 'children.lifecycle': 'Change child status', 'children.move': 'Move classroom',
 'children.lifecycleHelp': 'Pausing leaves fee agreements unchanged. Archiving retains history and ends future monthly generation when billing is available. Existing charges remain. Account slots are retained.',
 'children.history': 'Lifecycle history', 'children.classHistory': 'Classroom history', 'children.guardians': 'Guardian links', 'children.saveLink': 'Save guardian link', 'children.saved': 'Changes saved.', 'children.created': 'Family created.',
 'children.credentials': 'One-time initial passwords', 'children.credentialsHelp': 'Deliver these initial passwords privately. Each guardian must change the password at first login. They are shown once and never stored in this browser.', 'children.dismiss': 'Dismiss passwords',
 'children.initialPasswordHelp': 'The server creates an initial temporary password for each new guardian after the family is saved.', 'children.noLaterSteps': 'Available steps: accounts, children, optional documents. Fee agreements, transport, and payments will be available after their modules are implemented.',
 'children.documents': 'Administrative documents', 'children.documentName': 'Document name', 'children.expiry': 'Expiry date (optional)', 'children.file': 'PDF, JPEG, or PNG file', 'children.fileHelp': 'Up to 5 MB. Private administrative documents; optional expiry does not delete history.', 'children.upload': 'Upload document', 'children.download': 'Download', 'children.retire': 'Retire document',
 'children.contactNursery': 'Please contact the nursery about this child.', 'children.noChildren': 'No permitted children to display.', 'children.count': 'Matching children: {count}', 'children.previous': 'Previous page', 'children.nextPage': 'Next page', 'children.refresh': 'Refresh',
 'children.invalid': 'Check the required fields, dates, lifecycle state, and guardian selections.', 'children.conflict': 'A code or account may already exist, or linked data changed. Review the family before retrying.', 'children.operationConflict': 'This creation attempt was reused with different data. Review and start a new attempt.',
 'children.invalidDocument': 'The document is invalid or exceeds the allowed limits. Use a PDF without interactive content, JPEG, or PNG up to 5 MB.', 'children.capacityWarning': 'The classroom capacity is exceeded. The authorized placement was saved.', 'children.replayed': 'This family was already created. Original passwords cannot be displayed again; contact Superadmin if a reset is needed.',
 'children.occupancy': 'Active children: {count}; capacity: {capacity}',
 'organization.cap.children.read': 'Read children in assigned scope', 'organization.cap.children.manage': 'Manage children in assigned scope', 'organization.cap.guardians.manage': 'Manage guardian links', 'organization.cap.documents.manage': 'Manage private administrative documents'
} as const;
export const childrenArabic: Record<keyof typeof childrenEnglish,string> = {
 'children.title': 'الأطفال والأسر', 'children.onboard': 'إضافة أسرة', 'children.parents': 'حسابات أولياء الأمور', 'children.childFields': 'بيانات الأطفال', 'children.review': 'مراجعة وإنشاء', 'children.next': 'التالي', 'children.back': 'رجوع',
 'children.fullName': 'الاسم بالكامل', 'children.mobile': 'رقم الموبايل', 'children.username': 'اسم المستخدم', 'children.kind': 'حساب ولي الأمر', 'children.newGuardian': 'إنشاء حساب جديد', 'children.existingGuardian': 'ربط حساب موجود', 'children.chooseGuardian': 'اختار ولي أمر من المتاح',
 'children.birthDate': 'تاريخ الميلاد', 'children.code': 'كود الطفل', 'children.branch': 'الفرع', 'children.classroom': 'الفصل', 'children.unassigned': 'لسه مش متعيّن', 'children.classroomHelp': 'لازم تعيّن فصل قبل العمليات اليومية للفصل.',
 'children.relationship': 'صلة القرابة', 'children.contacts': 'جهات اتصال إضافية', 'children.addContact': 'إضافة جهة اتصال', 'children.remove': 'إزالة', 'children.addGuardian': 'إضافة ولي أمر', 'children.addChild': 'إضافة طفل تاني',
 'children.read': 'عرض سجلات الطفل', 'children.finance': 'عرض مالية الطفل', 'children.pickup': 'السماح بالاستلام', 'children.notify': 'استلام إشعارات', 'children.link': 'ربط بالطفل ده', 'children.activeLink': 'الربط فعّال',
 'children.search': 'البحث عن طفل', 'children.guardianSearch': 'البحث في أولياء الأمور المتاحين', 'children.all': 'الكل', 'children.status': 'الحالة', 'children.ACTIVE': 'نشط', 'children.PAUSED': 'متوقف مؤقتًا', 'children.ARCHIVED': 'مؤرشف / ترك الحضانة',
 'children.open': 'فتح سجل الطفل', 'children.save': 'حفظ', 'children.edit': 'تعديل السجل', 'children.reason': 'السبب', 'children.publicMessage': 'رسالة التواصل لولي الأمر', 'children.lifecycle': 'تغيير حالة الطفل', 'children.move': 'نقل الفصل',
 'children.lifecycleHelp': 'الإيقاف المؤقت مش بيغيّر اتفاقات الرسوم. الأرشفة بتحفظ السجلات وبتوقف إصدار الرسوم الشهرية الجديدة لما وحدة الرسوم تتنفّذ. الرسوم القديمة بتفضل موجودة وحجوزات الحسابات بتفضل محسوبة.',
 'children.history': 'سجل تغييرات الحالة', 'children.classHistory': 'سجل تغييرات الفصل', 'children.guardians': 'روابط أولياء الأمور', 'children.saveLink': 'حفظ رابط ولي الأمر', 'children.saved': 'تم الحفظ.', 'children.created': 'تم إنشاء الأسرة.',
 'children.credentials': 'كلمات المرور الأولية لمرة واحدة', 'children.credentialsHelp': 'سلّم كلمات المرور دي بشكل خاص. كل ولي أمر لازم يغيّرها عند أول دخول. بتظهر مرة واحدة ومش بتتحفظ في المتصفح.', 'children.dismiss': 'إخفاء كلمات المرور',
 'children.initialPasswordHelp': 'النظام بينشئ كلمة مرور مؤقتة لكل ولي أمر جديد بعد حفظ الأسرة.', 'children.noLaterSteps': 'الخطوات المتاحة: الحسابات، الأطفال، والمستندات الاختيارية. اتفاقات الرسوم والنقل والمدفوعات هتظهر بعد تنفيذ وحداتها.',
 'children.documents': 'المستندات الإدارية', 'children.documentName': 'اسم المستند', 'children.expiry': 'تاريخ الانتهاء (اختياري)', 'children.file': 'ملف PDF أو JPEG أو PNG', 'children.fileHelp': 'بحد أقصى 5 ميجابايت. مستندات إدارية خاصة، وتاريخ الانتهاء مش بيمسح السجل.', 'children.upload': 'رفع مستند', 'children.download': 'تنزيل', 'children.retire': 'إيقاف إتاحة المستند',
 'children.contactNursery': 'يرجى التواصل مع الحضانة بخصوص الطفل ده.', 'children.noChildren': 'مفيش أطفال مسموح بعرضهم.', 'children.count': 'عدد الأطفال في النتائج: {count}', 'children.previous': 'الصفحة السابقة', 'children.nextPage': 'الصفحة التالية', 'children.refresh': 'تحديث',
 'children.invalid': 'راجع البيانات المطلوبة والتواريخ والحالة واختيارات أولياء الأمور.', 'children.conflict': 'ممكن الكود أو الحساب موجود بالفعل أو البيانات المرتبطة اتغيرت. راجع الأسرة قبل المحاولة تاني.', 'children.operationConflict': 'محاولة الإنشاء اتكررت ببيانات مختلفة. راجع البيانات وابدأ محاولة جديدة.',
 'children.invalidDocument': 'المستند غير صالح أو حجمه أكبر من المسموح. استخدم PDF بدون محتوى تفاعلي أو JPEG أو PNG بحد أقصى 5 ميجابايت.', 'children.capacityWarning': 'سعة الفصل اتجاوزت الحد المحدد. تم حفظ التسكين المسموح به.', 'children.replayed': 'الأسرة اتعملت بالفعل. كلمات المرور الأصلية مش ممكن تظهر تاني؛ تواصل مع مسؤول النظام لو محتاج إعادة تعيين.',
 'children.occupancy': 'الأطفال النشطين: {count}؛ السعة: {capacity}',
 'organization.cap.children.read': 'عرض الأطفال في النطاق المسموح', 'organization.cap.children.manage': 'إدارة الأطفال في النطاق المسموح', 'organization.cap.guardians.manage': 'إدارة روابط أولياء الأمور', 'organization.cap.documents.manage': 'إدارة المستندات الإدارية الخاصة'
};

