export const examsEnglish = {
  'organization.cap.exams.catalog': 'Manage exam subjects and types',
  'exams.title': 'Exams',
  'exams.catalogTitle': 'Subjects and exam types',
  'exams.subjects': 'Subjects',
  'exams.types': 'Exam types',
  'exams.addSubject': 'Add subject',
  'exams.addType': 'Add exam type',
  'exams.name': 'Name',
  'exams.enabled': 'Enabled',
  'exams.save': 'Save',
  'exams.createTitle': 'Create an exam',
  'exams.examName': 'Exam name',
  'exams.subject': 'Subject',
  'exams.type': 'Exam type',
  'exams.classroom': 'Classroom',
  'exams.date': 'Exam date',
  'exams.gradeFormat': 'Grade format',
  'exams.numeric': 'Numeric marks',
  'exams.label': 'Grade label',
  'exams.maximumMarks': 'Maximum marks',
  'exams.decimalAllowed': 'Allow decimal marks',
  'exams.labelOptions': 'Grade labels (one per line, at least two)',
  'exams.createAction': 'Create exam',
  'exams.created': 'Exam created',
  'exams.listTitle': 'Exams for this classroom and date',
  'exams.empty': 'No exams are scheduled for this classroom and date.',
  'exams.noExam': 'No exam today',
  'exams.noExamHelp': 'Use only when nothing is scheduled. This records N/A for the reviewed roster and is refused once an exam exists for this day.',
  'exams.rosterTitle': 'Enter results',
  'exams.missing': 'Missing — not recorded',
  'exams.outcome': 'Outcome',
  'exams.result': 'Result',
  'exams.childAbsent': 'Child absent for this exam',
  'exams.score': 'Score',
  'exams.comment': 'Optional comment',
  'exams.include': 'Publish this child',
  'exams.reviewHelp': 'Review every selected child. A missing result is never treated as zero.',
  'exams.bulkAbsent': 'Explicitly mark all unpublished children absent for this exam',
  'exams.publish': 'Publish selected results',
  'exams.saved': 'Results saved',
  'exams.correct': 'Correct result',
  'exams.correctionReason': 'Why this correction is needed',
  'exams.historyTitle': 'Exam history',
  'exams.filterSubject': 'Filter by subject',
  'exams.filterType': 'Filter by type',
  'exams.filterFrom': 'From date',
  'exams.filterUntil': 'Until date',
  'exams.allSubjects': 'All subjects',
  'exams.allTypes': 'All types',
  'exams.invalid': 'Review the grade format, score, label, and selected children.',
  'exams.of': 'of',
} as const;
export const examsArabic: Record<keyof typeof examsEnglish,string> = {
  'organization.cap.exams.catalog': 'إدارة مواد وأنواع الامتحانات',
  'exams.title': 'الامتحانات',
  'exams.catalogTitle': 'المواد وأنواع الامتحانات',
  'exams.subjects': 'المواد',
  'exams.types': 'أنواع الامتحانات',
  'exams.addSubject': 'إضافة مادة',
  'exams.addType': 'إضافة نوع امتحان',
  'exams.name': 'الاسم',
  'exams.enabled': 'مفعّل',
  'exams.save': 'حفظ',
  'exams.createTitle': 'إنشاء امتحان',
  'exams.examName': 'اسم الامتحان',
  'exams.subject': 'المادة',
  'exams.type': 'نوع الامتحان',
  'exams.classroom': 'الفصل',
  'exams.date': 'تاريخ الامتحان',
  'exams.gradeFormat': 'طريقة التقييم',
  'exams.numeric': 'درجة رقمية',
  'exams.label': 'تقييم وصفي',
  'exams.maximumMarks': 'الدرجة النهائية',
  'exams.decimalAllowed': 'السماح بدرجات عشرية',
  'exams.labelOptions': 'التقييمات الوصفية (كل واحد في سطر، اتنين على الأقل)',
  'exams.createAction': 'إنشاء الامتحان',
  'exams.created': 'اتعمل الامتحان',
  'exams.listTitle': 'امتحانات الفصل ده في التاريخ ده',
  'exams.empty': 'مفيش امتحانات متحددة للفصل ده في التاريخ ده.',
  'exams.noExam': 'مفيش امتحان النهارده',
  'exams.noExamHelp': 'استخدم ده بس لو مفيش حاجة متحددة. هيتسجل مش مطلوب لكل الأطفال اللي راجعتهم، ومش هيتقبل لو فيه امتحان اتسجل في اليوم ده.',
  'exams.rosterTitle': 'تسجيل النتايج',
  'exams.missing': 'لسه متسجلش',
  'exams.outcome': 'النتيجة',
  'exams.result': 'درجة/تقييم',
  'exams.childAbsent': 'الطفل غايب عن الامتحان ده',
  'exams.score': 'الدرجة',
  'exams.comment': 'ملاحظة اختيارية',
  'exams.include': 'نشر نتيجة الطفل ده',
  'exams.reviewHelp': 'راجع كل طفل مختار. النتيجة الناقصة مش بتتحسب صفر.',
  'exams.bulkAbsent': 'تحديد كل الأطفال اللي لسه متسجلوش كغايبين عن الامتحان ده',
  'exams.publish': 'نشر النتايج المختارة',
  'exams.saved': 'اتحفظت النتايج',
  'exams.correct': 'تصحيح النتيجة',
  'exams.correctionReason': 'سبب التصحيح',
  'exams.historyTitle': 'سجل الامتحانات',
  'exams.filterSubject': 'فلترة حسب المادة',
  'exams.filterType': 'فلترة حسب النوع',
  'exams.filterFrom': 'من تاريخ',
  'exams.filterUntil': 'لحد تاريخ',
  'exams.allSubjects': 'كل المواد',
  'exams.allTypes': 'كل الأنواع',
  'exams.invalid': 'راجع طريقة التقييم والدرجة والتقييم الوصفي والأطفال المختارين.',
  'exams.of': 'من',
};
