export const communicationEnglish = {
 'organization.cap.announcements.manage': 'Publish targeted announcements',
 'hub.updated': 'New updates are available.',
 'hub.today': 'Today','hub.child': 'Choose a child','hub.notices': 'Notices','hub.notifications': 'Notifications','hub.profile': 'Child profile','hub.history': 'Previous updates','hub.acknowledge': 'I have read this notice','hub.acknowledged': 'Acknowledged','hub.empty': 'No notices yet.','hub.read': 'Mark read','hub.unread': 'Mark unread','hub.unreadCount': '{count} unread','hub.publish': 'Publish notice','hub.title': 'Notice title','hub.body': 'Message','hub.target': 'Send to','hub.NURSERY': 'Whole nursery','hub.BRANCH': 'Branch','hub.CLASSROOM': 'Classroom','hub.PARENTS': 'Selected parents','hub.CHILDREN': 'Selected children','hub.ackRequired': 'Ask each guardian to acknowledge','hub.holiday': 'Holiday notice','hub.from': 'From','hub.until': 'Until','hub.published': 'Notice published','hub.select': 'Select recipients','hub.next': 'Next page','hub.previous': 'Previous page',
 'hub.LEARNING': 'Learning update','hub.HOMEWORK': 'Homework update','hub.INCIDENT': 'Incident update','hub.UNEXPECTED_ABSENCE': 'Absence recorded','hub.PLANNED_ABSENCE': 'Planned absence saved','hub.ANNOUNCEMENT': 'New notice','hub.HOLIDAY': 'Holiday notice'
};
export const communicationArabic: Record<keyof typeof communicationEnglish,string> = {
 'organization.cap.announcements.manage': 'نشر إعلانات لمستلمين محددين',
 'hub.updated': 'فيه تحديثات جديدة.',
 'hub.today': 'النهارده','hub.child': 'اختار طفل','hub.notices': 'الإعلانات','hub.notifications': 'الإشعارات','hub.profile': 'بيانات الطفل','hub.history': 'التحديثات السابقة','hub.acknowledge': 'قريت الإعلان','hub.acknowledged': 'تم تأكيد القراءة','hub.empty': 'مفيش إعلانات لسه.','hub.read': 'حدد كمقروء','hub.unread': 'حدد كغير مقروء','hub.unreadCount': '{count} غير مقروء','hub.publish': 'نشر إعلان','hub.title': 'عنوان الإعلان','hub.body': 'الرسالة','hub.target': 'إرسال إلى','hub.NURSERY': 'كل الحضانة','hub.BRANCH': 'الفرع','hub.CLASSROOM': 'الفصل','hub.PARENTS': 'أولياء أمور محددين','hub.CHILDREN': 'أطفال محددين','hub.ackRequired': 'اطلب تأكيد القراءة من كل ولي أمر','hub.holiday': 'إعلان إجازة','hub.from': 'من','hub.until': 'لحد','hub.published': 'الإعلان اتنشر','hub.select': 'اختار المستلمين','hub.next': 'الصفحة التالية','hub.previous': 'الصفحة السابقة',
 'hub.LEARNING': 'تحديث تعليمي','hub.HOMEWORK': 'تحديث الواجب','hub.INCIDENT': 'تحديث واقعة','hub.UNEXPECTED_ABSENCE': 'اتسجل غياب','hub.PLANNED_ABSENCE': 'اتحفظ إشعار الغياب','hub.ANNOUNCEMENT': 'إعلان جديد','hub.HOLIDAY': 'إعلان إجازة'
};
