import { useRef,useState,type ReactNode,type FormEvent } from 'react';
import { Link,useParams } from 'react-router';
import { cairoIsoDate,formatDateOnly,whatsAppLink } from '@nursery/domain';
import type { Announcement,AnnouncementInput,DailyLearning,GuardianChild,GuardianSafetyView,NotificationPage } from '@nursery/contracts';
import { Button,SelectField,TextField } from '../../components/controls.js';
import { Card, Skeleton } from '../../components/surfaces.js';
import { EmptyState, PageHeader } from '../../components/data-display.js';
import { NurseryScene } from '../../components/illustrations.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import type { MessageKey } from '../../i18n/catalogs.js';
import { useAuth } from '../auth/AuthProvider.js';
import { errorKey,useScoped } from '../children/scoped.js';
import { DailyLearningPanel } from '../learning/screens.js';
import { GuardianExamHistoryPanel } from '../exams/screens.js';
import { GuardianHomeworkHistoryPanel } from '../homework/screens.js';
import { refreshParentScope } from './ParentLive.js';

// Parent destinations come from the session shell's grouped navigation; this frame adds the page
// body and the nursery contact so every parent screen keeps a visible way to reach the nursery.
export function ParentFrame({ children }: { children: ReactNode }) {
 const { t }=useLocale(); const auth=useAuth(); const contact=useScoped<{ name: string;whatsappNumber: string|null }>('parent/contact');
 if (auth.session?.account.kind!=='GUARDIAN') return <main><p>{t('auth.forbidden')}</p></main>;
 return <main className="organization-page parent-hub">{children}{contact.data?.whatsappNumber && <a className="button-link button-link--contact" href={whatsAppLink(contact.data.whatsappNumber)} target="_blank" rel="noopener noreferrer">{t('safety.whatsapp')} — {contact.data.name}</a>}</main>;
}
function TodayChild({ childId,date }: { childId: string;date: string }) {
 const { t }=useLocale(); const safety=useScoped<GuardianSafetyView>(`parent/children/${childId}/safety`); const day=useScoped<DailyLearning>(`learning/children/${childId}/daily?date=${date}`); const [historyDate,setHistoryDate]=useState(date); const exam=day.data?.slots.some((s) => s.definition.kind==='EXAM'); const homework=day.data?.slots.some((s) => s.definition.kind==='HOMEWORK');
 return <><div className="action-group"><Link className="button button--outline" to={`/parent/children/${childId}`}>{t('hub.profile')}</Link>{safety.data?.health && <Link className="button button--outline" to={`/parent/children/${childId}#health`}>{t('safety.health')}</Link>}{safety.data?.pickup && <Link className="button button--outline" to={`/parent/children/${childId}#pickup`}>{t('safety.pickup')}</Link>}</div>
 <DailyLearningPanel childId={childId} date={date} guardian />{exam && <Card title={t('exams.title')}><GuardianExamHistoryPanel childId={childId} date={date} /></Card>}{homework && <Card title={t('homework.title')}><GuardianHomeworkHistoryPanel childId={childId} date={date} /></Card>}
 {day.data && <details className="disclosure"><summary>{t('hub.history')}</summary><TextField label={t('learning.date')} type="date" max={date} value={historyDate} onChange={(e) => setHistoryDate(e.target.value)} />{historyDate && <DailyLearningPanel key={historyDate} childId={childId} date={historyDate} guardian />}{exam && <GuardianExamHistoryPanel childId={childId} />}{homework && <GuardianHomeworkHistoryPanel childId={childId} />}</details>}</>;
}
export function ParentTodayScreen() {
 const { t }=useLocale(); const state=useScoped<GuardianChild[]>('parent/children'); const [selected,setSelected]=useState(''); const active=state.data?.filter((c) => c.status==='ACTIVE') ?? []; const childId=active.some((c) => c.id===selected) ? selected : active[0]?.id;
 return <ParentFrame><PageHeader title={t('hub.today')} art={<NurseryScene variant="compact" />} /><p><span dir="ltr">{formatDateOnly(cairoIsoDate())}</span></p><Link className="button button--outline" to="/parent/notices">{t('hub.notices')}</Link>{state.error && <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>}{active.length ? <><SelectField label={t('hub.child')} value={childId} onChange={(e) => setSelected(e.target.value)}>{active.map((c) => <option key={c.id} value={c.id}>{c.fullName}</option>)}</SelectField>{childId && <TodayChild key={childId} childId={childId} date={cairoIsoDate()} />}</> : state.data ? <EmptyState art="children" title={t('children.noChildren')} /> : <Skeleton label={t('state.loading')} />}{state.data?.filter((c) => c.status==='PAUSED').map((c) => <Card key={c.id} title={c.fullName}><p>{c.publicMessage || t('children.contactNursery')}</p></Card>)}</ParentFrame>;
}
function NoticeCard({ notice }: { notice: Announcement }) {
 const { t }=useLocale(); const auth=useAuth(); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null);
 async function acknowledge() { setBusy(true); try { await auth.client.business(`parent/announcements/${notice.id}/acknowledgment`,'POST',{}); refreshParentScope(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
 return <Card title={notice.title}><p className="notice-body">{notice.body}</p>{notice.holiday && <p>{t('hub.holiday')}: <span dir="ltr">{formatDateOnly(notice.holiday.from)} — {formatDateOnly(notice.holiday.until)}</span></p>}{error && <p className="inline-notice inline-notice--danger" role="alert">{t(error)}</p>}{notice.acknowledgmentRequired && (notice.acknowledged ? <p>{t('hub.acknowledged')}</p> : <Button loading={busy} icon="check" disabled={busy} onClick={() => { void acknowledge(); }}>{t('hub.acknowledge')}</Button>)}</Card>;
}
export function ParentNoticesScreen() {
 const { t }=useLocale(); const [offset,setOffset]=useState(0); const state=useScoped<Announcement[]>(`parent/announcements?limit=20&offset=${offset}`);
 return <ParentFrame><PageHeader title={t('hub.notices')} icon="bell" />{state.error && <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>}{state.data?.length===0 && <EmptyState art="notifications" title={t('hub.empty')} />}{state.data?.map((n) => <NoticeCard key={n.id} notice={n} />)}<div className="action-group"><Button icon="back" variant="secondary" disabled={!offset} onClick={() => setOffset(offset-20)}>{t('hub.previous')}</Button><Button icon="arrow" variant="secondary" disabled={state.data?.length!==20} onClick={() => setOffset(offset+20)}>{t('hub.next')}</Button></div></ParentFrame>;
}
export function ParentNoticeScreen() {
 const { id }=useParams(); const { t }=useLocale(); const state=useScoped<Announcement>(`parent/announcements/${encodeURIComponent(id ?? '')}`);
 return <ParentFrame><PageHeader title={t('hub.notices')} icon="bell" />{state.error && <p className="inline-notice inline-notice--danger" role="alert">{t(state.error)}</p>}{state.data && <NoticeCard notice={state.data} />}</ParentFrame>;
}
export function ParentNotificationsScreen() {
 const { t }=useLocale(); const auth=useAuth(); const [offset,setOffset]=useState(0); const state=useScoped<NotificationPage>(`parent/notifications?limit=20&offset=${offset}`); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null);
 async function read(id: string,value: boolean) { setBusy(true); try { await auth.client.business(`parent/notifications/${id}/read`,'PUT',{ read: value }); refreshParentScope(); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
 return <ParentFrame><PageHeader title={t('hub.notifications')} icon="bell" />{(error || state.error) && <p className="inline-notice inline-notice--danger" role="alert">{t(error || state.error!)}</p>}{state.data && <><p className="inline-notice" role="status">{t('hub.unreadCount',{ count: state.data.unread })}</p>{state.data.items.length===0 && <EmptyState art="notifications" title={t('state.emptyTitle')} body={t('state.emptyBody')} />}{state.data.items.map((n) => <Card key={n.id} title={t(`hub.${n.kind}`)}>{n.date && <p dir="ltr">{formatDateOnly(n.date)}</p>}<div className="action-group"><Link className="button button--outline" to={n.href}>{t(`hub.${n.kind}`)}</Link><Button disabled={busy} onClick={() => { void read(n.id,!n.read); }}>{t(n.read ? 'hub.unread' : 'hub.read')}</Button></div></Card>)}<div className="action-group"><Button icon="back" variant="secondary" disabled={!offset} onClick={() => setOffset(offset-20)}>{t('hub.previous')}</Button><Button icon="arrow" variant="secondary" disabled={offset+20>=state.data.total} onClick={() => setOffset(offset+20)}>{t('hub.next')}</Button></div></>}</ParentFrame>;
}
type Options={ nursery: boolean;branches: { id: string;name: string }[];classrooms: { id: string;name: string }[];parents: { id: string;fullName: string }[];children: { id: string;fullName: string }[] };
export function AnnouncementPublishScreen() {
 const { t }=useLocale(); const auth=useAuth(); const [offset,setOffset]=useState(0); const options=useScoped<Options>(`announcements/options?limit=50&offset=${offset}`); const [kind,setKind]=useState<AnnouncementInput['target']['kind']>('CLASSROOM'); const [ids,setIds]=useState<string[]>([]); const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [ack,setAck]=useState(false); const [holiday,setHoliday]=useState(false); const [from,setFrom]=useState(cairoIsoDate()); const [until,setUntil]=useState(cairoIsoDate()); const [busy,setBusy]=useState(false); const [error,setError]=useState<MessageKey|null>(null); const [saved,setSaved]=useState(false); const operation=useRef({ input: '',id: '' });
 const choices=options.data ? kind==='BRANCH' ? options.data.branches.map((c) => ({ id: c.id,name: c.name })) : kind==='CLASSROOM' ? options.data.classrooms : (kind==='PARENTS' ? options.data.parents : options.data.children).map((c) => ({ id: c.id,name: c.fullName })) : [];
 async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setSaved(false); setError(null); const target=kind==='NURSERY' ? { kind } : kind==='BRANCH' || kind==='CLASSROOM' ? { kind,id: ids[0] } : { kind,ids }; const raw={ title,body,target,acknowledgmentRequired: ack,holiday: holiday ? { from,until } : null }; const encoded=JSON.stringify(raw); if (operation.current.input!==encoded) operation.current={ input: encoded,id: crypto.randomUUID() };
 try { await auth.client.business('announcements','POST',{ ...raw,operationId: operation.current.id }); setSaved(true); } catch(caught) { setError(errorKey(caught)); auth.handleError(caught); } finally { setBusy(false); } }
 return <main className="organization-page"><PageHeader title={t('hub.publish')} icon="bell" />{options.error && <p className="inline-notice inline-notice--danger" role="alert">{t(options.error)}</p>}{options.data && <form className="form-stack" onSubmit={(e) => { void submit(e); }}><fieldset className="organization-fields" disabled={busy}><legend>{t('hub.publish')}</legend>{error && <p className="inline-notice inline-notice--danger" role="alert">{t(error)}</p>}{saved && <p className="inline-notice" role="status">{t('hub.published')}</p>}<TextField label={t('hub.title')} required maxLength={160} value={title} onChange={(e) => setTitle(e.target.value)} /><TextField label={t('hub.body')} required maxLength={2000} value={body} onChange={(e) => setBody(e.target.value)} /><SelectField label={t('hub.target')} value={kind} onChange={(e) => { setKind(e.target.value as typeof kind); setIds([]); setOffset(0); }}>{(['NURSERY','BRANCH','CLASSROOM','PARENTS','CHILDREN'] as const).filter((k) => k!=='NURSERY' || options.data?.nursery).map((k) => <option key={k} value={k}>{t(`hub.${k}`)}</option>)}</SelectField>{kind!=='NURSERY' && <fieldset className="organization-fields"><legend>{t('hub.select')}</legend>{choices.map((c) => <label className="choice-field" key={c.id}><input type={kind==='BRANCH' || kind==='CLASSROOM' ? 'radio' : 'checkbox'} name="recipients" checked={ids.includes(c.id)} onChange={(e) => setIds(kind==='BRANCH' || kind==='CLASSROOM' ? [c.id] : e.target.checked ? [...ids,c.id] : ids.filter((id) => id!==c.id))} />{c.name}</label>)}{(kind==='PARENTS' || kind==='CHILDREN') && <><div className="action-group"><Button icon="back" variant="secondary" disabled={!offset} onClick={() => { setOffset(offset-50); setIds([]); }}>{t('hub.previous')}</Button><Button icon="arrow" variant="secondary" disabled={choices.length!==50} onClick={() => { setOffset(offset+50); setIds([]); }}>{t('hub.next')}</Button></div></>}</fieldset>}<label className="choice-field"><input type="checkbox" checked={ack} onChange={(e) => setAck(e.target.checked)} />{t('hub.ackRequired')}</label><label className="choice-field"><input type="checkbox" checked={holiday} onChange={(e) => setHoliday(e.target.checked)} />{t('hub.holiday')}</label>{holiday && <><TextField label={t('hub.from')} type="date" required value={from} onChange={(e) => setFrom(e.target.value)} /><TextField label={t('hub.until')} type="date" required min={from} value={until} onChange={(e) => setUntil(e.target.value)} /></>}<Button loading={busy} icon="check" type="submit" disabled={kind!=='NURSERY' && !ids.length}>{t('hub.publish')}</Button></fieldset></form>}</main>;
}
