import { useEffect,useRef,useState,type FormEvent } from 'react';
import { reportHasMoney,reportText,reportDetailValue,reportCategoryText,type ReportOptions,type ReportPage,type ReportExport,type ReportQuery,type ReportKind } from '@nursery/contracts';
import { cairoIsoDate,formatDateOnly,formatEgp,piastres } from '@nursery/domain';
import { Button,DateField,SelectField } from '../../components/controls.js';
import { Card,ResponsiveTable } from '../../components/surfaces.js';
import { StatCard,StatGrid } from '../../components/data-display.js';
import { useLocale } from '../../i18n/LocaleProvider.js';
import { useAuth } from '../auth/AuthProvider.js';
import { errorKey,useScoped } from '../children/scoped.js';
const money=(v:string)=>formatEgp(piastres(BigInt(v)));
function ExportStatus({id}:{id:string}) {
 const {t,locale}=useLocale(),auth=useAuth(),job=useScoped<ReportExport>(`reports/exports/${id}`),[error,setError]=useState<ReturnType<typeof errorKey>|null>(null),[busy,setBusy]=useState(false);const epoch=useRef(0);
 useEffect(()=>{const clear=()=>{epoch.current++;setError(null);};window.addEventListener('nursery:scope-refresh',clear);window.addEventListener('focus',clear);document.addEventListener('visibilitychange',clear);return()=>{epoch.current++;window.removeEventListener('nursery:scope-refresh',clear);window.removeEventListener('focus',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 async function download() {setBusy(true);const started=epoch.current;try{const blob=await auth.client.downloadReport(id);if(started!==epoch.current||document.visibilityState==='hidden')return;if(!blob){job.reload();return;}const url=URL.createObjectURL(blob);try{const a=document.createElement('a');a.href=url;a.download=`report.${job.data?.format==='PDF'?'pdf':'xlsx'}`;a.click();}finally{URL.revokeObjectURL(url);}}catch(e){setError(errorKey(e));auth.handleError(e);}finally{setBusy(false);}}
 return <section aria-live="polite">{(job.error||error)&&<p role="alert">{t((job.error||error)!)}</p>}{!job.data&&!job.error&&<p role="status">{t('state.loading')}</p>}{job.data&&<><p>{t(`reports.${job.data.status}`)}</p><p>{t('reports.expiry')}: {`${formatDateOnly(cairoIsoDate(job.data.expiresAt))} ${new Date(job.data.expiresAt).toLocaleTimeString(locale,{timeZone:'Africa/Cairo',hour:'2-digit',minute:'2-digit'})}`}</p>{job.data.error&&<p role="alert">{job.data.error==='reports.tooLarge'?t('reports.tooLarge'):t('reports.generationFailed')}</p>}{job.data.status==='READY'&&<Button disabled={busy} onClick={()=>void download()}>{t('reports.download')}</Button>}</>}</section>;
}
function ReportView({query,onCount}:{query:ReportQuery;onCount:(count:number|null)=>void}) {
 const {t,locale}=useLocale(),auth=useAuth(),page=useScoped<ReportPage>(`reports?${new URLSearchParams(Object.entries(query).map(([k,v])=>[k,String(v)]))}`);
 useEffect(()=>onCount(page.data?.totalCount??null),[page.data?.totalCount,onCount]);
 const [format,setFormat]=useState<'PDF'|'XLSX'>('PDF'),[job,setJob]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<ReturnType<typeof errorKey>|null>(null),[retry,setRetry]=useState(false);const request=useRef<object|null>(null),generation=useRef(0);
 useEffect(()=>{const clear=()=>{generation.current++;setJob(null);setError(null);request.current=null;setRetry(false);};window.addEventListener('nursery:scope-refresh',clear);window.addEventListener('focus',clear);return()=>{clear();window.removeEventListener('nursery:scope-refresh',clear);window.removeEventListener('focus',clear);};},[]);
 async function create() {if(busy)return;setBusy(true);setError(null);const started=generation.current;const filters={...query} as Partial<ReportQuery>;delete filters.limit;delete filters.offset;request.current??={...filters,format,locale,operationId:crypto.randomUUID()};try{const result=await auth.client.business<ReportExport>('reports/exports','POST',request.current);if(started===generation.current){setJob(result.id);setRetry(false);}}catch(e){if(started===generation.current){setError(errorKey(e));setRetry(true);}auth.handleError(e);}finally{setBusy(false);}}
 return <>{page.error&&<p role="alert">{t(page.error)}</p>}{!page.data&&!page.error&&<p role="status">{t('state.loading')}</p>}{page.data&&<><StatGrid label={reportText(locale,query.kind)}><StatCard tone="cyan" icon="overview" label={t('reports.rows')} countTo={page.data.totalCount} value={page.data.totalCount} numeric/>{reportHasMoney(query.kind)&&<StatCard tone="magenta" icon="finance" label={t('reports.total')} value={money(page.data.totals.amount)} numeric/>}</StatGrid>{page.data.warnings.map(w=><p key={w}>{t(`reports.${w}` as 'reports.CURRENT_SNAPSHOT')}</p>)}{!page.data.rows.length&&<p>{t('reports.empty')}</p>}<ResponsiveTable caption={reportText(locale,query.kind)} rows={page.data.rows} rowKey={r=>r.id} columns={[
 {key:'date',heading:t('reports.date'),cell:r=>r.date?formatDateOnly(r.date):'—'},
 {key:'label',heading:t('reports.label'),cell:r=>r.label},
 {key:'category',heading:t('reports.category'),cell:r=>r.category?reportCategoryText(locale,query.kind,r.category):'—'},
 {key:'amount',heading:t('reports.amount'),numeric:true,cell:r=>r.amount!==null?money(r.amount):'—'},
 {key:'branch',heading:t('reports.branch'),cell:r=>r.details.branch},
 {key:'classroom',heading:t('reports.classroom'),cell:r=>r.details.classroom??'—'},
 {key:'details',heading:t('reports.details'),cell:r=>Object.entries(r.details).filter(([k,v])=>k!=='branch'&&k!=='classroom'&&v!==null).map(([k,v])=><p key={k}>{reportText(locale,k)}: {reportDetailValue(locale,k,v!,formatDateOnly)}</p>)}
 ]}/><p>{t('reports.limit')}</p><SelectField label={t('reports.format')} value={format} disabled={busy||retry||job!==null} onChange={e=>setFormat(e.target.value as 'PDF'|'XLSX')}><option>PDF</option><option>XLSX</option></SelectField>{!job&&<Button disabled={busy} onClick={()=>void create()}>{t(retry?'reports.retry':'reports.export')}</Button>}{error&&<p role="alert">{t(error)}</p>}{job&&<><ExportStatus id={job}/><Button onClick={()=>{setJob(null);request.current=null;}}>{t('reports.new')}</Button></>}</>}</>;
}
export function ReportsScreen() {
 const {t,locale}=useLocale(),options=useScoped<ReportOptions>('reports/options');const [kind,setKind]=useState<ReportKind>('CASH_RESULT'),[from,setFrom]=useState(`${cairoIsoDate().slice(0,7)}-01`),[to,setTo]=useState(cairoIsoDate()),[branch,setBranch]=useState(''),[classroom,setClassroom]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState<ReportQuery|null>(null),[invalid,setInvalid]=useState(false),[totalCount,setTotalCount]=useState<number|null>(null);
 const selected=options.data?.kinds.includes(kind)?kind:options.data?.kinds[0];
 function submit(e:FormEvent){e.preventDefault();if(!selected||!from||!to||from>to){setInvalid(true);return;}setInvalid(false);setQuery({kind:selected,from,to,...(branch?{branchId:branch}:{}),...(classroom?{classroomId:classroom}:{}),...(category?{categoryId:category}:{}),limit:20,offset:0});}
 return <main className="organization-page"><Card title={t('reports.title')}>{options.error&&<p role="alert">{t(options.error)}</p>}{!options.data&&!options.error&&<p role="status">{t('state.loading')}</p>}{options.data&&<><form onSubmit={submit}><fieldset className="organization-fields"><legend>{t('reports.title')}</legend><SelectField label={t('reports.kind')} value={selected} onChange={e=>{setKind(e.target.value as ReportKind);setCategory('');}}>{options.data.kinds.map(k=><option key={k} value={k}>{reportText(locale,k)}</option>)}</SelectField><DateField label={t('reports.from')} value={from} required onValueChange={setFrom}/><DateField label={t('reports.to')} value={to} required onValueChange={setTo}/><SelectField label={t('reports.branch')} value={branch} onChange={e=>{setBranch(e.target.value);setClassroom('');}}><option value="">{t('reports.all')}</option>{options.data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</SelectField><SelectField label={t('reports.classroom')} value={classroom} onChange={e=>setClassroom(e.target.value)}><option value="">{t('reports.all')}</option>{options.data.classrooms.filter(c=>!branch||c.branchId===branch).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><SelectField label={t('reports.category')} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t('reports.all')}</option>{options.data.categories.filter(c=>selected&&c.kinds.includes(selected)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><Button type="submit">{t('reports.apply')}</Button></fieldset></form>{invalid&&<p role="alert">{t('reports.invalid')}</p>}{query&&<><ReportView key={JSON.stringify(query)} query={query} onCount={setTotalCount}/><Button disabled={query.offset===0} onClick={()=>setQuery({...query,offset:Math.max(0,query.offset-20)})}>{t('reports.previous')}</Button><Button disabled={totalCount===null||query.offset+20>=totalCount||query.offset>=100000} onClick={()=>setQuery({...query,offset:query.offset+20})}>{t('reports.next')}</Button></>}</>}</Card></main>;
}
