export const licensingEnglish = {
  'licensing.suspendedTitle': 'Subscription suspended',
  'licensing.suspendedBody': 'The nursery subscription is past its grace period. Normal access is paused. Please contact the nursery or Superadmin support to renew.',
  'licensing.graceWarning': 'The nursery subscription is in its grace period. Please renew soon to avoid a service pause.',
  'licensing.title': 'Subscriptions, slots, and support',
  'licensing.settingsTitle': 'Nursery settings',
  'licensing.status': 'Subscription status',
  'licensing.status.NOT_CONFIGURED': 'Not configured yet',
  'licensing.status.ACTIVE': 'Active',
  'licensing.status.GRACE': 'In grace period',
  'licensing.status.SUSPENDED': 'Suspended',
  'licensing.capacities': 'Purchased capacities and pricing',
  'licensing.parentCapacity': 'Parent account capacity',
  'licensing.employeeCapacity': 'Employee account capacity',
  'licensing.parentUnitPrice': 'Parent unit price (EGP)',
  'licensing.employeeUnitPrice': 'Employee unit price (EGP)',
  'licensing.period': 'Billing period',
  'licensing.periodMonthly': 'Monthly',
  'licensing.periodYearly': 'Yearly',
  'licensing.startsOn': 'Subscription starts on',
  'licensing.validUntil': 'Valid until',
  'licensing.graceDays': 'Grace days',
  'licensing.overrideAmount': 'Agreed total override (EGP)',
  'licensing.overrideReason': 'Override reason',
  'licensing.supportContact': 'Support contact details',
  'licensing.estimate': 'Period estimate: {amount}',
  'licensing.estimateHelp': 'Uses purchased capacities, not active logins. An agreed override replaces the calculated estimate.',
  'licensing.parentReserved': 'Parent slots reserved: {count} / {capacity}',
  'licensing.employeeReserved': 'Employee slots reserved: {count} / {capacity}',
  'licensing.save': 'Save',
  'licensing.saved': 'Saved.',
  'licensing.renewalPayments': 'Manual renewal payments',
  'licensing.recordPayment': 'Record renewal payment',
  'licensing.periodStart': 'Period start',
  'licensing.periodEnd': 'Period end',
  'licensing.amount': 'Amount (EGP)',
  'licensing.method': 'Payment method / reference',
  'licensing.note': 'Note',
  'licensing.provisioning': 'Provision new accounts',
  'licensing.provisionStaff': 'Create staff login',
  'licensing.provisionParent': 'Create parent login',
  'licensing.username': 'Username',
  'licensing.temporaryPassword': 'Temporary password (shown once)',
  'licensing.accountId': 'Account ID',
  'licensing.reason': 'Reason',
  'licensing.publicMessage': 'Message shown to the account (optional)',
  'licensing.untilDate': 'Blocked until (optional)',
  'licensing.release': 'Release seat (Superadmin only)',
  'licensing.restore': 'Restore released account',
  'licensing.deactivate': 'Deactivate staff account',
  'licensing.reactivate': 'Reactivate staff account',
  'licensing.block': 'Block parent account',
  'licensing.unblock': 'Unblock parent account',
  'licensing.actionDone': 'Action completed.',
  'licensing.modules': 'Module availability',
  'licensing.modulesHelp': 'Applies to every branch. Disabling pauses dependent operations while keeping existing history.',
  'licensing.module.FINANCE': 'Finance',
  'licensing.module.ATTENDANCE': 'Attendance',
  'licensing.module.EXAMS': 'Exams',
  'licensing.module.HOMEWORK': 'Homework',
  'licensing.module.HEALTH': 'Health',
  'licensing.module.PICKUP': 'Authorized pickup',
  'licensing.module.INCIDENTS': 'Incidents',
  'licensing.moduleEnabled': 'Enabled',
  'licensing.moduleDisabled': 'Disabled',
  'licensing.preview': 'Preview impact',
  'licensing.catchupRequired': 'Review the catch-up preview and confirm before re-enabling.',
  'licensing.catchupAcknowledge': 'I reviewed the missing-period preview and want to re-enable this module',
  'licensing.noMissingPeriods': 'No missing service periods to catch up (billing generation arrives in a later phase).',
  'licensing.apply': 'Apply',
  'licensing.branding': 'Nursery brand and theme',
  'licensing.name': 'Nursery name',
  'licensing.logoPath': 'Logo path',
  'licensing.contactPhone': 'Contact phone',
  'licensing.contactEmail': 'Contact email',
  'licensing.theme.brandPink': 'Brand pink',
  'licensing.theme.softPink': 'Soft pink',
  'licensing.theme.peach': 'Peach',
  'licensing.theme.paleYellow': 'Pale yellow',
  'licensing.theme.text': 'Text',
  'licensing.theme.surface': 'Surface',
  'licensing.theme.background': 'Background',
  'licensing.theme.strongPinkButton': 'Strong pink button',
  'licensing.theme.success': 'Success',
  'licensing.theme.warning': 'Warning',
  'licensing.theme.error': 'Error',
  'licensing.contrastFail': 'Some color pairs do not meet the 4.5:1 readability minimum: {pairs}',
  'licensing.contrastOk': 'All checked color pairs meet the readability minimum.',
  'licensing.supportContext': 'Superadmin support tools',
  'licensing.supportContextHelp': 'Every use of this area is recorded with your stated reason.',
  'licensing.openSupportContext': 'Open audited support view',
  'licensing.staffCount': 'Staff accounts: {count}',
  'licensing.parentCount': 'Parent accounts: {count}',
  'licensing.notConfigured': 'Licensing is not configured yet. Set capacities and dates first.',
  'licensing.capacityExceeded': 'No available capacity remains for this account kind.',
  'licensing.belowReserved': 'This capacity is below the number of active reservations. Release seats first.',
  'licensing.noActiveReservation': 'This account has no active reservation to release.',
  'licensing.notReleased': 'Only a released account can be restored.',
  'licensing.wrongAccountKind': 'This action does not apply to this account kind.',
  'licensing.useRestoreAction': 'This account was released. Use Restore released account instead.',
  'licensing.conflict': 'Check the entered values and linked records. A value may already exist.',
  'licensing.contrast': 'Some color pairs do not meet the readability minimum.'
} as const;
export const licensingArabic: Record<keyof typeof licensingEnglish, string> = {
  'licensing.suspendedTitle': 'الاشتراك موقوف',
  'licensing.suspendedBody': 'اشتراك الحضانة عدّى فترة السماح. الدخول العادي متوقف مؤقتًا. كلم إدارة الحضانة أو دعم مسؤول النظام عشان تجدد.',
  'licensing.graceWarning': 'اشتراك الحضانة في فترة السماح. جدد قريب عشان تتجنب توقف الخدمة.',
  'licensing.title': 'الاشتراكات والمقاعد والدعم',
  'licensing.settingsTitle': 'إعدادات الحضانة',
  'licensing.status': 'حالة الاشتراك',
  'licensing.status.NOT_CONFIGURED': 'لسه متعملوش إعداد',
  'licensing.status.ACTIVE': 'فعّال',
  'licensing.status.GRACE': 'في فترة السماح',
  'licensing.status.SUSPENDED': 'موقوف',
  'licensing.capacities': 'السعة المشتراة والأسعار',
  'licensing.parentCapacity': 'سعة حسابات أولياء الأمور',
  'licensing.employeeCapacity': 'سعة حسابات الموظفين',
  'licensing.parentUnitPrice': 'سعر وحدة ولي الأمر (جنيه)',
  'licensing.employeeUnitPrice': 'سعر وحدة الموظف (جنيه)',
  'licensing.period': 'فترة الفوترة',
  'licensing.periodMonthly': 'شهري',
  'licensing.periodYearly': 'سنوي',
  'licensing.startsOn': 'تاريخ بداية الاشتراك',
  'licensing.validUntil': 'صالح حتى',
  'licensing.graceDays': 'أيام السماح',
  'licensing.overrideAmount': 'إجمالي متفق عليه بديل (جنيه)',
  'licensing.overrideReason': 'سبب الإجمالي البديل',
  'licensing.supportContact': 'بيانات التواصل مع الدعم',
  'licensing.estimate': 'تقدير الفترة: {amount}',
  'licensing.estimateHelp': 'بيستخدم السعة المشتراة، مش عدد الحسابات الفعّالة. الإجمالي المتفق عليه بيحل محل الحساب التلقائي.',
  'licensing.parentReserved': 'مقاعد أولياء الأمور المحجوزة: {count} / {capacity}',
  'licensing.employeeReserved': 'مقاعد الموظفين المحجوزة: {count} / {capacity}',
  'licensing.save': 'حفظ',
  'licensing.saved': 'تم الحفظ.',
  'licensing.renewalPayments': 'مدفوعات التجديد اليدوية',
  'licensing.recordPayment': 'تسجيل دفعة تجديد',
  'licensing.periodStart': 'بداية الفترة',
  'licensing.periodEnd': 'نهاية الفترة',
  'licensing.amount': 'المبلغ (جنيه)',
  'licensing.method': 'طريقة الدفع / المرجع',
  'licensing.note': 'ملاحظة',
  'licensing.provisioning': 'إنشاء حسابات جديدة',
  'licensing.provisionStaff': 'إنشاء حساب موظف',
  'licensing.provisionParent': 'إنشاء حساب ولي أمر',
  'licensing.username': 'اسم المستخدم',
  'licensing.temporaryPassword': 'كلمة سر مؤقتة (بتظهر مرة واحدة)',
  'licensing.accountId': 'معرّف الحساب',
  'licensing.reason': 'السبب',
  'licensing.publicMessage': 'رسالة تظهر للحساب (اختياري)',
  'licensing.untilDate': 'محظور حتى (اختياري)',
  'licensing.release': 'تحرير المقعد (لمسؤول النظام فقط)',
  'licensing.restore': 'استرجاع حساب محرّر',
  'licensing.deactivate': 'تعطيل حساب موظف',
  'licensing.reactivate': 'إعادة تفعيل حساب موظف',
  'licensing.block': 'حظر حساب ولي أمر',
  'licensing.unblock': 'إلغاء حظر حساب ولي أمر',
  'licensing.actionDone': 'تم الإجراء.',
  'licensing.modules': 'إتاحة الوحدات',
  'licensing.modulesHelp': 'بتنطبق على كل الفروع. التعطيل بيوقف العمليات المرتبطة وبيحافظ على السجل التاريخي.',
  'licensing.module.FINANCE': 'الحسابات المالية',
  'licensing.module.ATTENDANCE': 'الحضور',
  'licensing.module.EXAMS': 'الاختبارات',
  'licensing.module.HOMEWORK': 'الواجبات',
  'licensing.module.HEALTH': 'الصحة',
  'licensing.module.PICKUP': 'الاستلام المصرّح به',
  'licensing.module.INCIDENTS': 'الحوادث',
  'licensing.moduleEnabled': 'مفعّل',
  'licensing.moduleDisabled': 'معطّل',
  'licensing.preview': 'معاينة الأثر',
  'licensing.catchupRequired': 'راجع معاينة الفترات الناقصة وأكّد قبل إعادة التفعيل.',
  'licensing.catchupAcknowledge': 'راجعت معاينة الفترات الناقصة وعايز أعيد تفعيل الوحدة دي',
  'licensing.noMissingPeriods': 'مفيش فترات خدمة ناقصة تتلحق (توليد الفواتير بييجي في مرحلة لاحقة).',
  'licensing.apply': 'تطبيق',
  'licensing.branding': 'هوية الحضانة والألوان',
  'licensing.name': 'اسم الحضانة',
  'licensing.logoPath': 'مسار الشعار',
  'licensing.contactPhone': 'رقم التواصل',
  'licensing.contactEmail': 'إيميل التواصل',
  'licensing.theme.brandPink': 'الوردي الأساسي',
  'licensing.theme.softPink': 'الوردي الفاتح',
  'licensing.theme.peach': 'الخوخي',
  'licensing.theme.paleYellow': 'الأصفر الفاتح',
  'licensing.theme.text': 'لون النص',
  'licensing.theme.surface': 'السطح',
  'licensing.theme.background': 'الخلفية',
  'licensing.theme.strongPinkButton': 'زر الوردي الغامق',
  'licensing.theme.success': 'النجاح',
  'licensing.theme.warning': 'التنبيه',
  'licensing.theme.error': 'الخطأ',
  'licensing.contrastFail': 'بعض أزواج الألوان مش واضحة بما فيه الكفاية (أقل من 4.5:1): {pairs}',
  'licensing.contrastOk': 'كل أزواج الألوان اللي اتفحصت واضحة بما فيه الكفاية.',
  'licensing.supportContext': 'أدوات دعم مسؤول النظام',
  'licensing.supportContextHelp': 'كل استخدام للمنطقة دي بيتسجل مع السبب اللي بتكتبه.',
  'licensing.openSupportContext': 'افتح شاشة الدعم المسجّلة',
  'licensing.staffCount': 'حسابات الموظفين: {count}',
  'licensing.parentCount': 'حسابات أولياء الأمور: {count}',
  'licensing.notConfigured': 'الترخيص لسه متعملوش إعداد. حدد السعات والتواريخ الأول.',
  'licensing.capacityExceeded': 'مفيش سعة متاحة لنوع الحساب ده.',
  'licensing.belowReserved': 'السعة دي أقل من عدد الحجوزات الفعّالة. حرر مقاعد الأول.',
  'licensing.noActiveReservation': 'الحساب ده معندوش حجز فعّال يتحرر.',
  'licensing.notReleased': 'الاسترجاع بيكون بس للحساب المحرَّر.',
  'licensing.wrongAccountKind': 'الإجراء ده مش بينطبق على نوع الحساب ده.',
  'licensing.useRestoreAction': 'الحساب ده اتحرر. استخدم استرجاع حساب محرّر بدل كده.',
  'licensing.conflict': 'راجع القيم المدخلة والسجلات المرتبطة. ممكن قيمة تكون موجودة بالفعل.',
  'licensing.contrast': 'بعض أزواج الألوان مش واضحة بما فيه الكفاية.'
};
