import type { Transaction } from '@nursery/db';
import type { Capability,ReportKind,ReportQuery,ReportPage,ReportRow } from '@nursery/contracts';
import { cairoIsoDate } from '@nursery/domain';
import { financeScope } from '../finance/core.js';
import { requireCapability,requireBranch,requireRecord,denied,type Policy } from '../organization/policy.js';
import { SafeError } from '../../errors.js';
export const MAX_REPORT_EXPORT_ROWS=10_000;
export function reportCapability(kind:ReportKind):Capability {if(['ATTENDANCE','EXAMS','HOMEWORK'].includes(kind))return 'learning.read';if(kind==='DOCUMENT_EXPIRY')return 'documents.manage';if(kind==='INCIDENTS')return 'incidents.read';if(kind==='BUS')return 'transport.read';if(kind==='TRIPS')return 'activities.read';if(['CHILDREN','CAPACITY'].includes(kind))return 'children.read';return 'finance.read';}
export function authorizeReport(p:Policy,kind:ReportKind) {requireCapability(p,reportCapability(kind));if(['PAYROLL','UNPAID_PAYROLL','ACCOUNTS','TREASURY','TRANSFERS','UNATTRIBUTED_SPENDING'].includes(kind)&&p.account.kind!=='SYSTEM'&&p.scope.mode!=='BRANCH')throw denied();}
const sources:Record<ReportKind,string>={
 OTHER_INCOME:"select * from report_cash_rows where category in ('COLLECTION','COLLECTION_REVERSAL') and details->>'categoryKind'='ADDITIONAL'",UNATTRIBUTED_SPENDING:"select * from report_cash_rows where category='OPERATING_EXPENSE' and classroom_id is null",
 CASH_RESULT:"select * from report_cash_rows where category in ('COLLECTION','COLLECTION_REVERSAL','REFUND','OPERATING_EXPENSE','PAYROLL_ADVANCE','PAYROLL_SETTLEMENT')",
 COLLECTIONS:"select * from report_cash_rows where category in ('COLLECTION','COLLECTION_REVERSAL')",REFUNDS:"select * from report_cash_rows where category='REFUND'",SPENDING:"select * from report_cash_rows where category='OPERATING_EXPENSE'",TREASURY:'select * from report_cash_rows',TRANSFERS:"select * from report_cash_rows where category='INTERNAL_TRANSFER'",PAYROLL:"select * from report_cash_rows where category in ('PAYROLL_ADVANCE','PAYROLL_SETTLEMENT')",
 PENDING_EXPENSES:"select e.id::text id,e.due_on date,e.branch_id,e.classroom_id,null::uuid child_id,e.note label,e.state category,e.category_id,e.amount::numeric amount,jsonb_build_object('category',e.category_name) details from expense_states e where e.state in ('PENDING','APPROVED')",
 OUTSTANDING:"select i.id::text id,i.due_on date,o.branch_id,o.classroom_id,o.child_id,o.child_name label,o.category_name category,o.category_id,i.remaining::numeric amount,jsonb_build_object('childCode',o.child_code,'status',case when i.allocated+i.credited=0 then 'UNPAID' else 'PARTIAL' end) details from installment_balances i join receivable_obligations o on o.id=i.obligation_id where i.remaining>0",
 OVERDUE:"select i.id::text id,i.due_on date,o.branch_id,o.classroom_id,o.child_id,o.child_name label,o.category_name category,o.category_id,i.remaining::numeric amount,jsonb_build_object('childCode',o.child_code) details from installment_balances i join receivable_obligations o on o.id=i.obligation_id where i.remaining>0",
 ACCOUNTS:"select a.id::text id,null::date date,a.branch_id,null::uuid classroom_id,null::uuid child_id,a.name label,a.type category,null::uuid category_id,coalesce((select sum(m.amount) from treasury_movements m where m.account_id=a.id and m.effective_on<=$6::date),0)::numeric amount,jsonb_build_object('code',a.code) details from treasury_accounts a",
 UNPAID_PAYROLL:"select p.id::text id,p.month date,p.paying_branch_id branch_id,null::uuid classroom_id,null::uuid child_id,p.employee_name label,'UNPAID_PAYROLL'::text category,null::uuid category_id,p.remaining::numeric amount,jsonb_build_object('employeeCode',p.employee_code,'basicSalary',p.basic_salary::text,'advances',p.advances::text) details from payroll_period_balances p where p.settlement_id is null",
 CHILDREN:"select c.id::text id,null::date date,c.branch_id,c.classroom_id,c.id child_id,c.full_name label,c.status category,null::uuid category_id,null::numeric amount,jsonb_build_object('code',c.code,'birthDate',c.birth_date::text) details from children c",
 CAPACITY:"select k.id::text id,null::date date,k.branch_id,k.id classroom_id,null::uuid child_id,k.name label,'CAPACITY'::text category,null::uuid category_id,null::numeric amount,jsonb_build_object('capacity',k.capacity::text,'occupancy',count(c.id)::text,'available',greatest(k.capacity-count(c.id),0)::text,'overCapacity',greatest(count(c.id)-k.capacity,0)::text) details from classrooms k left join children c on c.classroom_id=k.id and c.status='ACTIVE' group by k.id",
 ATTENDANCE:"select s.id::text id,d.business_date date,d.branch_id,d.classroom_id,d.child_id,c.full_name label,coalesce(a.presence,'MISSING') category,null::uuid category_id,null::numeric amount,jsonb_build_object('reason',a.absence_reason) details from daily_snapshots d join daily_slots s on s.snapshot_id=d.id join checkpoint_versions v on v.configuration_id=s.configuration_id and v.definition_id=s.definition_id join children c on c.id=d.child_id left join lateral (select ar.* from attendance_records ar join learning_events le on le.id=ar.event_id where le.slot_id=s.id order by le.revision desc limit 1) a on true where v.definition->>'kind'='ATTENDANCE'",
 EXAMS:"select e.id::text||'/'||d.child_id::text id,e.assessed_on date,e.branch_id,e.classroom_id,d.child_id,c.full_name label,coalesce(r.outcome,'MISSING') category,e.subject_id category_id,null::numeric amount,jsonb_build_object('exam',e.name,'subject',e.subject_name,'format',e.grade_format,'maximumMarks',e.maximum_marks::text,'score',r.score::text,'gradeLabel',r.label) details from exams e join daily_snapshots d on d.classroom_id=e.classroom_id and d.business_date=e.assessed_on join children c on c.id=d.child_id left join lateral (select er.* from exam_results er join learning_events le on le.id=er.event_id where er.exam_id=e.id and er.child_id=d.child_id order by le.revision desc limit 1) r on true",
 HOMEWORK:"select h.assignment_id::text||'/'||h.child_id::text id,a.due_on date,a.branch_id,a.classroom_id,h.child_id,h.child_name label,coalesce(o.status->>'outcome','PENDING') category,null::uuid category_id,null::numeric amount,jsonb_build_object('assignment',v.title,'assignedOn',a.assigned_on::text,'effectiveOn',o.effective_on::text) details from homework_recipients h join homework_assignments a on a.id=h.assignment_id join lateral (select title from homework_versions where assignment_id=a.id order by revision desc limit 1) v on true left join lateral (select status,effective_on from homework_outcomes where assignment_id=a.id and child_id=h.child_id and effective_on<=$6::date order by revision desc limit 1) o on true",
 BUS:"select b.id::text id,b.period_start date,b.branch_id,b.classroom_id,b.child_id,b.child_name label,'BUS'::text category,b.category_id,b.amount::numeric amount,jsonb_build_object('childCode',b.child_code,'until',b.period_end::text,'paid',(b.amount=0 or i.remaining=0)::text,'permission',coalesce((select enabled from bus_permission_events where subscription_id=b.id order by created_at desc,id desc limit 1),b.administrative_permission)::text,'active',(c.status='ACTIVE')::text) details from bus_subscriptions b join children c on c.id=b.child_id left join installment_balances i on i.id=b.installment_id",
 TRIPS:"select ac.id::text id,a.event_date date,a.branch_id,ac.classroom_id,ac.child_id,ac.child_name label,a.status category,a.category_id,a.fee::numeric amount,jsonb_build_object('trip',a.title,'childCode',ac.child_code,'paid',(a.fee=0 or i.remaining=0)::text,'consented',coalesce((select consented from activity_consents where activity_child_id=ac.id order by created_at desc,id desc limit 1),false)::text) details from activities a join activity_children ac on ac.activity_id=a.id left join installment_balances i on i.id=ac.installment_id",
 INCIDENTS:"select i.id::text id,i.occurred_on date,i.branch_id,i.classroom_id,i.child_id,c.full_name label,i.status category,null::uuid category_id,null::numeric amount,jsonb_build_object('description',i.description,'actionTaken',i.action_taken,'guardianInformed',i.guardian_informed::text,'followUp',i.follow_up) details from incidents i join children c on c.id=i.child_id",
 DOCUMENT_EXPIRY:"select d.id::text id,d.expires_on date,c.branch_id,c.classroom_id,c.id child_id,d.name label,'DOCUMENT'::text category,null::uuid category_id,null::numeric amount,jsonb_build_object('child',c.full_name,'childCode',c.code) details from child_documents d join children c on c.id=d.child_id where not d.retired and d.expires_on is not null",
 RECEIVABLE_TRANSFERS:"select t.id::text||'/'||leg.direction id,t.effective_on date,leg.branch_id,leg.classroom_id,t.child_id,t.child_name label,leg.direction category,null::uuid category_id,leg.sign*t.amount amount,jsonb_build_object('childCode',t.child_code) details from child_branch_transfers t cross join lateral (values(t.source_branch_id,t.source_classroom_id,'TRANSFERRED_OUT',-1),(t.destination_branch_id,t.destination_classroom_id,'TRANSFERRED_IN',1)) leg(branch_id,classroom_id,direction,sign)"
};
export class ReportEngine {
 async authorizeFilters(tx:Transaction,p:Policy,q:Pick<ReportQuery,'kind'|'classroomId'|'branchId'>) {
  authorizeReport(p,q.kind);if(q.branchId)requireBranch(p,q.branchId);
  if(q.classroomId){const c=(await tx.query<{branch_id:string}>('select branch_id from classrooms where id=$1',[q.classroomId])).rows[0];if(!c||q.branchId&&c.branch_id!==q.branchId)throw denied();requireRecord(p,reportCapability(q.kind),{branchId:c.branch_id,classroomId:q.classroomId});}
 }
 query(p:Policy,q:ReportQuery) {authorizeReport(p,q.kind);if(q.branchId)requireBranch(p,q.branchId);if(q.classroomId&&p.account.kind!=='SYSTEM'&&p.scope.mode==='CLASSROOM'&&!p.scope.classroomIds.includes(q.classroomId))throw denied();const s=financeScope(p,reportCapability(q.kind),'x');const values:unknown[]=[...s.values,q.from,q.to,q.branchId??null,q.classroomId??null,q.categoryId??null,cairoIsoDate()];let date="(x.date is null or x.date between $5::date and $6::date)";if(['OUTSTANDING','OVERDUE'].includes(q.kind))date=`x.date<=$6::date${q.kind==='OVERDUE'?' and x.date<$10::date':''}`;if(q.kind==='BUS')date="x.date<=$6::date and (x.details->>'until')::date>=$5::date";return {sql:`select x.id,x.date::text date,x.branch_id as "branchId",x.classroom_id as "classroomId",x.child_id as "childId",x.label,x.category,x.amount::text amount,x.details||jsonb_build_object('branch',b.code,'classroom',k.name) details from (${sources[q.kind]}) x join branches b on b.id=x.branch_id left join classrooms k on k.id=x.classroom_id where ${s.sql}${['ATTENDANCE','EXAMS','HOMEWORK','BUS','TRIPS','INCIDENTS'].includes(q.kind)?' and exists(select 1 from children current_child where current_child.id=x.child_id and ($1::boolean or current_child.branch_id=any($2::uuid[])) and ($3::boolean or current_child.classroom_id=any($4::uuid[])))':''} and $5::date<=$6::date and ${date} and ($7::uuid is null or x.branch_id=$7) and ($8::uuid is null or x.classroom_id=$8) and ($9::uuid is null or x.category_id=$9) and $10::date is not null`,values};}

 private readQuery(p:Policy,q:ReportQuery,exportAll=false) {
  const {sql,values}=this.query(p,q);
  // One PostgreSQL statement/snapshot ties counts, money and emitted rows together.
  // Concurrent collections cannot produce a mismatched total or silent export truncation.
  return {sql:`with filtered as materialized (${sql}), totals as (select count(*)::int count,coalesce(sum(amount::numeric),0)::text amount from filtered)
   select totals.*,coalesce((select jsonb_agg(row_to_json(r)) from (select * from filtered where not $13::boolean or (select count from totals)<=${MAX_REPORT_EXPORT_ROWS} order by date desc nulls last,id limit $11 offset $12) r),'[]'::jsonb) rows from totals`,values:[...values,exportAll?MAX_REPORT_EXPORT_ROWS:q.limit,exportAll?0:q.offset,exportAll]};
 }
 async read(tx:Transaction,p:Policy,q:ReportQuery,exportAll=false):Promise<ReportPage> {
  await this.authorizeFilters(tx,p,q);
  const {sql,values}=this.readQuery(p,q,exportAll);
  const total=(await tx.query<{count:number;amount:string;rows:ReportRow[]}>(sql,values)).rows[0];
  if(exportAll&&total.count>MAX_REPORT_EXPORT_ROWS)throw new SafeError('VALIDATION_ERROR','reports.tooLarge',false,409);
  const warnings:string[]=[];if(['CHILDREN','CAPACITY'].includes(q.kind))warnings.push('CURRENT_SNAPSHOT');if(['OUTSTANDING','OVERDUE'].includes(q.kind))warnings.push('CURRENT_RECEIVABLES');if(q.kind==='CASH_RESULT')warnings.push('CASH_CONTRIBUTION');
  return {kind:q.kind,from:q.from,to:q.to,rows:total.rows,totalCount:total.count,totals:{amount:total.amount},warnings};
 }
 async explain(tx:Transaction,p:Policy,q:ReportQuery) {await this.authorizeFilters(tx,p,q);const {sql,values}=this.readQuery(p,q);return (await tx.query(`explain (analyze,buffers,format json) ${sql}`,values)).rows[0]['QUERY PLAN'];}
}
