import { randomUUID,createHash } from 'node:crypto';
import type { CurrentAccount,ReportExport,ReportExportInput,ReportKind,ReportOptions,PolicyScope } from '@nursery/contracts';
import { reportKinds,reportQuerySchema,reportExportInputSchema } from '@nursery/contracts';
import type { Database,Transaction } from '@nursery/db';
import { cairoIsoDate } from '@nursery/domain';
import { SafeError } from '../../errors.js';
import { requireCapability,requireRecord,denied,loadPolicy,type Policy } from '../organization/policy.js';
import type { ChildService } from '../children/service.js';
import { PrivateDocumentStore,documentHash } from '../children/private-store.js';
import { ReportEngine,authorizeReport,reportCapability,MAX_REPORT_EXPORT_ROWS } from './engine.js';
import { renderReportPdf,renderReportXlsx,type ReportBrand } from './render.js';
type Scope=PolicyScope&{system:boolean};
type Resource={branchId:string;classroomId:string|null;childId:string|null};
type Job={id:string;creator_id:string;kind:ReportKind;format:'PDF'|'XLSX';filters:ReportExportInput;scope:Scope;resources:Resource[];status:ReportExport['status'];expires_at:Date;row_count:number|null;error_code:string|null;storage_key:string|null;sha256:string|null;mime_type:string|null;attempts:number;request_hash:string};
const MAX_BYTES=64*1024*1024;
export class ReportService {
 readonly engine=new ReportEngine();readonly store:PrivateDocumentStore;
 constructor(readonly children:ChildService|null,root:string) {this.store=new PrivateDocumentStore(root,'report-exports',MAX_BYTES);}
 private session<T>(token:string,work:(tx:Transaction,p:Policy)=>Promise<T>) {if(!this.children)throw new Error('Authenticated report service required');return this.children.withPolicy(token,work);}
 private summary(j:Job):ReportExport {return {id:j.id,status:j.expires_at.getTime()<=Date.now()?'EXPIRED':j.status,format:j.format,expiresAt:j.expires_at.toISOString(),rowCount:j.row_count,error:j.error_code};}
 private validateScope(p:Policy,j:Job) {authorizeReport(p,j.kind);if(p.account.kind==='SYSTEM')return;if(j.scope.system||j.scope.mode==='BRANCH'&&p.scope.mode==='CLASSROOM'||!j.scope.branchIds.every(id=>p.scope.branchIds.includes(id))||j.scope.mode==='CLASSROOM'&&p.scope.mode==='CLASSROOM'&&!j.scope.classroomIds.every(id=>p.scope.classroomIds.includes(id)))throw denied();}
 async report(token:string,raw:unknown) {const q=reportQuerySchema.parse(raw);return this.session(token,(tx,p)=>this.engine.read(tx,p,q));}
 async options(token:string):Promise<ReportOptions> {return this.session(token,async(tx,p)=>{const kinds=reportKinds.filter(k=>{try{authorizeReport(p,k);return true;}catch{return false;}});if(!kinds.length)throw denied();const system=p.account.kind==='SYSTEM';const branches=(await tx.query<{id:string;name:string}>('select id,name from branches where $1::boolean or id=any($2::uuid[]) order by code',[system,p.scope.branchIds])).rows;const classrooms=(await tx.query<{id:string;branchId:string;name:string}>('select id,branch_id as "branchId",name from classrooms where ($1::boolean or branch_id=any($2::uuid[])) and ($3::boolean or id=any($4::uuid[])) order by code',[system,p.scope.branchIds,system||p.scope.mode==='BRANCH',p.scope.classroomIds])).rows;const categories:ReportOptions['categories']=[];if(kinds.includes('OUTSTANDING'))for(const r of (await tx.query<{id:string;name:string}>('select id,name from fee_categories order by name')).rows)categories.push({...r,kinds:['CASH_RESULT','OTHER_INCOME','COLLECTIONS','OUTSTANDING','OVERDUE','BUS','TRIPS','TREASURY','REFUNDS']});if(kinds.includes('SPENDING'))for(const r of (await tx.query<{id:string;name:string}>('select id,name from expense_categories order by name')).rows)categories.push({...r,kinds:['CASH_RESULT','SPENDING','UNATTRIBUTED_SPENDING','PENDING_EXPENSES','TREASURY']});if(kinds.includes('EXAMS'))for(const r of (await tx.query<{id:string;name:string}>('select id,name from subjects order by name')).rows)categories.push({...r,kinds:['EXAMS']});return {kinds,branches,classrooms,categories,maxExportRows:MAX_REPORT_EXPORT_ROWS};});}
 async createExport(token:string,raw:unknown) {const input=reportExportInputSchema.parse(raw);return this.session(token,async(tx,p)=>{await this.engine.authorizeFilters(tx,p,input);this.engine.query(p,{...input,limit:1,offset:0});const {operationId,...request}=input;const hash=createHash('sha256').update(JSON.stringify(request)).digest('hex');await tx.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`report/${p.account.id}/${operationId}`]);const old=(await tx.query<Job>('select * from report_exports where creator_id=$1 and operation_id=$2',[p.account.id,operationId])).rows[0];if(old){this.validateScope(p,old);if(old.request_hash!==hash)throw new SafeError('IDEMPOTENCY_CONFLICT','finance.operationConflict',false,409);return this.summary(old);}const id=randomUUID();await tx.query("insert into report_exports(id,creator_id,kind,format,filters,scope,status,expires_at,operation_id,request_hash) values($1,$2,$3,$4,$5,$6,'PENDING',now()+interval '24 hours',$7,$8)",[id,p.account.id,input.kind,input.format,JSON.stringify(input),JSON.stringify({...p.scope,system:p.account.kind==='SYSTEM'}),operationId,hash]);return this.summary((await tx.query<Job>('select * from report_exports where id=$1',[id])).rows[0]);});}
 private async owned(tx:Transaction,p:Policy,id:string) {const j=(await tx.query<Job>('select * from report_exports where id=$1 and creator_id=$2',[id,p.account.id])).rows[0];if(!j)throw denied();this.validateScope(p,j);return j;}
 async status(token:string,id:string) {return this.session(token,async(tx,p)=>this.summary(await this.owned(tx,p,id)));}
 async download(token:string,id:string) {return this.session(token,async(tx,p)=>{
  const j=await this.owned(tx,p,id);if(j.expires_at.getTime()<=Date.now()||j.status==='EXPIRED')throw denied();if(j.status==='PENDING')return {pending:true as const};if(j.status!=='READY'||!j.storage_key||!j.sha256||!j.mime_type)throw denied();
  const ids=[...new Set(j.resources.flatMap(r=>r.childId?[r.childId]:[]))];
  const children=new Map((await tx.query<{id:string;branch_id:string;classroom_id:string|null}>('select id,branch_id,classroom_id from children where id=any($1::uuid[])',[ids])).rows.map(c=>[c.id,c]));
  for(const r of j.resources){requireRecord(p,reportCapability(j.kind),{branchId:r.branchId,classroomId:r.classroomId??undefined,childId:r.childId??undefined});if(r.childId&&['ATTENDANCE','EXAMS','HOMEWORK','BUS','TRIPS','INCIDENTS','DOCUMENT_EXPIRY','CHILDREN'].includes(j.kind)){const c=children.get(r.childId);if(!c)throw denied();requireRecord(p,reportCapability(j.kind),{branchId:c.branch_id,classroomId:c.classroom_id??undefined,childId:r.childId});}}
  return {pending:false as const,bytes:await this.store.read(j.storage_key,j.sha256),mimeType:j.mime_type,filename:`report-${j.kind.toLowerCase()}.${j.format==='PDF'?'pdf':'xlsx'}`};
 });}
 async runBatch(db:Database) {
  await this.cleanupBatch(db);
  const candidate=(await db.pool.query<{id:string;creator_id:string}>("select id,creator_id from report_exports where status='PENDING' and next_attempt_at<=now() and expires_at>now() order by created_at,id limit 1")).rows[0];if(!candidate)return {processed:0};let key:string|null=null;
  try {return await db.transaction(async tx=>{await tx.query('select version from policy_revision for share');const a=(await tx.query<{id:string;username_normalized:string;kind:CurrentAccount['kind'];locale:CurrentAccount['locale'];must_change_password:boolean;status:string;status_until:string|null}>('select id,username_normalized,kind,locale,must_change_password,status,status_until::text from accounts where id=$1 for update',[candidate.creator_id])).rows[0];const j=(await tx.query<Job>("select * from report_exports where id=$1 and status='PENDING' and expires_at>now() for update skip locked",[candidate.id])).rows[0];if(!j)return {processed:0};if(!a||a.status!=='ACTIVE'&&!(a.status==='BLOCKED'&&a.status_until!==null&&a.status_until<cairoIsoDate()))throw denied();const p=await loadPolicy(tx,{id:a.id,username:a.username_normalized,kind:a.kind,locale:a.locale,mustChangePassword:a.must_change_password,capabilities:[],policyReady:false});this.validateScope(p,j);await tx.query("set local statement_timeout='30s'");const page=await this.engine.read(tx,{...p,scope:j.scope},{...j.filters,limit:100,offset:0},true);const brand=(await tx.query<ReportBrand>("select name,contact_phone phone,theme->>'strongPinkButton' accent,(select name from branches where id=$1::uuid) as \"branchName\",(select name from classrooms where id=$2::uuid) as \"classroomName\",coalesce((select name from fee_categories where id=$3::uuid),(select name from expense_categories where id=$3::uuid),(select name from subjects where id=$3::uuid)) as \"categoryName\" from nursery_settings where singleton",[j.filters.branchId??null,j.filters.classroomId??null,j.filters.categoryId??null])).rows[0];const bytes=j.format==='PDF'?await renderReportPdf(j.filters,page,brand):await renderReportXlsx(j.filters,page,brand);if(bytes.length>MAX_BYTES)throw new SafeError('VALIDATION_ERROR','reports.tooLarge',false,409);key=randomUUID();await this.store.write(key,bytes);const resources=[...new Map(page.rows.map(r=>[`${r.branchId}/${r.classroomId}/${r.childId}`,{branchId:r.branchId,classroomId:r.classroomId,childId:r.childId}])).values()];await tx.query("update report_exports set status='READY',storage_key=$2,mime_type=$3,byte_size=$4,sha256=$5,row_count=$6,resources=$7,completed_at=now(),attempts=attempts+1,error_code=null where id=$1",[j.id,key,j.format==='PDF'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',bytes.length,documentHash(bytes),page.totalCount,JSON.stringify(resources)]);return {processed:1};});}
  catch(error) {if(key){const linked=await db.pool.query('select 1 from report_exports where storage_key=$1',[key]);if(!linked.rowCount)await this.store.remove(key);}await db.pool.query("update report_exports set attempts=least(attempts+1,3),status=case when attempts>=2 or $2::boolean then 'FAILED' else 'PENDING' end,error_code=$3,next_attempt_at=now()+interval '30 seconds' where id=$1 and status='PENDING'",[candidate.id,error instanceof SafeError,error instanceof SafeError?error.messageKey:'reports.generationFailed']);if(!(error instanceof SafeError))throw error;return {processed:0};}
 }
 async cleanupBatch(db:Database) {return db.transaction(async tx=>{const jobs=(await tx.query<Job>("select * from report_exports where expires_at<=now() and status<>'EXPIRED' order by expires_at limit 20 for update skip locked")).rows;for(const j of jobs){if(j.storage_key)await this.store.remove(j.storage_key).catch(error=>{if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;});await tx.query("update report_exports set status='EXPIRED',storage_key=null,mime_type=null,byte_size=null,sha256=null,row_count=null where id=$1",[j.id]);}return {expired:jobs.length};});}
 async cleanup(token:string) {return this.session(token,async(_tx,p)=>{requireCapability(p,'support.access');if(!this.children)throw new Error('Authenticated service required');return this.cleanupBatch(this.children.licensing.auth.database);});}
}
